source: .
destination: ./_site
include:
  - LICENSE.txt
  - favicon.ico
  - index.html
  - main-latest.zip
  # Includes both plain and enriched -tagged.yaml distribution specs.
  - opensearch-openapi-*.yaml
  - opensearch-openapi.yaml
exclude:
  - '*'
keep_files:
  - opensearch-openapi-*.yaml
  - opensearch-openapi.yaml
