source: .
destination: ./_site
spec_remote_url: https://ci.opensearch.org/ci/dbc/snapshots/opensearch-api-specification/opensearch-openapi.yaml
include:
  - favicon.ico
  - index.html
  - opensearch-openapi.yaml
exclude:
  - '*'
keep_files:
  - opensearch-openapi.yaml
