/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/

import * as js2ts from 'json-schema-to-typescript'
import fs from 'fs/promises'
import { read_yaml } from '../helpers'
import path from "path";
import { JSONSchema } from "json-schema-to-typescript";

async function generate_typescript_from_json_schema (schema_file: string, type_name: string, ts_path: string): Promise<void> {
  const schema = read_yaml<JSONSchema>(path.join('json_schemas', schema_file))
  delete schema.properties?.$schema
  const ts = await js2ts.compile(schema, type_name, {
    cwd: 'json_schemas/',
    additionalProperties: false,
    ignoreMinAndMaxItems: true,
    unreachableDefinitions: true,
    declareExternallyReferenced: true,
    unknownAny: false,
    style: {
      singleQuote: true,
      singleAttributePerLine: true
    },
    bannerComment: `/*
    * This file was automatically generated by json-schema-to-typescript.
    * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
    * and run json-schema-to-typescript to regenerate this file by running:
    * "npm run generate-types" in a terminal.
    */
    `
  })

  ts_path = path.join('tools', 'src', ts_path)

  await fs.mkdir(path.dirname(ts_path), { recursive: true })

  await fs.writeFile(ts_path, `/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/

/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/consistent-indexed-object-style */

`
    + ts + `
/* eslint-enable @typescript-eslint/ban-types */
/* eslint-enable @typescript-eslint/consistent-indexed-object-style */
`)
}

void generate_typescript_from_json_schema('test_story.schema.yaml', 'Story', 'tester/types/story.types.ts')
void generate_typescript_from_json_schema('_superseded_operations.schema.yaml', 'SupersededOperations', 'types/superseded_operations.types.ts')