openapi: 3.1.0
info:
  title: OpenSearch Dangling_indices API
  description: OpenSearch Dangling_indices API
  version: 1.0.0
paths:
  /_dangling:
    get:
      description: Returns all dangling indices.
      externalDocs:
        url: https://opensearch.org/docs/latest/api-reference/index-apis/dangling-index/
      operationId: dangling_indices.list_dangling_indices.0
      responses:
        '200':
          $ref: '#/components/responses/dangling_indices.list_dangling_indices@200'
      x-operation-group: dangling_indices.list_dangling_indices
      x-version-added: '1.0'
      parameters: []
  /_dangling/{index_uuid}:
    delete:
      description: Deletes the specified dangling index.
      externalDocs:
        url: https://opensearch.org/docs/latest/api-reference/index-apis/dangling-index/
      operationId: dangling_indices.delete_dangling_index.0
      parameters:
        - $ref: '#/components/parameters/dangling_indices.delete_dangling_index::path.index_uuid'
        - $ref: '#/components/parameters/dangling_indices.delete_dangling_index::query.accept_data_loss'
        - $ref: '#/components/parameters/dangling_indices.delete_dangling_index::query.timeout'
        - $ref: '#/components/parameters/dangling_indices.delete_dangling_index::query.master_timeout'
        - $ref: '#/components/parameters/dangling_indices.delete_dangling_index::query.cluster_manager_timeout'
      responses:
        '200':
          $ref: '#/components/responses/dangling_indices.delete_dangling_index@200'
      x-operation-group: dangling_indices.delete_dangling_index
      x-version-added: '1.0'
    post:
      description: Imports the specified dangling index.
      externalDocs:
        url: https://opensearch.org/docs/latest/api-reference/index-apis/dangling-index/
      operationId: dangling_indices.import_dangling_index.0
      parameters:
        - $ref: '#/components/parameters/dangling_indices.import_dangling_index::path.index_uuid'
        - $ref: '#/components/parameters/dangling_indices.import_dangling_index::query.accept_data_loss'
        - $ref: '#/components/parameters/dangling_indices.import_dangling_index::query.timeout'
        - $ref: '#/components/parameters/dangling_indices.import_dangling_index::query.master_timeout'
        - $ref: '#/components/parameters/dangling_indices.import_dangling_index::query.cluster_manager_timeout'
      responses:
        '200':
          $ref: '#/components/responses/dangling_indices.import_dangling_index@200'
      x-operation-group: dangling_indices.import_dangling_index
      x-version-added: '1.0'
components:
  requestBodies: {}
  responses:
    dangling_indices.list_dangling_indices@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              dangling_indices:
                type: array
                items:
                  $ref: '../schemas/dangling_indices.list_dangling_indices.yaml#/components/schemas/DanglingIndex'
            required:
              - dangling_indices
    dangling_indices.delete_dangling_index@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/AcknowledgedResponseBase'
    dangling_indices.import_dangling_index@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/AcknowledgedResponseBase'
  parameters:
    dangling_indices.delete_dangling_index::path.index_uuid:
      in: path
      name: index_uuid
      description: The UUID of the dangling index
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Uuid'
      style: simple
    dangling_indices.delete_dangling_index::query.accept_data_loss:
      in: query
      name: accept_data_loss
      description: Must be set to true in order to delete the dangling index
      required: true
      schema:
        type: boolean
      style: form
    dangling_indices.delete_dangling_index::query.timeout:
      in: query
      name: timeout
      description: Explicit operation timeout
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      style: form
    dangling_indices.delete_dangling_index::query.master_timeout:
      in: query
      name: master_timeout
      description: Specify timeout for connection to master
      deprecated: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      style: form
      x-version-deprecated: 2.0.0
      x-deprecation-message: To promote inclusive language, use 'cluster_manager_timeout' instead.
    dangling_indices.delete_dangling_index::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: Operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: 2.0.0
    dangling_indices.import_dangling_index::path.index_uuid:
      in: path
      name: index_uuid
      description: The UUID of the dangling index
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Uuid'
      style: simple
    dangling_indices.import_dangling_index::query.accept_data_loss:
      in: query
      name: accept_data_loss
      description: Must be set to true in order to import the dangling index
      required: true
      schema:
        type: boolean
      style: form
    dangling_indices.import_dangling_index::query.timeout:
      in: query
      name: timeout
      description: Explicit operation timeout
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      style: form
    dangling_indices.import_dangling_index::query.master_timeout:
      in: query
      name: master_timeout
      description: Specify timeout for connection to master
      deprecated: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      style: form
      x-version-deprecated: 2.0.0
      x-deprecation-message: To promote inclusive language, use 'cluster_manager_timeout' instead.
    dangling_indices.import_dangling_index::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: Operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: 2.0.0
