openapi: 3.1.0
info:
  title: OpenSearch Flow Framework API
  description: OpenSearch Flow Framework API.
  version: 1.0.0
paths:
  /_plugins/_flow_framework/workflow:
    post:
      operationId: flow_framework.create_workflow.0
      x-operation-group: flow_framework.create_workflow
      description: Creates a workflow.
      externalDocs:
        url: https://opensearch.org/docs/latest/automating-configurations/api/create-workflow/
      parameters:
        - $ref: '#/components/parameters/flow_framework.create_workflow::query.provision'
      requestBody:
        $ref: '#/components/requestBodies/flow_framework.create_workflow'
      responses:
        '201':
          $ref: '#/components/responses/flow_framework.create_workflow'


#
#  /_plugins/_flow_framework/workflow/{workflow_id}:
#    delete: { }
#    put: { }
#    get: { }


components:
  parameters:
    flow_framework.create_workflow::query.provision:
      in: query
      name: provision
      schema:
        description: Whether to provision the workflow as part of the request
        type: boolean
        default: false
  requestBodies:
    flow_framework.create_workflow:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: The name of the workflow.
              description:
                type: string
                description: A description of the workflow.
              use_case:
                type: string
                description: A use case, which can be used with the Search Workflow API to find related workflows.
              version:
                type: object
                description: A key-value map with two fields, template, which identifies the template version, and compatibility, which identifies a list of minimum required OpenSearch versions.
              workflows:
                type: object
                description: A map of workflows. Presently, only the provision key is supported. The value for the workflow key is a key-value map that includes fields for user_params and lists of nodes and edges.
            required:
              - name
  responses:
    flow_framework.create_workflow:
      content:
        application/json:
          schema:
            type: object
            properties:
              workflow_id:
                type: string
                description: The ID of the workflow to be updated. Required for the PUT method.
            required:
              - workflow_id

# below is for update query field , will change to update workflow
#    flow_framework.create_workflow::query.update_fields:
#      in: query
#      name: update_fields
#      schema:
#        description: Whether to update only the fields included in the request body.
#        type: boolean
#        default: false
#
#
#    flow_framework.create_workflow::query.validation:
#      in: query
#      name: validation
#      schema:
#        description: Whether to validate the workflow. Valid values are all (validate the template) and none (do not validate the template). Default is all.
#        type: string
#        default: all


