openapi: 3.1.0
info:
  title: OpenSearch ISM API
  description: Use the index state management operations to programmatically work with policies and managed indexes.
  version: 1.0.0
paths:
  /_plugins/_ism/policies:
    get:
      operationId: ism.get_policies.0
      x-operation-group: ism.get_policies
      description: Gets the policies.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#get-policy
      responses:
        '200':
          $ref: '#/components/responses/ism.get_policies@200'
    put:
      operationId: ism.put_policies.0
      x-operation-group: ism.put_policies
      description: Gets the policies.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#create-policy
      requestBody:
        $ref: '#/components/requestBodies/ism.put_policies'
      parameters:
        - $ref: '#/components/parameters/ism.put_policies::query.if_primary_term'
        - $ref: '#/components/parameters/ism.put_policies::query.if_seq_no'
        - $ref: '#/components/parameters/ism.put_policies::query.policyID'
      responses:
        '200':
          $ref: '#/components/responses/ism.put_policies@200'
  /_plugins/_ism/policies/{policy_id}:
    get:
      operationId: ism.get_policy.0
      x-operation-group: ism.get_policy
      description: Gets a policy.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#put-policy
      parameters:
        - $ref: '#/components/parameters/ism.get_policy::path.policy_id'
      responses:
        '200':
          $ref: '#/components/responses/ism.get_policy@200'
    head:
      operationId: ism.exists_policy.0
      x-operation-group: ism.exists_policy
      description: Checks whether the policy exists.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#get-policy
      parameters:
        - $ref: '#/components/parameters/ism.exists_policy::path.policy_id'
      responses:
        '200':
          $ref: '#/components/responses/ism.exists_policy@200'
        '404':
          $ref: '#/components/responses/ism.exists_policy@404'
    put:
      operationId: ism.put_policy.0
      x-operation-group: ism.put_policy
      description: Creates or updates a policy.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#create-policy
      parameters:
        - $ref: '#/components/parameters/ism.put_policy::path.policy_id'
        - $ref: '#/components/parameters/ism.put_policy::query.if_primary_term'
        - $ref: '#/components/parameters/ism.put_policy::query.if_seq_no'
      requestBody:
        $ref: '#/components/requestBodies/ism.put_policy'
      responses:
        '201':
          $ref: '#/components/responses/ism.put_policy@201'
        '200':
          $ref: '#/components/responses/ism.put_policy@200'
    delete:
      operationId: ism.delete_policy.0
      x-operation-group: ism.delete_policy
      description: Deletes a policy.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#delete-policy
      parameters:
        - $ref: '#/components/parameters/ism.delete_policy::path.policy_id'
      responses:
        '200':
          $ref: '#/components/responses/ism.delete_policy@200'
  /_plugins/_ism/add:
    post:
      operationId: ism.add_policy.0
      x-operation-group: ism.add_policy
      description: Adds a policy to an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#add-policy
      parameters:
        - $ref: '#/components/parameters/ism.add_policy::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.add_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.add_policy@200'
  /_plugins/_ism/add/{index}:
    post:
      operationId: ism.add_policy.1
      x-operation-group: ism.add_policy
      description: Adds a policy to an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#add-policy
      parameters:
        - $ref: '#/components/parameters/ism.add_policy::path.index'
        - $ref: '#/components/parameters/ism.add_policy::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.add_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.add_policy@200'
  /_plugins/_ism/remove:
    post:
      operationId: ism.remove_policy.0
      x-operation-group: ism.remove_policy
      description: Removes a policy from an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#remove-policy
      parameters:
        - $ref: '#/components/parameters/ism.remove_policy::query.index'
      responses:
        '200':
          $ref: '#/components/responses/ism.remove_policy@200'
  /_plugins/_ism/remove/{index}:
    post:
      operationId: ism.remove_policy.1
      x-operation-group: ism.remove_policy
      description: Removes a policy from an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#remove-policy
      parameters:
        - $ref: '#/components/parameters/ism.remove_policy::path.index'
        - $ref: '#/components/parameters/ism.remove_policy::query.index'
      responses:
        '200':
          $ref: '#/components/responses/ism.remove_policy@200'
  /_plugins/_ism/change_policy:
    post:
      operationId: ism.change_policy.0
      x-operation-group: ism.change_policy
      description: Updates the managed index policy to a new policy.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#update-managed-index-policy
      parameters:
        - $ref: '#/components/parameters/ism.change_policy::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.change_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.change_policy@200'
  /_plugins/_ism/change_policy/{index}:
    post:
      operationId: ism.change_policy.1
      x-operation-group: ism.change_policy
      description: Updates the managed index policy to a new policy.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#update-managed-index-policy
      parameters:
        - $ref: '#/components/parameters/ism.change_policy::path.index'
        - $ref: '#/components/parameters/ism.change_policy::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.change_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.change_policy@200'
  /_plugins/_ism/explain:
    get:
      operationId: ism.explain_policy.0
      x-operation-group: ism.explain_policy
      description: Gets the currently applied policy on indices.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
      requestBody:
        $ref: '#/components/requestBodies/ism.explain_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.explain_policy@200'
    post:
      operationId: ism.explain_policy.1
      x-operation-group: ism.explain_policy
      description: Gets the currently applied policy on indices.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
      requestBody:
        $ref: '#/components/requestBodies/ism.explain_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.explain_policy@200'
  /_plugins/_ism/explain/{index}:
    get:
      operationId: ism.explain_policy.3
      x-operation-group: ism.explain_policy
      description: Gets the currently applied policy on indices.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
      parameters:
        - $ref: '#/components/parameters/ism.explain_policy::path.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.explain_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.explain_policy@200'
    post:
      operationId: ism.explain_policy.4
      x-operation-group: ism.explain_policy
      description: Gets the currently applied policy on indices.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#explain-index
      parameters:
        - $ref: '#/components/parameters/ism.explain_policy::path.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.explain_policy'
      responses:
        '200':
          $ref: '#/components/responses/ism.explain_policy@200'
  /_plugins/_ism/retry:
    post:
      operationId: ism.retry_index.0
      x-operation-group: ism.retry_index
      description: Retry the failed action for an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#retry-failed-index
      parameters:
        - $ref: '#/components/parameters/ism.retry_index::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.retry_index'
      responses:
        '200':
          $ref: '#/components/responses/ism.retry_index@200'
  /_plugins/_ism/retry/{index}:
    post:
      operationId: ism.retry_index.1
      x-operation-group: ism.retry_index
      description: Retry the failed action for an index.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/ism/api/#retry-failed-index
      parameters:
        - $ref: '#/components/parameters/ism.retry_index::path.index'
        - $ref: '#/components/parameters/ism.retry_index::query.index'
      requestBody:
        $ref: '#/components/requestBodies/ism.retry_index'
      responses:
        '200':
          $ref: '#/components/responses/ism.retry_index@200'
  /_plugins/_refresh_search_analyzers/{index}:
    post:
      operationId: ism.refresh_search_analyzers.0
      x-operation-group: ism.refresh_search_analyzers
      description: Refresh search analyzers in real time.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/refresh-analyzer/
      parameters:
        - $ref: '#/components/parameters/ism.refresh_search_analyzers::path.index'
      responses:
        '200':
          $ref: '#/components/responses/ism.refresh_search_analyzers@200'
components:
  requestBodies:
    ism.put_policies:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/PutPolicyRequest'
    ism.put_policy:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/PutPolicyRequest'
    ism.add_policy:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/AddPolicyRequest'
    ism.change_policy:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/ChangePolicyRequest'
    ism.retry_index:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/RetryIndexRequest'
    ism.explain_policy:
      content:
        application/json:
          schema: {}
  responses:
    ism.exists_policy@200:
      content:
        application/json:
          schema: {}
    ism.exists_policy@404:
      content:
        application/json:
          schema: {}
    ism.get_policies@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/GetPoliciesResponse'
    ism.get_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/GetPolicyResponse'
    ism.put_policy@201:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/PutPolicyResponse'
    ism.put_policies@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/PutPolicyResponse'
    ism.put_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/PutPolicyResponse'
    ism.delete_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/DeletePolicyResponse'
    ism.add_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/AddPolicyResponse'
    ism.remove_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/RemovePolicyResponse'
    ism.change_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/ChangePolicyResponse'
    ism.explain_policy@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/ExplainIndexResponse'
    ism.retry_index@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/RetryIndexResponse'
    ism.refresh_search_analyzers@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ism._common.yaml#/components/schemas/RefreshSearchAnalyzersResponse'
  parameters:
    ism.exists_policy::path.policy_id:
      name: policy_id
      in: path
      required: true
      schema:
        type: string
    ism.get_policy::path.policy_id:
      name: policy_id
      in: path
      required: true
      schema:
        type: string
    ism.put_policy::path.policy_id:
      name: policy_id
      in: path
      required: true
      schema:
        type: string
    ism.delete_policy::path.policy_id:
      name: policy_id
      in: path
      required: true
      schema:
        type: string
    ism.put_policy::query.if_seq_no:
      name: if_seq_no
      in: query
      description: Only perform the operation if the document has this sequence number.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/SequenceNumber'
      style: form
    ism.put_policy::query.if_primary_term:
      name: if_primary_term
      in: query
      description: Only perform the operation if the document has this primary term.
      schema:
        type: number
      style: form
    ism.add_policy::query.index:
      name: index
      in: query
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
    ism.add_policy::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.change_policy::query.index:
      name: index
      in: query
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
    ism.remove_policy::query.index:
      name: index
      in: query
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
    ism.remove_policy::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.change_policy::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.explain_policy::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.retry_index::query.index:
      name: index
      in: query
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
    ism.retry_index::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.refresh_search_analyzers::path.index:
      name: index
      in: path
      description: |-
        Comma-separated list of data streams, indices, and aliases.
        Supports wildcards (`*`).
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/IndexName'
      style: simple
    ism.put_policies::query.policyID:
      name: policyID
      in: query
      required: true
      schema:
        type: string
      style: form
    ism.put_policies::query.if_primary_term:
      name: if_primary_term
      in: query
      description: Only perform the operation if the document has this primary term.
      schema:
        type: number
      style: form
    ism.put_policies::query.if_seq_no:
      name: if_seq_no
      in: query
      description: Only perform the operation if the document has this sequence number.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/SequenceNumber'
      style: form
