openapi: 3.1.0
info:
  title: OpenSearch ML API
  description: OpenSearch ML API.
  version: 1.0.0
paths:
  /_plugins/_ltr/stats:
    get:
      operationId: ltr.stats.0
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/stats/{stat}:
    get:
      operationId: ltr.stats.1
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.stat'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/{node_id}/stats:
    get:
      operationId: ltr.stats.2
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.node_id'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/{node_id}/stats/{stat}:
    get:
      operationId: ltr.stats.3
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.node_id'
        - $ref: '#/components/parameters/ltr.stats::path.stat'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'


components:
  parameters:
    ltr.stats::query.timeout:
      name: timeout
      in: query
      description: The time in milliseconds to wait for a response.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
    ltr.stats::path.stat:
      name: stat
      in: path
      description: Comma-separated list of stats to retrieve; use `_all` or empty string to retrieve all stats.
      schema:
        type: array
        description: Comma-separated list of stats to retrieve; use `_all` or empty string to retrieve all stats.
        items:
          type: string
          enum:
            - cache
            - request_error_count
            - request_total_count
      required: true
    ltr.stats::path.node_id:
      name: node_id
      in: path
      description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return information from the node you're connecting to, leave empty to get information from all nodes.
      schema:
        type: array
        description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return information from the node you're connecting to, leave empty to get information from all nodes.
        items:
          type: string
      required: true

  responses:
    ltr.stats@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/Stats'
