openapi: 3.1.0
info:
  title: OpenSearch LTR API
  description: OpenSearch Learning to Rank API.
  version: 1.0.0
paths:
  /_ltr:
    get:
      operationId: ltr.list_stores.0
      x-operation-group: ltr.list_stores
      x-version-added: '1.0'
      description: Lists all available feature stores.
      responses:
        '200':
          $ref: '#/components/responses/ltr.list_stores@200'

    put:
      operationId: ltr.create_default_store.0
      x-operation-group: ltr.create_default_store
      x-version-added: '1.0'
      description: Creates the default feature store.
      responses:
        '200':
          $ref: '#/components/responses/ltr.create_default_store@200'

    delete:
      operationId: ltr.delete_default_store.0
      x-operation-group: ltr.delete_default_store
      x-version-added: '1.0'
      description: Deletes the default feature store.
      responses:
        '200':
          $ref: '#/components/responses/ltr.delete_default_store@200'

  /_ltr/{store}:
    get:
      operationId: ltr.get_store.0
      x-operation-group: ltr.get_store
      x-version-added: '1.0'
      description: Checks if a store exists.
      parameters:
        - $ref: '#/components/parameters/ltr.get_store::path.store'
      responses:
        '200':
          $ref: '#/components/responses/ltr.get_store@200'
        '404':
          $ref: '#/components/responses/ltr.get_store@404'

    put:
      operationId: ltr.create_store.0
      x-operation-group: ltr.create_store
      x-version-added: '1.0'
      description: Creates a new feature store with the specified name.
      parameters:
        - $ref: '#/components/parameters/ltr.create_store::path.store'
      responses:
        '200':
          $ref: '#/components/responses/ltr.create_store@200'

    delete:
      operationId: ltr.delete_store.0
      x-operation-group: ltr.delete_store
      x-version-added: '1.0'
      description: Deletes a feature store with the specified name.
      parameters:
        - $ref: '#/components/parameters/ltr.delete_store::path.store'
      responses:
        '200':
          $ref: '#/components/responses/ltr.delete_store@200'

  /_plugins/_ltr/stats:
    get:
      operationId: ltr.stats.0
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/stats/{stat}:
    get:
      operationId: ltr.stats.1
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.stat'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/{node_id}/stats:
    get:
      operationId: ltr.stats.2
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.node_id'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'

  /_plugins/_ltr/{node_id}/stats/{stat}:
    get:
      operationId: ltr.stats.3
      x-operation-group: ltr.stats
      x-version-added: '1.0'
      description: Provides information about the current status of the LTR plugin.
      parameters:
        - $ref: '#/components/parameters/ltr.stats::path.node_id'
        - $ref: '#/components/parameters/ltr.stats::path.stat'
        - $ref: '#/components/parameters/ltr.stats::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/ltr.stats@200'


components:
  parameters:
    ltr.get_store::path.store:
      name: store
      in: path
      description: The name of the feature store.
      schema:
        type: string
      required: true
    ltr.create_store::path.store:
      name: store
      in: path
      description: The name of the feature store.
      schema:
        type: string
      required: true
    ltr.delete_store::path.store:
      name: store
      in: path
      description: The name of the feature store.
      schema:
        type: string
      required: true
    ltr.stats::query.timeout:
      name: timeout
      in: query
      description: The time in milliseconds to wait for a response.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
    ltr.stats::path.stat:
      name: stat
      in: path
      description: Comma-separated list of stats to retrieve; use `_all` or empty string to retrieve all stats.
      schema:
        type: array
        description: Comma-separated list of stats to retrieve; use `_all` or empty string to retrieve all stats.
        items:
          type: string
          enum:
            - cache
            - request_error_count
            - request_total_count
      required: true
    ltr.stats::path.node_id:
      name: node_id
      in: path
      description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return information from the node you're connecting to, leave empty to get information from all nodes.
      schema:
        type: array
        description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return information from the node you're connecting to, leave empty to get information from all nodes.
        items:
          type: string
      required: true

  responses:
    ltr.list_stores@200:
      description: Returns a list of available feature stores.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/ListStoresResponse'
    
    ltr.delete_default_store@200:
      description: Successfully deleted the default feature store.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/AcknowledgedResponse'

    ltr.get_store@200:
      description: Returns information about the store existence.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/StoreExistsResponse'

    ltr.get_store@404:
      description: The store does not exist.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/StoreExistsResponse'

    ltr.create_store@200:
      description: Successfully created the feature store.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/AcknowledgedResponse'

    ltr.create_default_store@200:
      description: Successfully created the default feature store.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/AcknowledgedResponse'

    ltr.delete_store@200:
      description: Successfully deleted the feature store.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/AcknowledgedResponse'
            
    ltr.stats@200:
      description: Provides information about the current status of the LTR plugin.
      content:
        application/json:
          schema:
            $ref: '../schemas/ltr._common.yaml#/components/schemas/Stats'
