openapi: 3.1.0
info:
  title: OpenSearch ML API
  description: OpenSearch ML API.
  version: 1.0.0
paths:
  /_plugins/_ml/model_groups/_register:
    post:
      operationId: ml.register_model_group.0
      x-operation-group: ml.register_model_group
      description: Registers a model group.
      requestBody:
        $ref: '#/components/requestBodies/ml.register_model_group'
      responses:
        '200':
          $ref: '#/components/responses/ml.register_model_group@200'
  /_plugins/_ml/model_groups/{model_group_id}:
    get:
      operationId: ml.get_model_group.0
      x-operation-group: ml.get_model_group
      description: Retrieves a model group.
      parameters:
        - $ref: '#/components/parameters/ml.get_model_group::path.model_group_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.get_model_group@200'
    delete:
      operationId: ml.delete_model_group.0
      x-operation-group: ml.delete_model_group
      description: Deletes a model group.
      parameters:
        - $ref: '#/components/parameters/ml.delete_model_group::path.model_group_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.delete_model_group@200'
  /_plugins/_ml/models/_register:
    post:
      operationId: ml.register_model.0
      x-operation-group: ml.register_model
      description: Registers a model.
      requestBody:
        $ref: '#/components/requestBodies/ml.register_model'
      responses:
        '200':
          $ref: '#/components/responses/ml.register_model@200'
  /_plugins/_ml/models/{model_id}:
    delete:
      operationId: ml.delete_model.0
      x-operation-group: ml.delete_model
      description: Deletes a model.
      parameters:
        - $ref: '#/components/parameters/ml.delete_model::path.model_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.delete_model@200'
  /_plugins/_ml/models/{model_id}/_deploy:
    post:
      operationId: ml.deploy_model.0
      x-operation-group: ml.deploy_model
      description: Deploys a model.
      parameters:
        - $ref: '#/components/parameters/ml.deploy_model::path.model_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.deploy_model@200'
  /_plugins/_ml/models/{model_id}/_undeploy:
    post:
      operationId: ml.undeploy_model.0
      x-operation-group: ml.undeploy_model
      description: Undeploys a model.
      parameters:
        - $ref: '#/components/parameters/ml.undeploy_model::path.model_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.undeploy_model@200'
  /_plugins/_ml/tasks/{task_id}:
    get:
      operationId: ml.get_task.0
      x-operation-group: ml.get_task
      description: Retrieves a task.
      parameters:
        - $ref: '#/components/parameters/ml.get_task::path.task_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.get_task@200'
    delete:
      operationId: ml.delete_task.0
      x-operation-group: ml.delete_task
      description: Deletes a task.
      parameters:
        - $ref: '#/components/parameters/ml.delete_task::path.task_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.delete_task@200'
  /_plugins/_ml/models/_search:
    get:
      operationId: ml.search_models.0
      x-operation-group: ml.search_models
      description: Searches for models.
      requestBody:
        $ref: '#/components/requestBodies/ml.search_models'
      responses:
        '200':
          $ref: '#/components/responses/ml.search_models@200'
  /_plugins/_ml/connectors/_create:
    post:
      operationId: ml.create_connector.0
      x-operation-group: ml.create_connector
      description: Creates a standalone connector.
      requestBody:
        $ref: '#/components/requestBodies/ml.create_connector'
      responses:
        '200':
          $ref: '#/components/responses/ml.create_connector@200'
  /_plugins/_ml/connectors/{connector_id}:
    delete:
      operationId: ml.delete_connector.0
      x-operation-group: ml.delete_connector
      description: Deletes a standalone connector.
      parameters:
        - $ref: '#/components/parameters/ml.delete_connector::path.connector_id'
      responses:
        '200':
          $ref: '#/components/responses/ml.delete_connector@200'

components:
  requestBodies:
    ml.register_model_group:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: The model group name.
              description:
                type: string
                description: The model group description.
              access_mode:
                type: string
                description: The model group access mode.
                enum: [private, public, restricted]
              backend_roles:
                type: array
                items:
                  type: string
                description: The backend roles.
              add_all_backend_roles:
                type: boolean
                description: The add all backend roles.
            required:
              - name
    ml.register_model:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
                description: The model name.
              version:
                type: string
                description: The model version.
              model_format:
                type: string
                description: The portable format of the model file.
                enum: [ONNX, TORCH_SCRIPT]
              description:
                type: string
                description: The model description.
              model_group_id:
                type: string
                description: The ID of the model group to which to register the model.
            required:
              - model_format
              - name
              - version
    ml.search_models:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/SearchModelsQuery'
    ml.create_connector:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/CreateConnectorRequest'
  responses:
    ml.register_model_group@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/ModelGroupRegistration'
    ml.get_model_group@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/ModelGroup'
    ml.delete_model_group@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/WriteResponseBase'
    ml.register_model@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              task_id:
                type: string
            required:
              - status
              - task_id
    ml.deploy_model@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              task_id:
                type: string
              task_type:
                type: string
            required:
              - status
              - task_id
    ml.undeploy_model@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/UndeployModelResponse'
    ml.delete_model@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/WriteResponseBase'
    ml.delete_task@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/WriteResponseBase'
    ml.get_task@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/Task'
    ml.search_models@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/SearchModelsResponse'
    ml.create_connector@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              connector_id:
                type: string
    ml.delete_connector@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/ml._common.yaml#/components/schemas/MLConnectorDeleteResponse'
  parameters:
    ml.get_model_group::path.model_group_id:
      name: model_group_id
      in: path
      required: true
      schema:
        type: string
    ml.delete_model_group::path.model_group_id:
      name: model_group_id
      in: path
      required: true
      schema:
        type: string
    ml.delete_model::path.model_id:
      name: model_id
      in: path
      required: true
      schema:
        type: string
    ml.deploy_model::path.model_id:
      name: model_id
      in: path
      required: true
      schema:
        type: string
    ml.undeploy_model::path.model_id:
      name: model_id
      in: path
      required: true
      schema:
        type: string
    ml.delete_task::path.task_id:
      name: task_id
      in: path
      required: true
      schema:
        type: string
    ml.delete_connector::path.connector_id:
      name: connector_id
      in: path
      required: true
      schema:
        type: string
    ml.get_task::path.task_id:
      name: task_id
      in: path
      required: true
      schema:
        type: string