openapi: 3.1.0
info:
  title: OpenSearch Neural Search API
  description: OpenSearch Neural API.
  version: 1.0.0
paths:
  /_plugins/_neural/stats:
    get:
      operationId: neural.stats.0
      x-operation-group: neural.stats
      x-version-added: '3.0'
      description: Provides information about the current status of the neural-search plugin.
      parameters:
        - $ref: '#/components/parameters/neural.stats::query.flat_stat_paths'
        - $ref: '#/components/parameters/neural.stats::query.include_all_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_individual_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_info'
        - $ref: '#/components/parameters/neural.stats::query.include_metadata'
      responses:
        '200':
          $ref: '#/components/responses/neural.stats@200'
  /_plugins/_neural/stats/{stat}:
    get:
      operationId: neural.stats.1
      x-operation-group: neural.stats
      x-version-added: '3.0'
      description: Provides information about the current status of the neural-search plugin.
      parameters:
        - $ref: '#/components/parameters/neural.stats::path.stat'
        - $ref: '#/components/parameters/neural.stats::query.flat_stat_paths'
        - $ref: '#/components/parameters/neural.stats::query.include_all_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_individual_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_info'
        - $ref: '#/components/parameters/neural.stats::query.include_metadata'
      responses:
        '200':
          $ref: '#/components/responses/neural.stats@200'
  /_plugins/_neural/{node_id}/stats:
    get:
      operationId: neural.stats.2
      x-operation-group: neural.stats
      x-version-added: '3.0'
      description: Provides information about the current status of the neural-search plugin.
      parameters:
        - $ref: '#/components/parameters/neural.stats::path.node_id'
        - $ref: '#/components/parameters/neural.stats::query.flat_stat_paths'
        - $ref: '#/components/parameters/neural.stats::query.include_all_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_individual_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_info'
        - $ref: '#/components/parameters/neural.stats::query.include_metadata'
      responses:
        '200':
          $ref: '#/components/responses/neural.stats@200'
  /_plugins/_neural/{node_id}/stats/{stat}:
    get:
      operationId: neural.stats.3
      x-operation-group: neural.stats
      x-version-added: '3.0'
      description: Provides information about the current status of the neural-search plugin.
      parameters:
        - $ref: '#/components/parameters/neural.stats::path.node_id'
        - $ref: '#/components/parameters/neural.stats::path.stat'
        - $ref: '#/components/parameters/neural.stats::query.flat_stat_paths'
        - $ref: '#/components/parameters/neural.stats::query.include_all_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_individual_nodes'
        - $ref: '#/components/parameters/neural.stats::query.include_info'
        - $ref: '#/components/parameters/neural.stats::query.include_metadata'
      responses:
        '200':
          $ref: '#/components/responses/neural.stats@200'
components:
  responses:
    neural.stats@200:
      description: Successful response containing neural stats
      content:
        application/json:
          schema:
            $ref: '../schemas/neural._common.yaml#/components/schemas/NeuralStats'
  parameters:
    neural.stats::path.node_id:
      name: node_id
      in: path
      description: A comma-separated list of node IDs or names to limit the returned information; leave empty to get information from all nodes.
      schema:
        type: string
      required: true
    neural.stats::path.stat:
      name: stat
      in: path
      description: A comma-separated list of stats to retrieve; use empty string to retrieve all stats.
      schema:
        type: string
        enum:
          - cluster_version
          - comb_arithmetic_executions
          - comb_arithmetic_processors
          - comb_geometric_executions
          - comb_geometric_processors
          - comb_harmonic_executions
          - comb_harmonic_processors
          - comb_rrf_executions
          - comb_rrf_processors
          - hybrid_query_requests
          - hybrid_query_with_filter_requests
          - hybrid_query_with_inner_hits_requests
          - hybrid_query_with_pagination_requests
          - neural_query_against_knn_requests
          - neural_query_against_semantic_dense_requests
          - neural_query_against_semantic_sparse_requests
          - neural_query_enricher_executions
          - neural_query_enricher_processors
          - neural_query_requests
          - neural_sparse_query_requests
          - neural_sparse_two_phase_executions
          - neural_sparse_two_phase_processors
          - norm_l2_executions
          - norm_l2_processors
          - norm_minmax_executions
          - norm_minmax_processors
          - norm_zscore_executions
          - norm_zscore_processors
          - normalization_processor_executions
          - normalization_processors
          - rank_based_normalization_processor_executions
          - rank_based_normalization_processors
          - rerank_by_field_executions
          - rerank_by_field_processors
          - rerank_ml_executions
          - rerank_ml_processors
          - semantic_field_chunking_executions
          - semantic_field_executions
          - semantic_highlighting_request_count
          - skip_existing_executions
          - skip_existing_processors
          - sparse_encoding_executions
          - sparse_encoding_processors
          - text_chunking_delimiter_executions
          - text_chunking_delimiter_processors
          - text_chunking_executions
          - text_chunking_fixed_char_length_executions
          - text_chunking_fixed_char_length_processors
          - text_chunking_fixed_token_length_executions
          - text_chunking_fixed_token_length_processors
          - text_chunking_processors
          - text_embedding_executions
          - text_embedding_processors_in_pipelines
          - text_image_embedding_executions
          - text_image_embedding_processors
      required: true
    neural.stats::query.flat_stat_paths:
      in: query
      name: flat_stat_paths
      description: |- 
        Whether to return stats in the flat form, which can improve readability, especially for heavily nested stats.
        For example, the flat form of `"processors": { "ingest": { "text_embedding_executions": 20181212 } }` is 
        `"processors.ingest.text_embedding_executions": "20181212"`.
      schema:
        type: boolean
        default: false
      style: form
    neural.stats::query.include_all_nodes:
      in: query
      name: include_all_nodes
      description: |- 
        When `true` includes aggregated statistics across all nodes in the `all_nodes` category.
        When `false`, excludes the `all_nodes` category from the response.
      schema:
        type: boolean
        default: true
      style: form
      x-version-added: '3.1'
    neural.stats::query.include_individual_nodes:
      in: query
      name: include_individual_nodes
      description: |- 
        When `true` includes statistics for individual nodes in the `nodes` category.
        When `false`, excludes the `nodes` category from the response.
      schema:
        type: boolean
        default: true
      style: form
      x-version-added: '3.1'
    neural.stats::query.include_info:
      in: query
      name: include_info
      description: |- 
        When `true` includes cluster-wide information in the `info` category.
        When `false`, excludes the `info` category from the response.
      schema:
        type: boolean
        default: true
      style: form
      x-version-added: '3.1'
    neural.stats::query.include_metadata:
      in: query
      name: include_metadata
      description: |- 
        Whether to return stat metadata instead of the raw stat value, includes additional information about the stat.
        These can include things like type hints, time since last stats being recorded, or recent rolling interval values
      schema:
        type: boolean
        default: false
      style: form
