openapi: 3.1.0
info:
  title: OpenSearch Notifications API
  description: OpenSearch Notifications API
  version: 1.0.0
paths:
  /_plugins/_notifications/configs:
    delete:
      operationId: notifications.delete_config.0
      x-operation-group: notifications.delete_config
      x-version-added: '2.2'
      description: Delete channel configuration.
      parameters:
        - $ref: '#/components/parameters/notifications.delete_config::query.config_id'
        - $ref: '#/components/parameters/notifications.delete_config::query.config_id_list'
      responses:
        '200':
          $ref: '#/components/responses/notifications.delete_config@200'
    get:
      operationId: notifications.get_config.0
      x-operation-group: notifications.get_config
      x-version-added: '2.0'
      description: Get channel configuration.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#get-channel-configuration
      parameters:
        - $ref: '#/components/parameters/notifications.get_config::query.last_updated_time_ms'
        - $ref: '#/components/parameters/notifications.get_config::query.created_time_ms'
        - $ref: '#/components/parameters/notifications.get_config::query.config_type'
        - $ref: '#/components/parameters/notifications.get_config::query.email.email_account_id'
        - $ref: '#/components/parameters/notifications.get_config::query.email.email_group_id_list'
        - $ref: '#/components/parameters/notifications.get_config::query.smtp_account.method'
        - $ref: '#/components/parameters/notifications.get_config::query.ses_account.region'
        - $ref: '#/components/parameters/notifications.get_config::query.name'
        - $ref: '#/components/parameters/notifications.get_config::query.name.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.description'
        - $ref: '#/components/parameters/notifications.get_config::query.description.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.slack.url'
        - $ref: '#/components/parameters/notifications.get_config::query.slack.url.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.chime.url'
        - $ref: '#/components/parameters/notifications.get_config::query.chime.url.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.microsoft_teams.url'
        - $ref: '#/components/parameters/notifications.get_config::query.microsoft_teams.url.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.webhook.url'
        - $ref: '#/components/parameters/notifications.get_config::query.webhook.url.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.smtp_account.host'
        - $ref: '#/components/parameters/notifications.get_config::query.smtp_account.host.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.smtp_account.from_address'
        - $ref: '#/components/parameters/notifications.get_config::query.smtp_account.from_address.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.sns.topic_arn'
        - $ref: '#/components/parameters/notifications.get_config::query.sns.topic_arn.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.sns.role_arn'
        - $ref: '#/components/parameters/notifications.get_config::query.sns.role_arn.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.ses_account.role_arn'
        - $ref: '#/components/parameters/notifications.get_config::query.ses_account.role_arn.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.ses_account.from_address'
        - $ref: '#/components/parameters/notifications.get_config::query.ses_account.from_address.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.is_enabled'
        - $ref: '#/components/parameters/notifications.get_config::query.email.recipient_list.recipient'
        - $ref: '#/components/parameters/notifications.get_config::query.email.recipient_list.recipient.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.email_group.recipient_list.recipient'
        - $ref: '#/components/parameters/notifications.get_config::query.email_group.recipient_list.recipient.keyword'
        - $ref: '#/components/parameters/notifications.get_config::query.query'
        - $ref: '#/components/parameters/notifications.get_config::query.text_query'
      requestBody:
        $ref: '#/components/requestBodies/notifications.get_config'
      responses:
        '200':
          $ref: '#/components/responses/notifications.get_config@200'
    post:
      operationId: notifications.create_config.0
      x-operation-group: notifications.create_config
      x-version-added: '2.0'
      description: Create channel configuration.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#create-channel-configuration
      requestBody:
        $ref: '#/components/requestBodies/notifications.create_config'
      responses:
        '200':
          $ref: '#/components/responses/notifications.create_config@200'
  /_plugins/_notifications/configs/{config_id}:
    delete:
      operationId: notifications.delete_config.1
      x-operation-group: notifications.delete_config
      x-version-added: '2.0'
      description: Delete channel configuration.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#delete-channel-configuration
      parameters:
        - $ref: '#/components/parameters/notifications.delete_config::path.config_id'
      responses:
        '200':
          $ref: '#/components/responses/notifications.delete_config@200'
    get:
      operationId: notifications.get_config.1
      x-operation-group: notifications.get_config
      x-version-added: '2.0'
      description: Get channel configuration.
      parameters:
        - $ref: '#/components/parameters/notifications.get_config::path.config_id'
      responses:
        '200':
          $ref: '#/components/responses/notifications.get_config@200'
    put:
      operationId: notifications.update_config.0
      x-operation-group: notifications.update_config
      x-version-added: '2.0'
      description: Update channel configuration.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#update-channel-configuration
      parameters:
        - $ref: '#/components/parameters/notifications.update_config::path.config_id'
      requestBody:
        $ref: '#/components/requestBodies/notifications.update_config'
      responses:
        '200':
          $ref: '#/components/responses/notifications.update_config@200'
  /_plugins/_notifications/feature/test/{config_id}:
    get:
      operationId: notifications.send_test.0
      x-operation-group: notifications.send_test
      deprecated: true
      x-deprecation-message: Use the POST method instead.
      x-version-added: '2.0'
      x-version-deprecated: '2.3'
      description: Send a test notification.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#send-test-notification
      parameters:
        - $ref: '#/components/parameters/notifications.send_test::path.config_id'
      responses:
        '200':
          $ref: '#/components/responses/notifications.send_test@200'
    post:
      operationId: notifications.send_test.1
      x-operation-group: notifications.send_test
      x-version-added: '2.0'
      description: Send a test notification.
      parameters:
        - $ref: '#/components/parameters/notifications.send_test::path.config_id'
      responses:
        '200':
          $ref: '#/components/responses/notifications.send_test@200'
  /_plugins/_notifications/features:
    get:
      operationId: notifications.list_features.0
      x-operation-group: notifications.list_features
      x-version-added: '2.0'
      description: List supported channel configurations.
      externalDocs:
        url: https://opensearch.org/docs/latest/observing-your-data/notifications/api/#list-supported-channel-configurations
      responses:
        '200':
          $ref: '#/components/responses/notifications.list_features@200'
components:
  requestBodies:
    notifications.create_config:
      content:
        application/json:
          schema:
            $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationsConfig'
      required: true
    notifications.get_config:
      content:
        application/json:
          schema:
            $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationsConfigs_GetRequestContent'
    notifications.update_config:
      content:
        application/json:
          schema:
            $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationsConfig'
      required: true
  responses:
    notifications.create_config@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              config_id:
                type: string
    notifications.delete_config@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              delete_response_list:
                $ref: '../schemas/notifications._common.yaml#/components/schemas/DeleteResponseList'
    notifications.get_config@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              start_index:
                type: integer
                format: int64
              total_hits:
                type: integer
                format: int64
              total_hit_relation:
                $ref: '../schemas/notifications._common.yaml#/components/schemas/TotalHitRelation'
              config_list:
                type: array
                items:
                  $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationsConfigsOutputItem'
    notifications.list_features@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              allowed_config_type_list:
                type: array
                items:
                  $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationConfigType'
              plugin_features:
                $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationsPluginFeaturesMap'
    notifications.send_test@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              event_source:
                $ref: '../schemas/notifications._common.yaml#/components/schemas/EventSource'
              status_list:
                type: array
                items:
                  $ref: '../schemas/notifications._common.yaml#/components/schemas/EventStatus'
    notifications.update_config@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              config_id:
                type: string
  parameters:
    notifications.delete_config::path.config_id:
      name: config_id
      in: path
      schema:
        type: string
      required: true
    notifications.delete_config::query.config_id:
      name: config_id
      in: query
      description: A channel ID.
      schema:
        type: string
        description: A channel ID.
    notifications.delete_config::query.config_id_list:
      name: config_id_list
      in: query
      description: A comma-separated list of channel IDs.
      schema:
        type: string
        description: A comma-separated list of channel IDs.
    notifications.get_config::path.config_id:
      name: config_id
      in: path
      schema:
        type: string
      required: true
    notifications.get_config::query.chime.url:
      name: chime.url
      in: query
      schema:
        type: string
    notifications.get_config::query.chime.url.keyword:
      name: chime.url.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.config_type:
      name: config_type
      in: query
      description: Type of notification configuration.
      schema:
        $ref: '../schemas/notifications._common.yaml#/components/schemas/NotificationConfigType'
    notifications.get_config::query.created_time_ms:
      name: created_time_ms
      in: query
      schema:
        type: integer
        format: int64
    notifications.get_config::query.description:
      name: description
      in: query
      schema:
        type: string
    notifications.get_config::query.description.keyword:
      name: description.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.email.email_account_id:
      name: email.email_account_id
      in: query
      schema:
        type: string
    notifications.get_config::query.email.email_group_id_list:
      name: email.email_group_id_list
      in: query
      schema:
        type: string
    notifications.get_config::query.email.recipient_list.recipient:
      name: email.recipient_list.recipient
      in: query
      schema:
        type: string
    notifications.get_config::query.email.recipient_list.recipient.keyword:
      name: email.recipient_list.recipient.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.email_group.recipient_list.recipient:
      name: email_group.recipient_list.recipient
      in: query
      schema:
        type: string
    notifications.get_config::query.email_group.recipient_list.recipient.keyword:
      name: email_group.recipient_list.recipient.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.is_enabled:
      name: is_enabled
      in: query
      schema:
        type: boolean
    notifications.get_config::query.last_updated_time_ms:
      name: last_updated_time_ms
      in: query
      schema:
        type: integer
        format: int64
    notifications.get_config::query.microsoft_teams.url:
      name: microsoft_teams.url
      in: query
      schema:
        type: string
    notifications.get_config::query.microsoft_teams.url.keyword:
      name: microsoft_teams.url.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.name:
      name: name
      in: query
      schema:
        type: string
    notifications.get_config::query.name.keyword:
      name: name.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.query:
      name: query
      in: query
      schema:
        type: string
    notifications.get_config::query.ses_account.from_address:
      name: ses_account.from_address
      in: query
      schema:
        type: string
    notifications.get_config::query.ses_account.from_address.keyword:
      name: ses_account.from_address.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.ses_account.region:
      name: ses_account.region
      in: query
      schema:
        type: string
    notifications.get_config::query.ses_account.role_arn:
      name: ses_account.role_arn
      in: query
      schema:
        type: string
    notifications.get_config::query.ses_account.role_arn.keyword:
      name: ses_account.role_arn.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.slack.url:
      name: slack.url
      in: query
      schema:
        type: string
    notifications.get_config::query.slack.url.keyword:
      name: slack.url.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.smtp_account.from_address:
      name: smtp_account.from_address
      in: query
      schema:
        type: string
    notifications.get_config::query.smtp_account.from_address.keyword:
      name: smtp_account.from_address.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.smtp_account.host:
      name: smtp_account.host
      in: query
      schema:
        type: string
    notifications.get_config::query.smtp_account.host.keyword:
      name: smtp_account.host.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.smtp_account.method:
      name: smtp_account.method
      in: query
      schema:
        type: string
    notifications.get_config::query.sns.role_arn:
      name: sns.role_arn
      in: query
      schema:
        type: string
    notifications.get_config::query.sns.role_arn.keyword:
      name: sns.role_arn.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.sns.topic_arn:
      name: sns.topic_arn
      in: query
      schema:
        type: string
    notifications.get_config::query.sns.topic_arn.keyword:
      name: sns.topic_arn.keyword
      in: query
      schema:
        type: string
    notifications.get_config::query.text_query:
      name: text_query
      in: query
      schema:
        type: string
    notifications.get_config::query.webhook.url:
      name: webhook.url
      in: query
      schema:
        type: string
    notifications.get_config::query.webhook.url.keyword:
      name: webhook.url.keyword
      in: query
      schema:
        type: string
    notifications.send_test::path.config_id:
      name: config_id
      in: path
      schema:
        type: string
      required: true
    notifications.update_config::path.config_id:
      name: config_id
      in: path
      schema:
        type: string
      required: true
