openapi: 3.1.0
info:
  title: OpenSearch Remote_store API
  description: OpenSearch Remote_store API
  version: 1.0.0
paths:
  /_remotestore/_restore:
    post:
      operationId: remote_store.restore.0
      x-operation-group: remote_store.restore
      x-version-added: '1.0'
      description: Restores from remote store.
      externalDocs:
        url: https://opensearch.org/docs/latest/opensearch/remote/#restoring-from-a-backup
      parameters:
        - $ref: '#/components/parameters/remote_store.restore::query.cluster_manager_timeout'
        - $ref: '#/components/parameters/remote_store.restore::query.wait_for_completion'
      requestBody:
        $ref: '#/components/requestBodies/remote_store.restore'
      responses:
        '200':
          $ref: '#/components/responses/remote_store.restore@200'
components:
  requestBodies:
    remote_store.restore:
      content:
        application/json:
          schema:
            type: object
            description: Comma-separated list of index IDs
            properties:
              indices:
                type: array
                items:
                  type: string
            required:
              - indices
          examples:
            RemoteStoreRestore_example1:
              summary: Examples for Post Remote Storage Restore Operation.
              description: ''
              value:
                indices:
                  - books
      required: true
  responses:
    remote_store.restore@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              accepted:
                type: boolean
              remote_store:
                $ref: '../schemas/remote_store._common.yaml#/components/schemas/RemoteStoreRestoreInfo'
          examples:
            RemoteStoreRestore_example1:
              summary: Examples for Post Remote Storage Restore Operation.
              description: ''
              value:
                remote_store:
                  indices:
                    - books
                  shards:
                    total: 1
                    failed: 0
                    successful: 1
  parameters:
    remote_store.restore::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: Operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: '2.0'
    remote_store.restore::query.wait_for_completion:
      name: wait_for_completion
      in: query
      description: Should this request wait until the operation has completed before returning.
      schema:
        type: boolean
        default: false
        description: Should this request wait until the operation has completed before returning.
