openapi: 3.1.0
info:
  title: OpenSearch Search Relevance API
  description: OpenSearch Search Relevance API.
  version: 1.0.0
paths:
  _plugins/search_relevance/query_sets:
    get:
      operationId: search_relevance.get_query_sets.0
      x-operation-group: search_relevance.get_query_sets
      x-version-added: '3.1'
      description: Lists the current query sets available.
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_query_sets@200'
    post:
      operationId: search_relevance.post_query_sets.0
      x-operation-group: search_relevance.post_query_sets
      x-version-added: '3.1'
      description: Creates a new query set by sampling queries from the user behavior data. 
      requestBody:
        $ref: '#/components/requestBodies/search_relevance.post_query_sets'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.post_query_sets@200'
    put:
      operationId: search_relevance.put_query_sets.0
      x-operation-group: search_relevance.put_query_sets
      x-version-added: '3.1'
      description: Creates a new query set by uploading manually.
      requestBody:
        $ref: '#/components/requestBodies/search_relevance.put_query_sets'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.put_query_sets@200'
  _plugins/search_relevance/query_sets/{query_set_id}:
    get:
      operationId: search_relevance.get_query_sets.1
      x-operation-group: search_relevance.get_query_sets
      x-version-added: '3.1'
      description: Lists the current query sets available.
      parameters:
        - $ref: '#/components/parameters/search_relevance.get_query_sets::path.query_set_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_query_sets@200'
    delete:
      operationId: search_relevance.delete_query_sets.0
      x-operation-group: search_relevance.delete_query_sets
      x-version-added: '3.1'
      description: Deletes a query set.
      parameters:
        - $ref: '#/components/parameters/search_relevance.delete_query_sets::path.query_set_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.delete_query_sets@200'
  _plugins/search_relevance/judgments:
    get:
      operationId: search_relevance.get_judgments.0
      x-operation-group: search_relevance.get_judgments
      x-version-added: '3.1'
      description: Gets judgments.
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_judgments@200'
    put:
      operationId: search_relevance.put_judgments.0
      x-operation-group: search_relevance.put_judgments
      x-version-added: '3.1'
      description: Creates a judgment.
      requestBody:
        description: The request body of the judgment to be created.
        $ref: '#/components/requestBodies/search_relevance.put_judgments' 
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.put_judgments@200'
  _plugins/search_relevance/judgments/{judgment_id}:
    get:
      operationId: search_relevance.get_judgments.1
      x-operation-group: search_relevance.get_judgments
      x-version-added: '3.1'
      description: Gets judgments.
      parameters:
        - $ref: '#/components/parameters/search_relevance.get_judgments::path.judgment_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_judgments@200'
    delete:
      operationId: search_relevance.delete_judgments.0
      x-operation-group: search_relevance.delete_judgments
      x-version-added: '3.1'
      description: Deletes a specified judgment.
      parameters:
        - $ref: '#/components/parameters/search_relevance.delete_judgments::path.judgment_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.delete_judgments@200'
  _plugins/search_relevance/search_configurations:
    get:
      operationId: search_relevance.get_search_configurations.0
      x-operation-group: search_relevance.get_search_configurations
      x-version-added: '3.1'
      description: Gets the search configurations.
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_search_configurations@200'
    put:
      operationId: search_relevance.put_search_configurations.0
      x-operation-group: search_relevance.put_search_configurations
      x-version-added: '3.1'
      description: Creates a search configuration.
      requestBody:
        $ref: '#/components/requestBodies/search_relevance.put_search_configurations' 
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.put_search_configurations@200'
  _plugins/search_relevance/search_configurations/{search_configuration_id}:
    get:
      operationId: search_relevance.get_search_configurations.1
      x-operation-group: search_relevance.get_search_configurations
      x-version-added: '3.1'
      description: Gets the search configurations.
      parameters:
        - $ref: '#/components/parameters/search_relevance.get_search_configurations::path.search_configuration_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_search_configurations@200'
          #content:
          #  application/json:
          #    schema:
          #      $ref: '../schemas/search_relevance._common.yaml#/components/schemas/SearchConfiguration'
    delete:
      operationId: search_relevance.delete_search_configurations.0
      x-operation-group: search_relevance.delete_search_configurations
      x-version-added: '3.1'
      description: Deletes a specified search configuration.
      parameters:
        - $ref: '#/components/parameters/search_relevance.delete_search_configurations::path.search_configuration_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.delete_search_configurations@200'
  _plugins/search_relevance/experiments:
    get:
      operationId: search_relevance.get_experiments.0
      x-operation-group: search_relevance.get_experiments
      x-version-added: '3.1'
      description: Gets experiments.
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_experiments@200'
    put:
      operationId: search_relevance.put_experiments.0
      x-operation-group: search_relevance.put_experiments
      x-version-added: '3.1'
      description: Creates an experiment.
      requestBody:
        $ref: '#/components/requestBodies/search_relevance.put_experiments'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.put_experiments@200'
  _plugins/search_relevance/experiments/{experiment_id}:
    get:
      operationId: search_relevance.get_experiments.1
      x-operation-group: search_relevance.get_experiments
      x-version-added: '3.1'
      description: Gets experiments.
      parameters:
        - $ref: '#/components/parameters/search_relevance.get_experiments::path.experiment_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.get_experiments@200'
          #content:
          #  application/json:
          #    schema:
          #      type: object
                #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/Experiment'
    delete:
      operationId: search_relevance.delete_experiments.0
      x-operation-group: search_relevance.delete_experiments
      x-version-added: '3.1'
      description: Deletes a specified experiment.
      parameters:
        - $ref: '#/components/parameters/search_relevance.delete_experiments::path.experiment_id'
      responses:
        '200':
          $ref: '#/components/responses/search_relevance.delete_experiments@200'
          
components:
  parameters:
    search_relevance.get_query_sets::path.query_set_id: 
      name: query_set_id
      in: path
      description: The query set id
      schema:
        type: string
    search_relevance.delete_query_sets::path.query_set_id: 
      name: query_set_id
      in: path
      description: The query set id
      schema:
        type: string
    search_relevance.get_judgments::path.judgment_id:
      name: judgment_id
      in: path
      description: The judgment id
      schema:
        type:
          string
    search_relevance.delete_judgments::path.judgment_id:
      name: judgment_id
      in: path
      description: The judgment id
      schema:
        type:
          string
    search_relevance.get_search_configurations::path.search_configuration_id:
      name: search_configuration_id
      in: path
      description: The search configuration id
      schema:
        type:
          string
    search_relevance.delete_search_configurations::path.search_configuration_id:
      name: search_configuration_id
      in: path
      description: The search configuration id
      schema:
        type:
          string
    search_relevance.get_experiments::path.experiment_id:
      name: experiment_id
      in: path
      description: The experiment id
      schema:
        type:
          string
    search_relevance.delete_experiments::path.experiment_id:
      name: experiment_id
      in: path
      description: The experiment id
      schema:
        type:
          string
  requestBodies:
    search_relevance.post_query_sets:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetSize:
                type: integer
    search_relevance.put_query_sets:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              sampling:
                type: string
              querySetQueries:
                type: array
                items:
                  type: object
    search_relevance.put_judgments:
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  type:
                    type: string
                  querySetId:
                    type: string
                  clickModel:
                    type: string
                  maxRank:
                    type: integer
              - type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
                  type:
                    type: string
                  querySetId:
                    type: string
                  modelId:
                    type: string
                  size:
                    type: integer
                  searchConfigurationList:
                    type: array
                    items:
                      type: string
            #- $ref: '#/components/schemas/put_judgment_ubi'
            #- $ref: '#/components/schemas/put_judgment_llm'
    search_relevance.put_search_configurations:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              query:
                type: string
              index:
                type: string
    search_relevance.put_experiments:
      content:
        application/json:
          schema:
            type: object
            properties:
              querySetId:
                type: string
              searchConfigurationList:
                type: array
                items:
                  type: string
              size:
                type: integer
              type:
                type: string
  responses:
    search_relevance.get_query_sets@200:
      content:
        application/json:
          schema:
            #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            oneOf:
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/QuerySet'
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            #items: 
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/QuerySet'
    search_relevance.post_query_sets@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              query_set_id: 
                type: string
              query_set_result:
                type: string
    search_relevance.put_query_sets@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              query_set_id: 
                type: string
              query_set_result:
                type: string
    search_relevance.delete_query_sets@200:
      content:
        application/json:
          schema:
            type: object
            #properties:
            #  id: 
            #    type: string
            #  result:
            #    type: string
    search_relevance.get_judgments@200:
      content:
        application/json:
          schema:
            #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            oneOf:
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Judgment'
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Judgment'
    search_relevance.put_judgments@200:
      content:
        application/json:
          schema:
            type: 
              object
            properties:
              judgment_id:
                type: string
    search_relevance.delete_judgments@200:
      content:
        application/json:
          schema:
            type: object
            #properties:
            #  id: 
            #    type: string
            #  result:
            #    type: string
    search_relevance.get_search_configurations@200:
      content:
        application/json:
          schema:
            #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            oneOf:
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/SearchConfiguration'
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            #type: array
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/SearchConfiguration'
    search_relevance.put_search_configurations@200:
      content:
        application/json:
          schema:
            type: object
            properties:
              search_configuration_id:
                type: string
              search_configuration_result:
                type: string
    search_relevance.delete_search_configurations@200:
      content:
        application/json:
          schema:
            type: object
            #properties:
            #  id: 
            #    type: string
            #  result:
            #    type: string
    search_relevance.get_experiments@200:
      content:
        application/json:
          schema:
            #$ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            oneOf:
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Experiment'
              - $ref: '../schemas/search_relevance._common.yaml#/components/schemas/GenericObject'
            #type: array
            #items:
            #  $ref: '../schemas/search_relevance._common.yaml#/components/schemas/Experiment'
    search_relevance.put_experiments@200:
      content:
        application/json:
          schema:
            type: object
            #properties:
            #  experiments_id:
            #    type: string
            #  experiments_result:
            #    type: string
    search_relevance.delete_experiments@200:
      content:
          application/json:
            schema:
              type: object
              #properties:
              #  id: 
              #    type: string
              #  result:
              #    type: string