openapi: 3.1.0
info:
  title: OpenSearch Search_pipeline API
  description: OpenSearch Search_pipeline API
  version: 1.0.0
paths:
  /_search/pipeline:
    get:
      operationId: search_pipeline.get.0
      x-operation-group: search_pipeline.get
      x-version-added: '2.9'
      description: Retrieves information about a specified search pipeline.
      parameters:
        - $ref: '#/components/parameters/search_pipeline.get::query.cluster_manager_timeout'
      responses:
        '200':
          $ref: '#/components/responses/search_pipeline.get@200'
  /_search/pipeline/{id}:
    get:
      operationId: search_pipeline.get.1
      x-operation-group: search_pipeline.get
      x-version-added: '2.9'
      description: Retrieves information about a specified search pipeline.
      parameters:
        - $ref: '#/components/parameters/search_pipeline.get::path.id'
        - $ref: '#/components/parameters/search_pipeline.get::query.cluster_manager_timeout'
      responses:
        '200':
          $ref: '#/components/responses/search_pipeline.get@200'
    put:
      operationId: search_pipeline.put.0
      x-operation-group: search_pipeline.put
      x-version-added: '2.9'
      description: Creates or replaces the specified search pipeline.
      externalDocs:
        url: https://opensearch.org/docs/latest/search-plugins/search-pipelines/creating-search-pipeline/
      parameters:
        - $ref: '#/components/parameters/search_pipeline.put::path.id'
        - $ref: '#/components/parameters/search_pipeline.put::query.cluster_manager_timeout'
        - $ref: '#/components/parameters/search_pipeline.put::query.timeout'
      requestBody:
        $ref: '#/components/requestBodies/search_pipeline.put'
      responses:
        '200':
          $ref: '#/components/responses/search_pipeline.put@200'
    delete:
      operationId: search_pipeline.delete.0
      x-operation-group: search_pipeline.delete
      x-version-added: '2.9'
      description: Deletes the specified search pipeline.
      parameters:
        - $ref: '#/components/parameters/search_pipeline.delete::path.id'
        - $ref: '#/components/parameters/search_pipeline.delete::query.cluster_manager_timeout'
        - $ref: '#/components/parameters/search_pipeline.delete::query.timeout'
      responses:
        '200':
          $ref: '#/components/responses/search_pipeline.delete@200'
components:
  requestBodies:
    search_pipeline.put:
      content:
        application/json:
          schema:
            $ref: '../schemas/search_pipeline._common.yaml#/components/schemas/SearchPipelineStructure'
      required: true
  responses:
    search_pipeline.put@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
    search_pipeline.delete@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
    search_pipeline.get@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/search_pipeline._common.yaml#/components/schemas/SearchPipelineMap'
  parameters:
    search_pipeline.put::path.id:
      name: id
      in: path
      description: Pipeline ID.
      schema:
        type: string
      required: true
    search_pipeline.delete::path.id:
      name: id
      in: path
      description: Pipeline ID.
      schema:
        type: string
      required: true
    search_pipeline.get::path.id:
      name: id
      in: path
      description: Comma-separated list of search pipeline ids. Wildcards supported.
      schema:
        type: string
    search_pipeline.get::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: '2.0'
    search_pipeline.put::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: '2.0'
    search_pipeline.delete::query.cluster_manager_timeout:
      name: cluster_manager_timeout
      in: query
      description: Operation timeout for connection to cluster-manager node.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
      x-version-added: '2.0'
    search_pipeline.put::query.timeout:
      name: timeout
      in: query
      description: Operation timeout.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
    search_pipeline.delete::query.timeout:
      name: timeout
      in: query
      description: Operation timeout.
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Duration'
