openapi: 3.1.0
info:
  title: Workload Management Query Group API
  description: The Query Group Lifecycle APIs create, update, and delete workload management query groups.
  version: 1.0.0
paths:
  /_wlm/query_group:
    get:
      operationId: wlm.get_query_group.0
      x-operation-group: wlm.get_query_group
      x-version-added: '2.17'
      description: Retrieves the specified query group. If no query group is specified, all query groups in the cluster are retrieved.
      responses:
        '200':
          $ref: '#/components/responses/wlm.get_query_group@200'
    put:
      operationId: wlm.create_query_group.0
      x-operation-group: wlm.create_query_group
      x-version-added: '2.17'
      description: Creates a new query group and sets the resource limits for the new query group.
      requestBody:
        $ref: '#/components/requestBodies/wlm.create_query_group'
      responses:
        '200':
          $ref: '#/components/responses/wlm.create_query_group@200'
  /_wlm/query_group/{name}:
    get:
      operationId: wlm.get_query_group.1
      x-operation-group: wlm.get_query_group
      x-version-added: '2.17'
      description: Retrieves the specified query group. If no query group is specified, all query groups in the cluster are retrieved.
      parameters:
        - $ref: '#/components/parameters/wlm.get_query_group::path.name'
      responses:
        '200':
          $ref: '#/components/responses/wlm.get_query_group@200'
    put:
      operationId: wlm.update_query_group.0
      x-operation-group: wlm.update_query_group
      x-version-added: '2.17'
      description: Updates the specified query group.
      parameters:
        - $ref: '#/components/parameters/wlm.update_query_group::path.name'
      requestBody:
        $ref: '#/components/requestBodies/wlm.update_query_group'
      responses:
        '200':
          $ref: '#/components/responses/wlm.update_query_group@200'
    delete:
      operationId: wlm.delete_query_group.0
      x-operation-group: wlm.delete_query_group
      x-version-added: '2.17'
      description: Deletes the specified query group.
      parameters:
        - $ref: '#/components/parameters/wlm.delete_query_group::path.name'
      responses:
        '200':
          $ref: '#/components/responses/wlm.delete_query_group@200'
components:
  requestBodies:
    wlm.create_query_group:
      content:
        application/json:
          schema:
            $ref: '../schemas/wlm._common.yaml#/components/schemas/QueryGroupCreate'
      required: true
    wlm.update_query_group:
      content:
        application/json:
          schema:
            $ref: '../schemas/wlm._common.yaml#/components/schemas/QueryGroupUpdate'
      required: true
  responses:
    wlm.create_query_group@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/wlm._common.yaml#/components/schemas/QueryGroupResponse'
    wlm.update_query_group@200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/wlm._common.yaml#/components/schemas/QueryGroupResponse'
    wlm.delete_query_group@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              acknowledged:
                type: boolean
    wlm.get_query_group@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              query_groups:
                type: array
                items:
                  $ref: '../schemas/wlm._common.yaml#/components/schemas/QueryGroupResponse'
  parameters:
    wlm.update_query_group::path.name:
      name: name
      in: path
      description: The name of the query group.
      schema:
        type: string
      required: true
    wlm.delete_query_group::path.name:
      name: name
      in: path
      description: The name of the query group.
      schema:
        type: string
      required: true
    wlm.get_query_group::path.name:
      name: name
      in: path
      description: The name of the query group.
      schema:
        type: string
      required: true
