/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/

import * as js2ts from 'json-schema-to-typescript'
import fs from 'fs'
import { read_yaml } from '../helpers'

const schema = read_yaml('json_schemas/test_story.schema.yaml')
void js2ts.compile(schema, 'Story',
  {
    cwd: 'json_schemas/',
    additionalProperties: false,
    ignoreMinAndMaxItems: true,
    unreachableDefinitions: true,
    declareExternallyReferenced: true,
    unknownAny: false,
    style: {
      singleQuote: true,
      singleAttributePerLine: true
    },
    bannerComment: `/*
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file by running:
* "npm run generate-types" in a terminal.
*/
`
  })
  .then(ts => {
    fs.writeFileSync('tools/src/tester/types/story.types.ts', `/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/

/* eslint-disable @typescript-eslint/ban-types */
/* eslint-disable @typescript-eslint/consistent-indexed-object-style */

`
      + ts + `
/* eslint-enable @typescript-eslint/ban-types */
/* eslint-enable @typescript-eslint/consistent-indexed-object-style */
`)
  })
