import * as js2ts from 'json-schema-to-typescript'
import fs from 'fs'
import { read_yaml } from '../../helpers'

const schema = read_yaml('json_schemas/test_story.schema.yaml')
void js2ts.compile(schema, 'Story',
  {
    cwd: 'json_schemas/',
    additionalProperties: false,
    ignoreMinAndMaxItems: true,
    unreachableDefinitions: true,
    declareExternallyReferenced: true,
    unknownAny: false,
    style: {
      singleQuote: true,
      singleAttributePerLine: true
    },
    // multiline comment
    bannerComment: `/* eslint-disable */
    
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file by running:
 * "npx ts-node tools/src/tester/_generate_story_types.ts" in a terminal.
 */`

  })
  .then(ts => { fs.writeFileSync('tools/src/tester/types/story.types.ts', ts) })
