openapi: 3.1.0
info:
  title: ''
  version: ''
components:
  parameters:
    _global::query.pretty:
      name: pretty
      in: query
      description: Whether to pretty format the returned JSON response.
      schema:
        type: boolean
      default: false
    _global::query.human:
      name: human
      in: query
      description: Whether to return human readable values for statistics.
      schema:
        type: boolean
      default: true
    _global::query.error_trace:
      name: error_trace
      in: query
      description: Whether to include the stack trace of returned errors.
      schema:
        type: boolean
      default: false
    _global::query.source:
      name: source
      in: query
      description: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
      schema:
        type: string
    _global::query.filter_path:
      name: filter_path
      in: query
      description: Comma-separated list of filters used to reduce the response.
      schema:
        oneOf:
          - type: string
          - type: array
            items:
              type: string