openapi: 3.1.0
info:
  title: ''
  version: ''
components:
  parameters:
    pretty:
      name: pretty
      in: query
      description: Whether to pretty format the returned JSON response.
      schema:
        type: boolean
        default: false
    human:
      name: human
      in: query
      description: Whether to return human readable values for statistics.
      schema:
        type: boolean
        default: false
    error_trace:
      name: error_trace
      in: query
      description: Whether to include the stack trace of returned errors.
      schema:
        type: boolean
        default: false
    source:
      name: source
      in: query
      description: The URL-encoded request definition. Useful for libraries that do not accept a request body for non-POST requests.
      schema:
        type: string
    filter_path:
      name: filter_path
      in: query
      description: Used to reduce the response. This parameter takes a comma-separated list of filters. It supports using wildcards to match any field or part of a field’s name. You can also exclude fields with "-".
      schema:
        $ref: 'schemas/_common.yaml#/components/schemas/StringOrStringArray'
