openapi: 3.1.0
info:
  title: Schemas of _core.reindex category
  description: Schemas of _core.reindex category
  version: 1.0.0
paths: {}
components:
  schemas:
    Destination:
      type: object
      properties:
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        op_type:
          $ref: '_common.yaml#/components/schemas/OpType'
        pipeline:
          description: The name of the pipeline to use.
          type: string
        routing:
          $ref: '_common.yaml#/components/schemas/Routing'
        version_type:
          $ref: '_common.yaml#/components/schemas/VersionType'
      required:
        - index
    Source:
      type: object
      properties:
        index:
          $ref: '_common.yaml#/components/schemas/Indices'
        query:
          $ref: '_common.query_dsl.yaml#/components/schemas/QueryContainer'
        remote:
          $ref: '#/components/schemas/RemoteSource'
        size:
          description: >-
            The number of documents to index per batch.

            Use when indexing from remote to ensure that the batches fit within the on-heap buffer, which defaults to a maximum size of 100 MB.
          type: number
        slice:
          $ref: '_common.yaml#/components/schemas/SlicedScroll'
        sort:
          $ref: '_common.yaml#/components/schemas/Sort'
        _source:
          $ref: '_common.yaml#/components/schemas/Fields'
        runtime_mappings:
          $ref: '_common.mapping.yaml#/components/schemas/RuntimeFields'
      required:
        - index
    RemoteSource:
      type: object
      properties:
        connect_timeout:
          $ref: '_common.yaml#/components/schemas/Duration'
        headers:
          description: An object containing the headers of the request.
          type: object
          additionalProperties:
            type: string
        host:
          $ref: '_common.yaml#/components/schemas/Host'
        username:
          $ref: '_common.yaml#/components/schemas/Username'
        password:
          $ref: '_common.yaml#/components/schemas/Password'
        socket_timeout:
          $ref: '_common.yaml#/components/schemas/Duration'
      required:
        - host
