openapi: 3.1.0
info:
  title: Schemas of _core.search_shards category
  description: Schemas of _core.search_shards category
  version: 1.0.0
paths: {}
components:
  schemas:
    ShardStoreIndex:
      type: object
      properties:
        aliases:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/Name'
        filter:
          $ref: '_common.query_dsl.yaml#/components/schemas/QueryContainer'
