openapi: 3.1.0
info:
  title: Schemas of cat.indices category
  description: Schemas of cat.indices category
  version: 1.0.0
paths: {}
components:
  schemas:
    IndicesRecord:
      type: object
      properties:
        health:
          description: current health status
          type: string
        status:
          description: open/close status
          type: string
        index:
          description: index name
          type: string
        uuid:
          description: index uuid
          type: string
        pri:
          description: number of primary shards
          type: string
        rep:
          description: number of replica shards
          type: string
        docs.count:
          description: available docs
          oneOf:
            - type: string
            - nullable: true
              type: string
        docs.deleted:
          description: deleted docs
          oneOf:
            - type: string
            - nullable: true
              type: string
        creation.date:
          description: index creation date (millisecond value)
          type: string
        creation.date.string:
          description: index creation date (as string)
          type: string
        store.size:
          description: store size of primaries & replicas
          oneOf:
            - type: string
            - nullable: true
              type: string
        pri.store.size:
          description: store size of primaries
          oneOf:
            - type: string
            - nullable: true
              type: string
        completion.size:
          description: size of completion
          type: string
        pri.completion.size:
          description: size of completion
          type: string
        fielddata.memory_size:
          description: used fielddata cache
          type: string
        pri.fielddata.memory_size:
          description: used fielddata cache
          type: string
        fielddata.evictions:
          description: fielddata evictions
          type: string
        pri.fielddata.evictions:
          description: fielddata evictions
          type: string
        query_cache.memory_size:
          description: used query cache
          type: string
        pri.query_cache.memory_size:
          description: used query cache
          type: string
        query_cache.evictions:
          description: query cache evictions
          type: string
        pri.query_cache.evictions:
          description: query cache evictions
          type: string
        request_cache.memory_size:
          description: used request cache
          type: string
        pri.request_cache.memory_size:
          description: used request cache
          type: string
        request_cache.evictions:
          description: request cache evictions
          type: string
        pri.request_cache.evictions:
          description: request cache evictions
          type: string
        request_cache.hit_count:
          description: request cache hit count
          type: string
        pri.request_cache.hit_count:
          description: request cache hit count
          type: string
        request_cache.miss_count:
          description: request cache miss count
          type: string
        pri.request_cache.miss_count:
          description: request cache miss count
          type: string
        flush.total:
          description: number of flushes
          type: string
        pri.flush.total:
          description: number of flushes
          type: string
        flush.total_time:
          description: time spent in flush
          type: string
        pri.flush.total_time:
          description: time spent in flush
          type: string
        get.current:
          description: number of current get ops
          type: string
        pri.get.current:
          description: number of current get ops
          type: string
        get.time:
          description: time spent in get
          type: string
        pri.get.time:
          description: time spent in get
          type: string
        get.total:
          description: number of get ops
          type: string
        pri.get.total:
          description: number of get ops
          type: string
        get.exists_time:
          description: time spent in successful gets
          type: string
        pri.get.exists_time:
          description: time spent in successful gets
          type: string
        get.exists_total:
          description: number of successful gets
          type: string
        pri.get.exists_total:
          description: number of successful gets
          type: string
        get.missing_time:
          description: time spent in failed gets
          type: string
        pri.get.missing_time:
          description: time spent in failed gets
          type: string
        get.missing_total:
          description: number of failed gets
          type: string
        pri.get.missing_total:
          description: number of failed gets
          type: string
        indexing.delete_current:
          description: number of current deletions
          type: string
        pri.indexing.delete_current:
          description: number of current deletions
          type: string
        indexing.delete_time:
          description: time spent in deletions
          type: string
        pri.indexing.delete_time:
          description: time spent in deletions
          type: string
        indexing.delete_total:
          description: number of delete ops
          type: string
        pri.indexing.delete_total:
          description: number of delete ops
          type: string
        indexing.index_current:
          description: number of current indexing ops
          type: string
        pri.indexing.index_current:
          description: number of current indexing ops
          type: string
        indexing.index_time:
          description: time spent in indexing
          type: string
        pri.indexing.index_time:
          description: time spent in indexing
          type: string
        indexing.index_total:
          description: number of indexing ops
          type: string
        pri.indexing.index_total:
          description: number of indexing ops
          type: string
        indexing.index_failed:
          description: number of failed indexing ops
          type: string
        pri.indexing.index_failed:
          description: number of failed indexing ops
          type: string
        merges.current:
          description: number of current merges
          type: string
        pri.merges.current:
          description: number of current merges
          type: string
        merges.current_docs:
          description: number of current merging docs
          type: string
        pri.merges.current_docs:
          description: number of current merging docs
          type: string
        merges.current_size:
          description: size of current merges
          type: string
        pri.merges.current_size:
          description: size of current merges
          type: string
        merges.total:
          description: number of completed merge ops
          type: string
        pri.merges.total:
          description: number of completed merge ops
          type: string
        merges.total_docs:
          description: docs merged
          type: string
        pri.merges.total_docs:
          description: docs merged
          type: string
        merges.total_size:
          description: size merged
          type: string
        pri.merges.total_size:
          description: size merged
          type: string
        merges.total_time:
          description: time spent in merges
          type: string
        pri.merges.total_time:
          description: time spent in merges
          type: string
        refresh.total:
          description: total refreshes
          type: string
        pri.refresh.total:
          description: total refreshes
          type: string
        refresh.time:
          description: time spent in refreshes
          type: string
        pri.refresh.time:
          description: time spent in refreshes
          type: string
        refresh.external_total:
          description: total external refreshes
          type: string
        pri.refresh.external_total:
          description: total external refreshes
          type: string
        refresh.external_time:
          description: time spent in external refreshes
          type: string
        pri.refresh.external_time:
          description: time spent in external refreshes
          type: string
        refresh.listeners:
          description: number of pending refresh listeners
          type: string
        pri.refresh.listeners:
          description: number of pending refresh listeners
          type: string
        search.fetch_current:
          description: current fetch phase ops
          type: string
        pri.search.fetch_current:
          description: current fetch phase ops
          type: string
        search.fetch_time:
          description: time spent in fetch phase
          type: string
        pri.search.fetch_time:
          description: time spent in fetch phase
          type: string
        search.fetch_total:
          description: total fetch ops
          type: string
        pri.search.fetch_total:
          description: total fetch ops
          type: string
        search.open_contexts:
          description: open search contexts
          type: string
        pri.search.open_contexts:
          description: open search contexts
          type: string
        search.query_current:
          description: current query phase ops
          type: string
        pri.search.query_current:
          description: current query phase ops
          type: string
        search.query_time:
          description: time spent in query phase
          type: string
        pri.search.query_time:
          description: time spent in query phase
          type: string
        search.query_total:
          description: total query phase ops
          type: string
        pri.search.query_total:
          description: total query phase ops
          type: string
        search.scroll_current:
          description: open scroll contexts
          type: string
        pri.search.scroll_current:
          description: open scroll contexts
          type: string
        search.scroll_time:
          description: time scroll contexts held open
          type: string
        pri.search.scroll_time:
          description: time scroll contexts held open
          type: string
        search.scroll_total:
          description: completed scroll contexts
          type: string
        pri.search.scroll_total:
          description: completed scroll contexts
          type: string
        segments.count:
          description: number of segments
          type: string
        pri.segments.count:
          description: number of segments
          type: string
        segments.memory:
          description: memory used by segments
          type: string
        pri.segments.memory:
          description: memory used by segments
          type: string
        segments.index_writer_memory:
          description: memory used by index writer
          type: string
        pri.segments.index_writer_memory:
          description: memory used by index writer
          type: string
        segments.version_map_memory:
          description: memory used by version map
          type: string
        pri.segments.version_map_memory:
          description: memory used by version map
          type: string
        segments.fixed_bitset_memory:
          description: memory used by fixed bit sets for nested object field types and export type filters for types referred in
            _parent fields
          type: string
        pri.segments.fixed_bitset_memory:
          description: memory used by fixed bit sets for nested object field types and export type filters for types referred in
            _parent fields
          type: string
        warmer.current:
          description: current warmer ops
          type: string
        pri.warmer.current:
          description: current warmer ops
          type: string
        warmer.total:
          description: total warmer ops
          type: string
        pri.warmer.total:
          description: total warmer ops
          type: string
        warmer.total_time:
          description: time spent in warmers
          type: string
        pri.warmer.total_time:
          description: time spent in warmers
          type: string
        suggest.current:
          description: number of current suggest ops
          type: string
        pri.suggest.current:
          description: number of current suggest ops
          type: string
        suggest.time:
          description: time spend in suggest
          type: string
        pri.suggest.time:
          description: time spend in suggest
          type: string
        suggest.total:
          description: number of suggest ops
          type: string
        pri.suggest.total:
          description: number of suggest ops
          type: string
        memory.total:
          description: total used memory
          type: string
        pri.memory.total:
          description: total user memory
          type: string
        search.throttled:
          description: indicates if the index is search throttled
          type: string
        bulk.total_operations:
          description: number of bulk shard ops
          type: string
        pri.bulk.total_operations:
          description: number of bulk shard ops
          type: string
        bulk.total_time:
          description: time spend in shard bulk
          type: string
        pri.bulk.total_time:
          description: time spend in shard bulk
          type: string
        bulk.total_size_in_bytes:
          description: total size in bytes of shard bulk
          type: string
        pri.bulk.total_size_in_bytes:
          description: total size in bytes of shard bulk
          type: string
        bulk.avg_time:
          description: average time spend in shard bulk
          type: string
        pri.bulk.avg_time:
          description: average time spend in shard bulk
          type: string
        bulk.avg_size_in_bytes:
          description: average size in bytes of shard bulk
          type: string
        pri.bulk.avg_size_in_bytes:
          description: average size in bytes of shard bulk
          type: string
