openapi: 3.1.0
info:
  title: Schemas of cat.tasks category
  description: Schemas of cat.tasks category
  version: 1.0.0
paths: {}
components:
  schemas:
    TasksRecord:
      type: object
      properties:
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        action:
          description: The task action.
          type: string
        task_id:
          $ref: '_common.yaml#/components/schemas/Id'
        parent_task_id:
          description: The parent task identifier.
          type: string
        type:
          description: The task type.
          type: string
        start_time:
          description: The start time in milliseconds.
          type: string
        timestamp:
          description: The start time in `HH:MM:SS` format.
          type: string
        running_time_ns:
          description: The running time in nanoseconds.
          type: string
        running_time:
          description: The running time.
          type: string
        node_id:
          $ref: '_common.yaml#/components/schemas/NodeId'
        ip:
          description: The IP address for the node.
          type: string
        port:
          description: The bound transport port for the node.
          type: string
        node:
          description: The node name.
          type: string
        version:
          $ref: '_common.yaml#/components/schemas/VersionString'
        x_opaque_id:
          description: The X-Opaque-ID header.
          type: string
        description:
          description: The task action description.
          type: string
