openapi: 3.1.0
info:
  title: Schemas of cluster._common category
  description: Schemas of cluster._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    ComponentTemplate:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        component_template:
          $ref: '#/components/schemas/ComponentTemplateNode'
      required:
        - name
        - component_template
    ComponentTemplateNode:
      type: object
      properties:
        template:
          $ref: '#/components/schemas/ComponentTemplateSummary'
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        _meta:
          $ref: '_common.yaml#/components/schemas/Metadata'
      required:
        - template
    ComponentTemplateSummary:
      type: object
      properties:
        _meta:
          $ref: '_common.yaml#/components/schemas/Metadata'
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        settings:
          type: object
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/IndexSettings'
        mappings:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
        aliases:
          type: object
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/AliasDefinition'
        lifecycle:
          $ref: 'indices._common.yaml#/components/schemas/DataStreamLifecycleWithRollover'
