openapi: 3.1.0
info:
  title: Schemas of indices.update_aliases category
  description: Schemas of indices.update_aliases category
  version: 1.0.0
paths: {}
components:
  schemas:
    Action:
      type: object
      properties:
        add:
          $ref: '#/components/schemas/AddAction'
        remove:
          $ref: '#/components/schemas/RemoveAction'
        remove_index:
          $ref: '#/components/schemas/RemoveIndexAction'
      minProperties: 1
      maxProperties: 1
    AddAction:
      type: object
      properties:
        alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        aliases:
          description: |-
            Aliases for the action.
            Index alias names support date math.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/IndexAlias'
            - type: array
              items:
                $ref: '_common.yaml#/components/schemas/IndexAlias'
        filter:
          $ref: '_common.query_dsl.yaml#/components/schemas/QueryContainer'
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
        index_routing:
          $ref: '_common.yaml#/components/schemas/Routing'
        is_hidden:
          description: If `true`, the alias is hidden.
          type: boolean
        is_write_index:
          description: If `true`, sets the write index or data stream for the alias.
          type: boolean
        routing:
          $ref: '_common.yaml#/components/schemas/Routing'
        search_routing:
          $ref: '_common.yaml#/components/schemas/Routing'
        must_exist:
          description: If `true`, the alias must exist to perform the action.
          type: boolean
    RemoveAction:
      type: object
      properties:
        alias:
          $ref: '_common.yaml#/components/schemas/IndexAlias'
        aliases:
          description: |-
            Aliases for the action.
            Index alias names support date math.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/IndexAlias'
            - type: array
              items:
                $ref: '_common.yaml#/components/schemas/IndexAlias'
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
        must_exist:
          description: If `true`, the alias must exist to perform the action.
          type: boolean
    RemoveIndexAction:
      type: object
      properties:
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
        must_exist:
          description: If `true`, the alias must exist to perform the action.
          type: boolean
