openapi: 3.1.0
info:
  title: Schemas of indices.close category
  description: Schemas of indices.close category
  version: 1.0.0
paths: {}
components:
  schemas:
    CloseIndexResult:
      type: object
      properties:
        closed:
          type: boolean
        shards:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CloseShardResult'
      required:
        - closed
    CloseShardResult:
      type: object
      properties:
        failures:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/ShardFailure'
      required:
        - failures
