openapi: 3.1.0
info:
  title: Schemas of ml._common category
  description: Schemas of ml._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    RegressionInferenceOptions:
      type: object
      properties:
        results_field:
          $ref: '_common.yaml#/components/schemas/Field'
        num_top_feature_importance_values:
          description: Specifies the maximum number of feature importance values per document.
          type: number
    ClassificationInferenceOptions:
      type: object
      properties:
        num_top_classes:
          description: Specifies the number of top class predictions to return. Defaults to 0.
          type: number
        num_top_feature_importance_values:
          description: Specifies the maximum number of feature importance values per document.
          type: number
        prediction_field_type:
          description: 'Specifies the type of the predicted field to write. Acceptable values are: string, number, boolean. When
            boolean is provided 1.0 is transformed to true and 0.0 to false.'
          type: string
        results_field:
          description: The field that is added to incoming documents to contain the inference prediction. Defaults to
            predicted_value.
          type: string
        top_classes_results_field:
          description: Specifies the field to which the top classes are written. Defaults to top_classes.
          type: string
