openapi: 3.1.0
info:
  title: Schemas of remote_store._common category
  description: Schemas of remote_store._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    RemoteStoreRestoreInfo:
      type: object
      properties:
        snapshot:
          type: string
        indices:
          type: array
          items:
            type: string
        shards:
          $ref: '#/components/schemas/RemoteStoreRestoreShardsInfo'
    RemoteStoreRestoreShardsInfo:
      type: object
      properties:
        total:
          type: integer
          format: int32
        failed:
          type: integer
          format: int32
        successful:
          type: integer
          format: int32
