openapi: 3.1.0
info:
  title: Schemas of snapshot.restore category
  description: Schemas of snapshot.restore category
  version: 1.0.0
paths: {}
components:
  schemas:
    SnapshotRestore:
      type: object
      properties:
        indices:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/IndexName'
        snapshot:
          type: string
        shards:
          $ref: '_common.yaml#/components/schemas/ShardStatistics'
      required:
        - indices
        - snapshot
        - shards
