openapi: 3.1.0
info:
  title: Schemas of snapshot.get category
  description: Schemas of snapshot.get category
  version: 1.0.0
paths: {}
components:
  schemas:
    SnapshotResponseItem:
      type: object
      properties:
        repository:
          $ref: '_common.yaml#/components/schemas/Name'
        snapshots:
          type: array
          items:
            $ref: 'snapshot._common.yaml#/components/schemas/SnapshotInfo'
        error:
          $ref: '_common.yaml#/components/schemas/ErrorCause'
      required:
        - repository
