openapi: 3.1.0
info:
  title: Schemas of watcher._common category
  description: Schemas of watcher._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    ScheduleTimeOfDay:
      description: A time of day, expressed either as `hh:mm`, `noon`, `midnight`, or an hour/minutes structure.
      oneOf:
        - type: string
        - $ref: '#/components/schemas/HourAndMinute'
    HourAndMinute:
      type: object
      properties:
        hour:
          type: array
          items:
            type: number
        minute:
          type: array
          items:
            type: number
      required:
        - hour
        - minute
    ActionStatusOptions:
      type: string
      enum:
        - success
        - failure
        - simulated
        - throttled
