openapi: 3.1.0
info:
  title: Schemas of _core.msearch_template category
  description: Schemas of _core.msearch_template category
  version: 1.0.0
paths: {}
components:
  schemas:
    RequestItem:
      oneOf:
        - $ref: '_core.msearch.yaml#/components/schemas/MultisearchHeader'
        - $ref: '#/components/schemas/TemplateConfig'
    TemplateConfig:
      type: object
      properties:
        explain:
          description: If `true`, returns detailed information about score calculation as part of each hit.
          type: boolean
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        params:
          description: |-
            Key-value pairs used to replace Mustache variables in the template.
            The key is the variable name.
            The value is the variable value.
          type: object
          additionalProperties:
            type: object
        profile:
          description: If `true`, the query execution is profiled.
          type: boolean
        source:
          description: |-
            An inline search template. Supports the same parameters as the search API's
            request body. Also supports Mustache variables. If no id is specified, this
            parameter is required.
          type: string
