openapi: 3.1.0
info:
  title: OpenSearch Painless Context API
  description: OpenSearch Painless Context API schemas.
  version: 1.0.0
paths: {}
components:
  schemas:
    PainlessContextResponse:
      type: object
      additionalProperties: true
