openapi: 3.1.0
info:
  title: Schemas of _core.explain category
  description: Schemas of _core.explain category
  version: 1.0.0
paths: {}
components:
  schemas:
    Explanation:
      type: object
      properties:
        description:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ExplanationDetail'
        value:
          oneOf:
            - type: integer
              format: int32
            - type: integer
              format: int64
            - type: number
              format: float
            - type: number
              format: double
      required:
        - description
        - details
        - value
    ExplanationDetail:
      type: object
      properties:
        description:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/ExplanationDetail'
        value:
          oneOf:
            - type: integer
              format: int32
            - type: integer
              format: int64
            - type: number
              format: float
            - type: number
              format: double
      required:
        - description
        - value
