openapi: 3.1.0
info:
  title: Schemas of `_core.termvectors` Category
  description: Schemas of `_core.termvectors` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Filter:
      type: object
      properties:
        max_doc_freq:
          description: |-
            Ignores words that appear in more than the specified number of documents.
            Default is `unbounded`.
          type: number
        max_num_terms:
          description: The maximum number of terms that should be returned per field.
          type: number
        max_term_freq:
          description: |-
            Ignore words with more than this frequency in the source doc.
            Default is `unbounded`.
          type: number
        max_word_length:
          description: |-
            The maximum word length.
            Words longer than this value will be ignored.
            Default is `unbounded`.
          type: number
        min_doc_freq:
          description: Ignore terms which do not occur in at least this many docs.
          type: number
        min_term_freq:
          description: Ignore words with less than this frequency in the source doc.
          type: number
        min_word_length:
          description: |-
            The minimum word length.
            Words shorter than this value will be ignored.
            Default is 0.
          type: number
    TermVector:
      type: object
      properties:
        field_statistics:
          $ref: '#/components/schemas/FieldStatistics'
        terms:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Term'
      required:
        - field_statistics
        - terms
    FieldStatistics:
      type: object
      properties:
        doc_count:
          type: number
        sum_doc_freq:
          type: number
        sum_ttf:
          type: number
      required:
        - doc_count
        - sum_doc_freq
        - sum_ttf
    Term:
      type: object
      properties:
        doc_freq:
          type: number
        score:
          type: number
        term_freq:
          type: number
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/Token'
        ttf:
          type: number
      required:
        - term_freq
    Token:
      type: object
      properties:
        end_offset:
          type: number
        payload:
          type: string
        position:
          type: number
        start_offset:
          type: number
      required:
        - position
