openapi: 3.1.0
info:
  title: Schemas of _core._common category
  description: Schemas of _core._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    DeletedPit:
      type: object
      properties:
        successful:
          type: boolean
        pit_id:
          type: string
    PitsDetailsDeleteAll:
      type: object
      properties:
        successful:
          type: boolean
        pit_id:
          type: string
    PitDetail:
      type: object
      properties:
        pit_id:
          type: string
        creation_time:
          type: integer
          format: int64
        keep_alive:
          type: integer
          format: int64
    ShardStatistics:
      type: object
      properties:
        total:
          type: integer
          format: int32
        successful:
          type: integer
          format: int32
        skipped:
          type: integer
          format: int32
        failed:
          type: integer
          format: int32
