openapi: 3.1.0
info:
  title: Schemas of `_core.get_script_languages` Category
  description: Schemas of `_core.get_script_languages` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    LanguageContext:
      type: object
      properties:
        contexts:
          type: array
          items:
            type: string
        language:
          $ref: '_common.yaml#/components/schemas/ScriptLanguage'
      required:
        - contexts
        - language
