openapi: 3.1.0
info:
  title: Schemas of _core.get_script_context category
  description: Schemas of _core.get_script_context category
  version: 1.0.0
paths: {}
components:
  schemas:
    Context:
      type: object
      properties:
        methods:
          type: array
          items:
            $ref: '#/components/schemas/ContextMethod'
        name:
          $ref: '_common.yaml#/components/schemas/Name'
      required:
        - methods
        - name
    ContextMethod:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        return_type:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ContextMethodParam'
      required:
        - name
        - return_type
        - params
    ContextMethodParam:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        type:
          type: string
      required:
        - name
        - type
