openapi: 3.1.0
info:
  title: Schemas of `_core.get` Category
  description: Schemas of `_core.get` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    GetResult:
      allOf:
        - $ref: '#/components/schemas/GetResultBase'
        - type: object
          properties:
            _source:
              $ref: '_common.yaml#/components/schemas/TDocument'
    GetResultBase:
      type: object
      properties:
        _type:
          $ref: '_common.yaml#/components/schemas/Type'
        _index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        fields:
          type: object
          additionalProperties: true
        found:
          type: boolean
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _primary_term:
          type: integer
          format: int64
        _routing:
          type: string
        _seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        _source:
          $ref: '_common.yaml#/components/schemas/TDocument'
        _version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
      required:
        - _id
        - _index
        - found
