openapi: 3.1.0
info:
  title: Schemas of _core.get category
  description: Schemas of _core.get category
  version: 1.0.0
paths: {}
components:
  schemas:
    GetResult:
      type: object
      properties:
        _index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        fields:
          type: object
          additionalProperties:
            type: object
        found:
          type: boolean
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _primary_term:
          type: number
        _routing:
          type: string
        _seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        _source:
          type: object
        _version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
      required:
        - _index
        - found
        - _id
