openapi: 3.1.0
info:
  title: OpenSearch Painless Context API
  description: OpenSearch Painless Context API schemas.
  version: 1.0.0
paths: {}
components:
  schemas:
    PainlessContextResponse:
      oneOf:
        - $ref: '#/components/schemas/PainlessContextNames'
        - $ref: '#/components/schemas/PainlessContextInfo'
    PainlessContextNames:
      type: object
      properties:
        contexts:
          type: array
          items:
            type: string
      required:
        - contexts
    PainlessContextInfo:
      type: object
      properties:
        name:
          type: string
        classes:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextClass'
        imported_methods:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextMethod'
        class_bindings:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextClassBinding'
        instance_bindings:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextInstanceBinding'
      required:
        - class_bindings
        - classes
        - imported_methods
        - instance_bindings
        - name
    PainlessContextClass:
      type: object
      properties:
        name:
          type: string
        imported:
          type: boolean
        constructors:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextConstructor'
        static_methods:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextMethod'
        methods:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextMethod'
        static_fields:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextField'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/PainlessContextField'
      required:
        - constructors
        - fields
        - imported
        - methods
        - name
        - static_fields
        - static_methods
    PainlessContextConstructor:
      type: object
      properties:
        declaring:
          type: string
        parameters:
          type: array
          items:
            type: string
      required:
        - declaring
        - parameters
    PainlessContextMethod:
      type: object
      properties:
        declaring:
          type: string
        name:
          type: string
        return:
          type: string
        parameters:
          type: array
          items:
            type: string
      required:
        - declaring
        - name
        - parameters
        - return
    PainlessContextField:
      type: object
      properties:
        declaring:
          type: string
        name:
          type: string
        type:
          type: string
      required:
        - declaring
        - name
        - type
    PainlessContextClassBinding:
      type: object
      properties:
        declaring:
          type: string
        name:
          type: string
        return:
          type: string
        read_only:
          type: integer
          format: int32
        parameters:
          type: array
          items:
            type: string
      required:
        - declaring
        - name
        - parameters
        - read_only
        - return
    PainlessContextInstanceBinding:
      type: object
      properties:
        declaring:
          type: string
        name:
          type: string
        return:
          type: string
        parameters:
          type: array
          items:
            type: string
      required:
        - declaring
        - name
        - parameters
        - return
