openapi: 3.1.0
info:
  title: Schemas of _core.mget category
  description: Schemas of _core.mget category
  version: 1.0.0
paths: {}
components:
  schemas:
    Operation:
      type: object
      properties:
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        routing:
          $ref: '_common.yaml#/components/schemas/Routing'
        _source:
          $ref: '_core.search.yaml#/components/schemas/SourceConfig'
        stored_fields:
          $ref: '_common.yaml#/components/schemas/Fields'
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        version_type:
          $ref: '_common.yaml#/components/schemas/VersionType'
      required:
        - _id
    ResponseItem:
      oneOf:
        - $ref: '_core.get.yaml#/components/schemas/GetResult'
        - $ref: '#/components/schemas/MultiGetError'
    MultiGetError:
      type: object
      properties:
        error:
          $ref: '_common.yaml#/components/schemas/ErrorCause'
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _index:
          $ref: '_common.yaml#/components/schemas/IndexName'
      required:
        - error
        - _id
        - _index
