openapi: 3.1.0
info:
  title: Schemas of cat.aliases category
  description: Schemas of cat.aliases category
  version: 1.0.0
paths: {}
components:
  schemas:
    AliasesRecord:
      type: object
      properties:
        alias:
          description: alias name
          type: string
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        filter:
          description: filter
          type: string
        routing.index:
          description: index routing
          type: string
        routing.search:
          description: search routing
          type: string
        is_write_index:
          description: write index
          type: string
