openapi: 3.1.0
info:
  title: Schemas of cat.thread_pool category
  description: Schemas of cat.thread_pool category
  version: 1.0.0
paths: {}
components:
  schemas:
    ThreadPoolRecord:
      type: object
      properties:
        node_name:
          description: The node name.
          type: string
        node_id:
          $ref: '_common.yaml#/components/schemas/NodeId'
        ephemeral_node_id:
          description: The ephemeral node identifier.
          type: string
        pid:
          description: The process identifier.
          type: string
        host:
          description: The host name for the current node.
          type: string
        ip:
          description: The IP address for the current node.
          type: string
        port:
          description: The bound transport port for the current node.
          type: string
        name:
          description: The thread pool name.
          type: string
        type:
          description: |-
            The thread pool type.
            Returned values include `fixed`, `fixed_auto_queue_size`, `direct`, and `scaling`.
          type: string
        active:
          description: The number of active threads in the current thread pool.
          type: string
        pool_size:
          description: The number of threads in the current thread pool.
          type: string
        queue:
          description: The number of tasks currently in queue.
          type: string
        queue_size:
          description: The maximum number of tasks permitted in the queue.
          type: string
        rejected:
          description: The number of rejected tasks.
          type: string
        largest:
          description: The highest number of active threads in the current thread pool.
          type: string
        completed:
          description: The number of completed tasks.
          type: string
        core:
          description: The core number of active threads allowed in a scaling thread pool.
          oneOf:
            - type: string
            - nullable: true
              type: string
        max:
          description: The maximum number of active threads allowed in a scaling thread pool.
          oneOf:
            - type: string
            - nullable: true
              type: string
        size:
          description: The number of active threads allowed in a fixed thread pool.
          oneOf:
            - type: string
            - nullable: true
              type: string
        keep_alive:
          description: The thread keep alive time.
          oneOf:
            - type: string
            - nullable: true
              type: string
