openapi: 3.1.0
info:
  title: Schemas of cat.templates category
  description: Schemas of cat.templates category
  version: 1.0.0
paths: {}
components:
  schemas:
    TemplatesRecord:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        index_patterns:
          description: The template index patterns.
          type: string
        order:
          description: The template application order or priority number.
          type: string
        version:
          description: The template version.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/VersionString'
            - nullable: true
              type: string
        composed_of:
          description: The component templates that comprise the index template.
          type: string
