openapi: 3.1.0
info:
  title: Schemas of `cat.fielddata` Category
  description: Schemas of `cat.fielddata` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    FielddataRecord:
      type: object
      properties:
        id:
          description: node id
          type: string
        host:
          description: hostname
          type: string
        ip:
          description: ip address
          type: string
        node:
          description: node name
          type: string
        field:
          description: field name
          type: string
        size:
          description: field data usage
          type: string
