openapi: 3.1.0
info:
  title: Schemas of cat._common category
  description: Schemas of cat._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    CatPitSegmentsRecord:
      type: object
      properties:
        index:
          type: string
        shard:
          type: string
        prirep:
          type: string
        ip:
          type: string
        segment:
          type: string
        generation:
          type: string
        docs.count:
          type: string
        docs.deleted:
          type: string
        size:
          type: string
        size.memory:
          type: string
        committed:
          type: string
        searchable:
          type: string
        version:
          type: string
        compound:
          type: string
    CatSegmentReplicationRecord:
      type: object
      properties:
        shardId:
          type: string
        target_node:
          type: string
        target_host:
          type: string
        checkpoints_behind:
          type: string
        bytes_behind:
          type: string
        current_lag:
          type: string
        last_completed_lag:
          type: string
        rejected_requests:
          type: string
        stage:
          type: string
        time:
          type: string
        files_fetched:
          type: string
        files_percent:
          type: string
        bytes_fetched:
          type: string
        bytes_percent:
          type: string
        start_time:
          type: string
        stop_time:
          type: string
        files:
          type: string
        files_total:
          type: string
        bytes:
          type: string
        bytes_total:
          type: string
        replicating_stage_time_taken:
          type: string
        get_checkpoint_info_stage_time_taken:
          type: string
        file_diff_stage_time_taken:
          type: string
        get_files_stage_time_taken:
          type: string
        finalize_replication_stage_time_taken:
          type: string
