openapi: 3.1.0
info:
  title: Schemas of cat.recovery category
  description: Schemas of cat.recovery category
  version: 1.0.0
paths: {}
components:
  schemas:
    RecoveryRecord:
      type: object
      properties:
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        shard:
          description: The shard name.
          type: string
        start_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
        start_time_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        stop_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
        stop_time_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        time:
          $ref: '_common.yaml#/components/schemas/Duration'
        type:
          description: The recovery type.
          type: string
        stage:
          description: The recovery stage.
          type: string
        source_host:
          description: The source host.
          type: string
        source_node:
          description: The source node name.
          type: string
        target_host:
          description: The target host.
          type: string
        target_node:
          description: The target node name.
          type: string
        repository:
          description: The repository name.
          type: string
        snapshot:
          description: The snapshot name.
          type: string
        files:
          description: The number of files to recover.
          type: string
        files_recovered:
          description: The files recovered.
          type: string
        files_percent:
          $ref: '_common.yaml#/components/schemas/Percentage'
        files_total:
          description: The total number of files.
          type: string
        bytes:
          description: The number of bytes to recover.
          type: string
        bytes_recovered:
          description: The bytes recovered.
          type: string
        bytes_percent:
          $ref: '_common.yaml#/components/schemas/Percentage'
        bytes_total:
          description: The total number of bytes.
          type: string
        translog_ops:
          description: The number of translog operations to recover.
          type: string
        translog_ops_recovered:
          description: The translog operations recovered.
          type: string
        translog_ops_percent:
          $ref: '_common.yaml#/components/schemas/Percentage'
