openapi: 3.1.0
info:
  title: Schemas of `cat.master` Category
  description: Schemas of `cat.master` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    MasterRecord:
      type: object
      properties:
        id:
          description: node id
          type: string
        host:
          description: hostname
          type: string
        ip:
          description: IP address
          type: string
        node:
          description: node name
          type: string
