openapi: 3.1.0
info:
  title: Schemas of `cat.indices` Category
  description: Schemas of `cat.indices` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    IndicesRecord:
      type: object
      properties:
        health:
          description: current health status
          type: string
        status:
          description: open/close status
          type: string
        index:
          description: index name
          type: string
        uuid:
          description: index UUID
          type: string
        pri:
          description: number of primary shards
          type: string
        rep:
          description: number of replica shards
          type: string
        docs.count:
          description: available docs
          type: ['null', string]
        docs.deleted:
          description: deleted docs
          type: ['null', string]
        creation.date:
          description: index creation date (millisecond value)
          type: string
        creation.date.string:
          description: index creation date (as string)
          type: string
        store.size:
          description: store size of primaries and replicas
          type: ['null', string]
        pri.store.size:
          description: store size of primaries
          type: ['null', string]
        completion.size:
          description: size of completion
          type: ['null', string]
        pri.completion.size:
          description: size of completion
          type: ['null', string]
        fielddata.memory_size:
          description: used field data cache
          type: ['null', string]
        pri.fielddata.memory_size:
          description: used field data cache
          type: ['null', string]
        fielddata.evictions:
          description: field data evictions
          type: ['null', string]
        pri.fielddata.evictions:
          description: field data evictions
          type: ['null', string]
        query_cache.memory_size:
          description: used query cache
          type: ['null', string]
        pri.query_cache.memory_size:
          description: used query cache
          type: ['null', string]
        query_cache.evictions:
          description: query cache evictions
          type: ['null', string]
        pri.query_cache.evictions:
          description: query cache evictions
          type: ['null', string]
        request_cache.memory_size:
          description: used request cache
          type: ['null', string]
        pri.request_cache.memory_size:
          description: used request cache
          type: ['null', string]
        request_cache.evictions:
          description: request cache evictions
          type: ['null', string]
        pri.request_cache.evictions:
          description: request cache evictions
          type: ['null', string]
        request_cache.hit_count:
          description: request cache hit count
          type: ['null', string]
        pri.request_cache.hit_count:
          description: request cache hit count
          type: ['null', string]
        request_cache.miss_count:
          description: request cache miss count
          type: ['null', string]
        pri.request_cache.miss_count:
          description: request cache miss count
          type: ['null', string]
        flush.total:
          description: number of flushes
          type: ['null', string]
        pri.flush.total:
          description: number of flushes
          type: ['null', string]
        flush.total_time:
          description: time spent in flush
          type: ['null', string]
        pri.flush.total_time:
          description: time spent in flush
          type: ['null', string]
        get.current:
          description: number of current get ops
          type: ['null', string]
        pri.get.current:
          description: number of current get ops
          type: ['null', string]
        get.time:
          description: time spent in get
          type: ['null', string]
        pri.get.time:
          description: time spent in get
          type: ['null', string]
        get.total:
          description: number of get ops
          type: ['null', string]
        pri.get.total:
          description: number of get ops
          type: ['null', string]
        get.exists_time:
          description: time spent in successful gets
          type: ['null', string]
        pri.get.exists_time:
          description: time spent in successful gets
          type: ['null', string]
        get.exists_total:
          description: number of successful gets
          type: ['null', string]
        pri.get.exists_total:
          description: number of successful gets
          type: ['null', string]
        get.missing_time:
          description: time spent in failed gets
          type: ['null', string]
        pri.get.missing_time:
          description: time spent in failed gets
          type: ['null', string]
        get.missing_total:
          description: number of failed gets
          type: ['null', string]
        pri.get.missing_total:
          description: number of failed gets
          type: ['null', string]
        indexing.delete_current:
          description: number of current deletions
          type: ['null', string]
        pri.indexing.delete_current:
          description: number of current deletions
          type: ['null', string]
        indexing.delete_time:
          description: time spent in deletions
          type: ['null', string]
        pri.indexing.delete_time:
          description: time spent in deletions
          type: ['null', string]
        indexing.delete_total:
          description: number of delete ops
          type: ['null', string]
        pri.indexing.delete_total:
          description: number of delete ops
          type: ['null', string]
        indexing.index_current:
          description: number of current indexing ops
          type: ['null', string]
        pri.indexing.index_current:
          description: number of current indexing ops
          type: ['null', string]
        indexing.index_time:
          description: time spent in indexing
          type: ['null', string]
        pri.indexing.index_time:
          description: time spent in indexing
          type: ['null', string]
        indexing.index_total:
          description: number of indexing ops
          type: ['null', string]
        pri.indexing.index_total:
          description: number of indexing ops
          type: ['null', string]
        indexing.index_failed:
          description: number of failed indexing ops
          type: ['null', string]
        pri.indexing.index_failed:
          description: number of failed indexing ops
          type: ['null', string]
        merges.current:
          description: number of current merges
          type: ['null', string]
        pri.merges.current:
          description: number of current merges
          type: ['null', string]
        merges.current_docs:
          description: number of current merging docs
          type: ['null', string]
        pri.merges.current_docs:
          description: number of current merging docs
          type: ['null', string]
        merges.current_size:
          description: size of current merges
          type: ['null', string]
        pri.merges.current_size:
          description: size of current merges
          type: ['null', string]
        merges.total:
          description: number of completed merge ops
          type: ['null', string]
        pri.merges.total:
          description: number of completed merge ops
          type: ['null', string]
        merges.total_docs:
          description: docs merged
          type: ['null', string]
        pri.merges.total_docs:
          description: docs merged
          type: ['null', string]
        merges.total_size:
          description: size merged
          type: ['null', string]
        pri.merges.total_size:
          description: size merged
          type: ['null', string]
        merges.total_time:
          description: time spent in merges
          type: ['null', string]
        pri.merges.total_time:
          description: time spent in merges
          type: ['null', string]
        merges.warmer.total_invocations:
          description: total invocations of merged segment warmer
          type: [ 'null', string ]
        pri.merges.warmer.total_invocations:
          description: total invocations of merged segment warmer
          type: [ 'null', string ]
        merges.warmer.total_time:
          description: total wallclock time spent in the warming operation
          type: [ 'null', string ]
        pri.merges.warmer.total_time:
          description: total wallclock time spent in the warming operation
          type: [ 'null', string ]
        merges.warmer.ongoing_count:
          description: point-in-time metric for number of in-progress warm operations
          type: [ 'null', string ]
        pri.merges.warmer.ongoing_count:
          description: point-in-time metric for number of in-progress warm operations
          type: [ 'null', string ]
        merges.warmer.total_bytes_received:
          description: total bytes received by a replica shard during the warm operation
          type: [ 'null', string ]
        pri.merges.warmer.total_bytes_received:
          description: total bytes received by a replica shard during the warm operation
          type: [ 'null', string ]
        merges.warmer.total_bytes_sent:
          description: total bytes sent by a primary shard during the warm operation
          type: [ 'null', string ]
        pri.merges.warmer.total_bytes_sent:
          description: total bytes sent by a primary shard during the warm operation
          type: [ 'null', string ]
        merges.warmer.total_receive_time:
          description: total wallclock time spent receiving merged segments by a replica shard
          type: [ 'null', string ]
        pri.merges.warmer.total_receive_time:
          description: total wallclock time spent receiving merged segments by a replica shard
          type: [ 'null', string ]
        merges.warmer.total_failure_count:
          description: total failures in merged segment warmer
          type: [ 'null', string ]
        pri.merges.warmer.total_failure_count:
          description: total failures in merged segment warmer
          type: [ 'null', string ]
        merges.warmer.total_send_time:
          description: total wallclock time spent sending merged segments by a primary shard
          type: [ 'null', string ]
        pri.merges.warmer.total_send_time:
          description: total wallclock time spent sending merged segments by a primary shard
          type: [ 'null', string ]
        refresh.total:
          description: total refreshes
          type: ['null', string]
        pri.refresh.total:
          description: total refreshes
          type: ['null', string]
        refresh.time:
          description: time spent in refreshes
          type: ['null', string]
        pri.refresh.time:
          description: time spent in refreshes
          type: ['null', string]
        refresh.external_total:
          description: total external refreshes
          type: ['null', string]
        pri.refresh.external_total:
          description: total external refreshes
          type: ['null', string]
        refresh.external_time:
          description: time spent in external refreshes
          type: ['null', string]
        pri.refresh.external_time:
          description: time spent in external refreshes
          type: ['null', string]
        refresh.listeners:
          description: number of pending refresh listeners
          type: ['null', string]
        pri.refresh.listeners:
          description: number of pending refresh listeners
          type: ['null', string]
        search.fetch_current:
          description: current fetch phase ops
          type: ['null', string]
        pri.search.fetch_current:
          description: current fetch phase ops
          type: ['null', string]
        search.fetch_time:
          description: time spent in fetch phase
          type: ['null', string]
        pri.search.fetch_time:
          description: time spent in fetch phase
          type: ['null', string]
        search.fetch_total:
          description: total fetch ops
          type: ['null', string]
        pri.search.fetch_total:
          description: total fetch ops
          type: ['null', string]
        search.open_contexts:
          description: open search contexts
          type: ['null', string]
        pri.search.open_contexts:
          description: open search contexts
          type: ['null', string]
        search.query_current:
          description: current query phase ops
          type: ['null', string]
        pri.search.query_current:
          description: current query phase ops
          type: ['null', string]
        search.query_time:
          description: time spent in query phase
          type: ['null', string]
        pri.search.query_time:
          description: time spent in query phase
          type: ['null', string]
        search.query_total:
          description: total query phase ops
          type: ['null', string]
        pri.search.query_total:
          description: total query phase ops
          type: ['null', string]
        search.concurrent_query_current:
          type: ['null', string]
        pri.search.concurrent_query_current:
          type: ['null', string]
        search.concurrent_query_time:
          type: ['null', string]
        pri.search.concurrent_query_time:
          type: ['null', string]
        search.concurrent_query_total:
          type: ['null', string]
        pri.search.concurrent_query_total:
          type: ['null', string]
        search.concurrent_avg_slice_count:
          type: ['null', string]
        pri.search.concurrent_avg_slice_count:
          type: ['null', string]
        search.scroll_current:
          description: open scroll contexts
          type: ['null', string]
        pri.search.scroll_current:
          description: open scroll contexts
          type: ['null', string]
        search.scroll_time:
          description: time scroll contexts held open
          type: ['null', string]
        pri.search.scroll_time:
          description: time scroll contexts held open
          type: ['null', string]
        search.scroll_total:
          description: completed scroll contexts
          type: ['null', string]
        pri.search.scroll_total:
          description: completed scroll contexts
          type: ['null', string]
        search.point_in_time_current:
          type: ['null', string]
        pri.search.point_in_time_current:
          type: ['null', string]
        search.point_in_time_time:
          type: ['null', string]
        pri.search.point_in_time_time:
          type: ['null', string]
        search.point_in_time_total:
          type: ['null', string]
        pri.search.point_in_time_total:
          type: ['null', string]
        segments.count:
          description: number of segments
          type: ['null', string]
        pri.segments.count:
          description: number of segments
          type: ['null', string]
        segments.memory:
          description: memory used by segments
          type: ['null', string]
        pri.segments.memory:
          description: memory used by segments
          type: ['null', string]
        segments.index_writer_memory:
          description: memory used by index writer
          type: ['null', string]
        pri.segments.index_writer_memory:
          description: memory used by index writer
          type: ['null', string]
        segments.version_map_memory:
          description: memory used by version map
          type: ['null', string]
        pri.segments.version_map_memory:
          description: memory used by version map
          type: ['null', string]
        segments.fixed_bitset_memory:
          description: memory used by fixed bit sets for nested object field types and export type filters for types referred in `_parent` fields
          type: ['null', string]
        pri.segments.fixed_bitset_memory:
          description: memory used by fixed bit sets for nested object field types and export type filters for types referred in `_parent` fields
          type: ['null', string]
        warmer.current:
          description: current warmer ops
          type: ['null', string]
        pri.warmer.current:
          description: current warmer ops
          type: ['null', string]
        warmer.total:
          description: total warmer ops
          type: ['null', string]
        pri.warmer.total:
          description: total warmer ops
          type: ['null', string]
        warmer.total_time:
          description: time spent in warmers
          type: ['null', string]
        pri.warmer.total_time:
          description: time spent in warmers
          type: ['null', string]
        suggest.current:
          description: number of current suggest ops
          type: ['null', string]
        pri.suggest.current:
          description: number of current suggest ops
          type: ['null', string]
        suggest.time:
          description: time spend in suggest
          type: ['null', string]
        pri.suggest.time:
          description: time spend in suggest
          type: ['null', string]
        suggest.total:
          description: number of suggest ops
          type: ['null', string]
        pri.suggest.total:
          description: number of suggest ops
          type: ['null', string]
        memory.total:
          description: total used memory
          type: string
        pri.memory.total:
          description: total user memory
          type: string
        search.throttled:
          description: indicates if the index is search throttled
          type: string
