openapi: 3.1.0
info:
  title: Schemas of cat.count category
  description: Schemas of cat.count category
  version: 1.0.0
paths: {}
components:
  schemas:
    CountRecord:
      type: object
      properties:
        epoch:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitSeconds'
        timestamp:
          $ref: '_common.yaml#/components/schemas/TimeOfDay'
        count:
          description: the document count
          type: string
