openapi: 3.1.0
info:
  title: Schemas of cat.health category
  description: Schemas of cat.health category
  version: 1.0.0
paths: {}
components:
  schemas:
    HealthRecord:
      type: object
      properties:
        epoch:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitSeconds'
        timestamp:
          $ref: '_common.yaml#/components/schemas/TimeOfDay'
        cluster:
          description: cluster name
          type: string
        status:
          description: health status
          type: string
        node.total:
          description: total number of nodes
          type: string
        node.data:
          description: number of nodes that can store data
          type: string
        shards:
          description: total number of shards
          type: string
        pri:
          description: number of primary shards
          type: string
        relo:
          description: number of relocating nodes
          type: string
        init:
          description: number of initializing nodes
          type: string
        unassign:
          description: number of unassigned shards
          type: string
        pending_tasks:
          description: number of pending tasks
          type: string
        max_task_wait_time:
          description: wait time of longest task pending
          type: string
        active_shards_percent:
          description: active number of shards in percent
          type: string
