openapi: 3.1.0
info:
  title: Schemas of cat.snapshots category
  description: Schemas of cat.snapshots category
  version: 1.0.0
paths: {}
components:
  schemas:
    SnapshotsRecord:
      type: object
      properties:
        id:
          description: The unique identifier for the snapshot.
          type: string
        repository:
          description: The repository name.
          type: string
        status:
          description: |-
            The state of the snapshot process.
            Returned values include:
            `FAILED`: The snapshot process failed.
            `INCOMPATIBLE`: The snapshot process is incompatible with the current cluster version.
            `IN_PROGRESS`: The snapshot process started but has not completed.
            `PARTIAL`: The snapshot process completed with a partial success.
            `SUCCESS`: The snapshot process completed with a full success.
          type: string
        start_epoch:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitSeconds'
        start_time:
          $ref: 'watcher._common.yaml#/components/schemas/ScheduleTimeOfDay'
        end_epoch:
          $ref: '_common.yaml#/components/schemas/StringifiedEpochTimeUnitSeconds'
        end_time:
          $ref: '_common.yaml#/components/schemas/TimeOfDay'
        duration:
          $ref: '_common.yaml#/components/schemas/Duration'
        indices:
          description: The number of indices in the snapshot.
          type: string
        successful_shards:
          description: The number of successful shards in the snapshot.
          type: string
        failed_shards:
          description: The number of failed shards in the snapshot.
          type: string
        total_shards:
          description: The total number of shards in the snapshot.
          type: string
        reason:
          description: The reason for any snapshot failures.
          type: string
