openapi: 3.1.0
info:
  title: Schemas of `cat._common` Category.
  description: Schemas of `cat._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    ResponseFormat:
      type: string
      description: |-
        The response format returned by `_cat` operations. Equivalent to the HTTP `Accept` header but expressed as a query parameter.
        When the parameter is omitted the server responds with `text`.
      default: text
      enum:
        - cbor
        - json
        - smile
        - text
        - yaml
