openapi: 3.1.0
info:
  title: Schemas of cat.cluster_manager category
  description: Schemas of cat.cluster_manager category
  version: 1.0.0
paths: {}
components:
  schemas:
    ClusterManagerRecord:
      type: object
      properties:
        id:
          description: node id
          type: string
        host:
          description: host name
          type: string
        ip:
          description: ip address
          type: string
        node:
          description: node name
          type: string
