openapi: 3.1.0
info:
  title: Schemas of cat.nodeattrs category
  description: Schemas of cat.nodeattrs category
  version: 1.0.0
paths: {}
components:
  schemas:
    NodeAttributesRecord:
      type: object
      properties:
        node:
          description: The node name.
          type: string
        id:
          description: The unique node identifier.
          type: string
        pid:
          description: The process identifier.
          type: string
        host:
          description: The host name.
          type: string
        ip:
          description: The IP address.
          type: string
        port:
          description: The bound transport port.
          type: string
        attr:
          description: The attribute name.
          type: string
        value:
          description: The attribute value.
          type: string
