openapi: 3.1.0
info:
  title: Schemas of cat.allocation category
  description: Schemas of cat.allocation category
  version: 1.0.0
paths: {}
components:
  schemas:
    AllocationRecord:
      type: object
      properties:
        shards:
          description: Number of primary and replica shards assigned to the node.
          type: string
        disk.indices:
          description: >-
            Disk space used by the node’s shards. Does not include disk space for the translog or unassigned shards.

            IMPORTANT: This metric double-counts disk space for hard-linked files, such as those created when shrinking, splitting, or cloning an index.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/ByteSize'
            - nullable: true
              type: string
        disk.used:
          description: >-
            Total disk space in use.

            Opensearch retrieves this metric from the node’s operating system (OS).

            The metric includes disk space for: Opensearch, including the translog and unassigned shards; the node’s operating system; any other applications or files on the node.

            Unlike `disk.indices`, this metric does not double-count disk space for hard-linked files.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/ByteSize'
            - nullable: true
              type: string
        disk.avail:
          description: |-
            Free disk space available to Opensearch.
            Opensearch retrieves this metric from the node’s operating system.
            Disk-based shard allocation uses this metric to assign shards to nodes based on available disk space.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/ByteSize'
            - nullable: true
              type: string
        disk.total:
          description: Total disk space for the node, including in-use and available space.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/ByteSize'
            - nullable: true
              type: string
        disk.percent:
          description: Total percentage of disk space in use. Calculated as `disk.used / disk.total`.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/Percentage'
            - nullable: true
              type: string
        host:
          description: Network host for the node. Set using the `network.host` setting.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/Host'
            - nullable: true
              type: string
        ip:
          description: IP address and port for the node.
          oneOf:
            - $ref: '_common.yaml#/components/schemas/Ip'
            - nullable: true
              type: string
        node:
          description: Name for the node. Set using the `node.name` setting.
          type: string
