openapi: 3.1.0
info:
  title: Schemas of Decommission Awareness.
  description: Schemas of decommission awareness category.
  version: 1.0.0
paths: {}
components:
  schemas:
    DecommissionStatus:
      description: An enumeration of the states during decommissioning.
      oneOf:
        - type: string
          const: INIT
          description: Decommission process is initiated, and to-be-decommissioned leader is excluded from voting config.
        - type: string
          const: DRAINING
          description: Decommission process is initiated, and the zone is being drained.
        - type: string
          const: IN_PROGRESS
          description: Decommission process has started, decommissioned nodes should be removed.
        - type: string
          const: SUCCESSFUL
          description: Decommission action completed.
        - type: string
          const: FAILED
          description: Decommission request failed.
