openapi: 3.1.0
info:
  title: Schemas of cluster.state category
  description: Schemas of cluster.state category
  version: 1.0.0
paths: {}
components:
  schemas:
    Metric:
      type: string
      enum:
        - blocks
        - metadata
        - nodes
        - routing_table
        - routing_nodes
        - master_node
        - cluster_manager_node
        - version
        - _all