openapi: 3.1.0
info:
  title: Schemas of Weighted Routing Category
  description: Schemas of weighted routing category.
  version: 1.0.0
paths: {}
components:
  schemas:
    WeightsBase:
      type: object
      properties:
        _version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        weights:
          type: object
          additionalProperties:
            type: string
