openapi: 3.1.0
info:
  title: Schemas of `cluster.allocation_explain` Category
  description: Schemas of `cluster.allocation_explain` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Decision:
      type: string
      enum:
        - allocation_delayed
        - awaiting_info
        - no
        - no_attempt
        - no_valid_shard_copy
        - throttled
        - worse_balance
        - yes
    AllocationDecision:
      type: object
      properties:
        decider:
          type: string
        decision:
          $ref: '#/components/schemas/AllocationExplainDecision'
        explanation:
          type: string
      required:
        - decider
        - decision
        - explanation
    AllocationExplainDecision:
      type: string
      enum:
        - ALWAYS
        - NO
        - THROTTLE
        - YES
    ClusterInfo:
      type: object
      properties:
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NodeDiskUsage'
        shard_sizes:
          type: object
          additionalProperties:
            oneOf:
              - $ref: '_common.yaml#/components/schemas/ByteCount'
              - $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        shard_data_set_sizes:
          type: object
          additionalProperties:
            type: string
        shard_paths:
          type: object
          additionalProperties:
            type: string
        reserved_sizes:
          type: array
          items:
            $ref: '#/components/schemas/ReservedSize'
      required:
        - nodes
        - reserved_sizes
        - shard_paths
        - shard_sizes
    NodeDiskUsage:
      type: object
      properties:
        node_name:
          $ref: '_common.yaml#/components/schemas/Name'
        least_available:
          $ref: '#/components/schemas/DiskUsage'
        most_available:
          $ref: '#/components/schemas/DiskUsage'
      required:
        - least_available
        - most_available
        - node_name
    DiskUsage:
      type: object
      properties:
        path:
          type: string
        total:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        total_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        used:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        used_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        free:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        free_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        free_disk_percent:
          $ref: '_common.yaml#/components/schemas/PercentageNumber'
        used_disk_percent:
          $ref: '_common.yaml#/components/schemas/PercentageNumber'
      required:
        - free_bytes
        - free_disk_percent
        - path
        - total_bytes
        - used_bytes
        - used_disk_percent
    ReservedSize:
      type: object
      properties:
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        path:
          type: string
        total:
          type: integer
          format: int64
        shards:
          type: array
          items:
            type: string
      required:
        - node_id
        - path
        - shards
        - total
    CurrentNode:
      type: object
      properties:
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        attributes:
          type: object
          additionalProperties:
            type: string
        transport_address:
          $ref: '_common.yaml#/components/schemas/TransportAddress'
        weight_ranking:
          type: integer
          format: int32
      required:
        - attributes
        - id
        - name
        - transport_address
        - weight_ranking
    NodeAllocationExplanation:
      type: object
      properties:
        deciders:
          type: array
          items:
            $ref: '#/components/schemas/AllocationDecision'
        node_attributes:
          type: object
          additionalProperties:
            type: string
        node_decision:
          $ref: '#/components/schemas/Decision'
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        node_name:
          $ref: '_common.yaml#/components/schemas/Name'
        store:
          $ref: '#/components/schemas/AllocationStore'
        transport_address:
          $ref: '_common.yaml#/components/schemas/TransportAddress'
        weight_ranking:
          type: integer
          format: int32
      required:
        - deciders
        - node_attributes
        - node_decision
        - node_id
        - node_name
        - transport_address
    AllocationStore:
      type: object
      properties:
        allocation_id:
          type: string
        found:
          type: boolean
        in_sync:
          type: boolean
        matching_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        matching_sync_id:
          type: boolean
        store_exception:
          type: string
      required:
        - allocation_id
        - found
        - in_sync
        - matching_size_in_bytes
        - matching_sync_id
        - store_exception
    UnassignedInformation:
      type: object
      properties:
        at:
          $ref: '_common.yaml#/components/schemas/DateTime'
        last_allocation_status:
          type: string
        reason:
          $ref: '#/components/schemas/UnassignedInformationReason'
        details:
          type: string
        failed_allocation_attempts:
          type: integer
          format: int32
        delayed:
          type: boolean
        allocation_status:
          type: string
      required:
        - at
        - reason
    UnassignedInformationReason:
      type: string
      enum:
        - ALLOCATION_FAILED
        - CLUSTER_RECOVERED
        - DANGLING_INDEX_IMPORTED
        - EXISTING_INDEX_RESTORED
        - FORCED_EMPTY_PRIMARY
        - INDEX_CREATED
        - INDEX_REOPENED
        - MANUAL_ALLOCATION
        - NEW_INDEX_RESTORED
        - NODE_LEFT
        - PRIMARY_FAILED
        - REALLOCATED_REPLICA
        - REINITIALIZED
        - REPLICA_ADDED
        - REROUTE_CANCELLED
