openapi: 3.1.0
info:
  title: Schemas of cluster.allocation_explain category
  description: Schemas of cluster.allocation_explain category
  version: 1.0.0
paths: {}
components:
  schemas:
    Decision:
      type: string
      enum:
        - yes
        - no
        - worse_balance
        - throttled
        - awaiting_info
        - allocation_delayed
        - no_valid_shard_copy
        - no_attempt
    AllocationDecision:
      type: object
      properties:
        decider:
          type: string
        decision:
          $ref: '#/components/schemas/AllocationExplainDecision'
        explanation:
          type: string
      required:
        - decider
        - decision
        - explanation
    AllocationExplainDecision:
      type: string
      enum:
        - NO
        - YES
        - THROTTLE
        - ALWAYS
    ClusterInfo:
      type: object
      properties:
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NodeDiskUsage'
        shard_sizes:
          type: object
          additionalProperties:
            type: number
        shard_data_set_sizes:
          type: object
          additionalProperties:
            type: string
        shard_paths:
          type: object
          additionalProperties:
            type: string
        reserved_sizes:
          type: array
          items:
            $ref: '#/components/schemas/ReservedSize'
      required:
        - nodes
        - shard_sizes
        - shard_paths
        - reserved_sizes
    NodeDiskUsage:
      type: object
      properties:
        node_name:
          $ref: '_common.yaml#/components/schemas/Name'
        least_available:
          $ref: '#/components/schemas/DiskUsage'
        most_available:
          $ref: '#/components/schemas/DiskUsage'
      required:
        - node_name
        - least_available
        - most_available
    DiskUsage:
      type: object
      properties:
        path:
          type: string
        total_bytes:
          type: number
        used_bytes:
          type: number
        free_bytes:
          type: number
        free_disk_percent:
          type: number
        used_disk_percent:
          type: number
      required:
        - path
        - total_bytes
        - used_bytes
        - free_bytes
        - free_disk_percent
        - used_disk_percent
    ReservedSize:
      type: object
      properties:
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        path:
          type: string
        total:
          type: number
        shards:
          type: array
          items:
            type: string
      required:
        - node_id
        - path
        - total
        - shards
    CurrentNode:
      type: object
      properties:
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        attributes:
          type: object
          additionalProperties:
            type: string
        transport_address:
          $ref: '_common.yaml#/components/schemas/TransportAddress'
        weight_ranking:
          type: number
      required:
        - id
        - name
        - attributes
        - transport_address
        - weight_ranking
    NodeAllocationExplanation:
      type: object
      properties:
        deciders:
          type: array
          items:
            $ref: '#/components/schemas/AllocationDecision'
        node_attributes:
          type: object
          additionalProperties:
            type: string
        node_decision:
          $ref: '#/components/schemas/Decision'
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        node_name:
          $ref: '_common.yaml#/components/schemas/Name'
        store:
          $ref: '#/components/schemas/AllocationStore'
        transport_address:
          $ref: '_common.yaml#/components/schemas/TransportAddress'
        weight_ranking:
          type: number
      required:
        - deciders
        - node_attributes
        - node_decision
        - node_id
        - node_name
        - transport_address
        - weight_ranking
    AllocationStore:
      type: object
      properties:
        allocation_id:
          type: string
        found:
          type: boolean
        in_sync:
          type: boolean
        matching_size_in_bytes:
          type: number
        matching_sync_id:
          type: boolean
        store_exception:
          type: string
      required:
        - allocation_id
        - found
        - in_sync
        - matching_size_in_bytes
        - matching_sync_id
        - store_exception
    UnassignedInformation:
      type: object
      properties:
        at:
          $ref: '_common.yaml#/components/schemas/DateTime'
        last_allocation_status:
          type: string
        reason:
          $ref: '#/components/schemas/UnassignedInformationReason'
        details:
          type: string
        failed_allocation_attempts:
          type: number
        delayed:
          type: boolean
        allocation_status:
          type: string
      required:
        - at
        - reason
    UnassignedInformationReason:
      type: string
      enum:
        - INDEX_CREATED
        - CLUSTER_RECOVERED
        - INDEX_REOPENED
        - DANGLING_INDEX_IMPORTED
        - NEW_INDEX_RESTORED
        - EXISTING_INDEX_RESTORED
        - REPLICA_ADDED
        - ALLOCATION_FAILED
        - NODE_LEFT
        - REROUTE_CANCELLED
        - REINITIALIZED
        - REALLOCATED_REPLICA
        - PRIMARY_FAILED
        - FORCED_EMPTY_PRIMARY
        - MANUAL_ALLOCATION
