openapi: 3.1.0
info:
  title: Schemas of cluster.pending_tasks category
  description: Schemas of cluster.pending_tasks category
  version: 1.0.0
paths: {}
components:
  schemas:
    PendingTask:
      type: object
      properties:
        executing:
          description: Indicates whether the pending tasks are currently executing or not.
          type: boolean
        insert_order:
          description: The number that represents when the task has been inserted into the task queue.
          type: number
        priority:
          description: >-
            The priority of the pending task.

            The valid priorities in descending priority order are: `IMMEDIATE` > `URGENT` > `HIGH` > `NORMAL` > `LOW` > `LANGUID`.
          type: string
        source:
          description: A general description of the cluster task that may include a reason and origin.
          type: string
        time_in_queue:
          $ref: '_common.yaml#/components/schemas/Duration'
        time_in_queue_millis:
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
      required:
        - executing
        - insert_order
        - priority
        - source
        - time_in_queue_millis
