openapi: 3.1.0
info:
  title: Schemas of Decommission Awareness.
  description: Schemas of decommission awareness category.
  version: 1.0.0
paths: {}
components:
  schemas:
    DecommissionStatusResponse:
      oneOf:
        - $ref: '#/components/schemas/ZoneDecommissionStatusResponse'
    ZoneDecommissionStatusResponse:
      type: object
      additionalProperties:
        type: string
        enum:
          - DRAINING
          - FAILED
          - INIT
          - IN_PROGRESS
          - SUCCESSFUL
