openapi: 3.0.3
info:
  title: Schemas of `flow_framework.common` Category
  description: Schemas of `flow_framework.common` category.
  version: 1.0.0
paths: { }
components:
  schemas:
    AllowDelete:
      description: Specifies whether to allow deletion of resources with potential data loss.
      type: string
    WorkflowID:
      type: string
      description: The ID of the workflow.
    WorkflowIDResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow.
    WorkflowStepName:
      type: string
      description: The name of the workflow step.
    Provision:
      description: Whether to provision the workflow as part of the request.
      type: boolean
      default: false
    Reprovision:
      type: boolean
      default: false
      description: Whether to reprovision an existing workflow.
    UseCase:
      type: string
      description: The workflow template to use.
    Validation:
      description: Specifies the validation type. Valid values are `all` (validate the template) and `none` (do not validate the template).
      type: string
      default: all
    UpdateFields:
      description: Whether to update only the fields included in the request body..
      type: boolean
      default: false
    All:
      description: Whether to return all fields in the response.
      type: boolean
      default: false
    FlowFrameworkCreate:
      type: object
      properties:
        name:
          type: string
          description: The name of the workflow.
        description:
          type: string
          description: A description of the workflow.
        use_case:
          type: string
          description: A use case ID, which can be used with the Search Workflow API to find related workflows.
        version:
          $ref: '#/components/schemas/version'
        workflows:
          type: object
          description: A map of workflows. Presently, only the provision key is supported. The value for the workflow key is a key-value map that includes fields for `user_params` and lists of nodes and edges.
      required:
        - name
    FlowFrameworkUpdate:
      type: object
      properties:
        name:
          type: string
          description: The name of the workflow.
        description:
          type: string
          description: A description of the workflow.
        use_case:
          type: string
          description: A use case ID, which can be used with the Search Workflow API to find related workflows.
        workflows:
          type: object
        version:
          $ref: '#/components/schemas/version'
      minProperties: 1
    FlowFrameworkGetResponse:
      type: object
      properties:
        name:
          type: string
          description: The name of the workflow.
        version:
          $ref: '#/components/schemas/version'
        description:
          type: string
          description: The description of the workflow.
        use_case:
          type: string
          description: A use case ID, which can be used with the Search Workflow API to find related workflows.
        workflows:
          type: object
        user:
          $ref: '#/components/schemas/user'
        created_time:
          type: integer
          description: When the workflow was created.
        last_updated_time:
          type: integer
          description: When the workflow was last updated.
        last_provisioned_time:
          type: number
          description: When the workflow was last provisioned.
    version:
      type: object
      description: A key-value map with two fields, template, which identifies the template version, and compatibility, which identifies a list of minimum required OpenSearch versions.
      properties:
        template:
          type: string
          description: The template version of the workflow.
        compatibility:
          type: array
          items:
            type: string
          description: A list of minimum required OpenSearch versions.
    shards:
      type: object
      properties:
        total:
          type: integer
          description: The total number of shards involved in the deletion.
        successful:
          type: integer
          description: The number of shards where the deletion was successful.
        failed:
          type: integer
          description: The number of shards where the deletion failed.
        skipped:
          type: integer
          description: The number of shards where the deletion was skipped.
    total:
      type: object
      properties:
        value:
          type: integer
          description: The total number of matching documents.
        relation:
          type: string
          description: The relation of the total hits.
    itemsObject:
      type: object
      properties:
        _index:
          type: string
          description: The index name where the document resides.
        _id:
          type: string
          description: The document ID.
        _version:
          type: integer
          description: The version of the document.
        _seq_no:
          type: integer
          description: The sequence number of the document.
        _primary_term:
          type: integer
          description: The primary term of the document.
        _score:
          type: number
          format: float
          description: The score of the search hit.
        _source:
          $ref: '#/components/schemas/FlowFrameworkGetResponse'
    StateItems:
      type: object
      properties:
        _index:
          type: string
          description: The index name where the document resides.
        _id:
          type: string
          description: The document ID.
        _version:
          type: integer
          description: The version of the document.
        _seq_no:
          type: integer
          description: The sequence number of the document.
        _primary_term:
          type: integer
          description: The primary term of the document.
        _score:
          type: number
          format: float
          description: The score of the search hit.
        _source:
          $ref: '#/components/schemas/SearchStateResponse'
    SearchStateResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow.
        provisioning_progress:
          type: string
          description: The current progress status of the provisioning operation.
        state:
          type: string
          description: The current state of the workflow.
        user:
          $ref: '#/components/schemas/user'
        provision_start_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
          description: When the provisioning operation started.
        provision_end_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
          description: When the provisioning operation completed.
        resources_created:
          $ref: '#/components/schemas/ResourcesCreated'
    ResourcesCreated:
      type: object
      properties:
        workflow_step_name:
          type: string
          description: The name of the workflow step.
        workflow_step_id:
          type: string
          description: The unique identifier for the workflow step.
        resource_type:
          type: string
          description: The type of resource created.
        resource_id:
          type: string
          description: The unique identifier for the created resource.
    user:
      type: object
      properties:
        name:
          type: string
          description: The name of the user.
        backend_roles:
          type: array
          description: The list of backend roles assigned to the user.
          items:
            type: string
        roles:
          type: array
          description: The list of roles assigned to the user.
          items:
            type: string
        custom_attribute_names:
          description: The list of custom attributes associated with the user.
          type: array
          items:
            type: string
        user_requested_tenant:
          description: The tenant requested by the user.
          type: string
          nullable: true
    hits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/total'
        max_score:
          oneOf:
            - type: 'null'
            - type: number
              format: float
              description: The maximum score of the search hits.
        hits:
          type: array
          items:
            $ref: '#/components/schemas/itemsObject'
    StateHits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/total'
        max_score:
          oneOf:
            - type: 'null'
            - type: number
              format: float
              description: The maximum score across all search hits.
        hits:
          description: The list of search hits.
          type: array
          items:
            $ref: '#/components/schemas/StateItems'
    WorkflowSteps:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/WorkflowStep'
    WorkflowStep:
      type: object
      description: A map of workflow steps and their configurations.
      properties:
        inputs:
          type: array
          items:
            type: string
          description: The list of required inputs for the workflow step.
        outputs:
          type: array
          items:
            type: string
          description: The list of outputs generated by the workflow step.
        required_plugins:
          type: array
          items:
            type: string
          description: The list of plugins required for the workflow step.
        timeout:
          $ref: '_common.yaml#/components/schemas/Duration'
    WorkFlowStatusDefaultResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow.
        error:
          type: string
          description: The error message if the workflow failed.
          nullable: true
        state:
          type: string
          description: The current state of the workflow.
        resources_created:
          type: array
          items:
            type: string
          description: A list of resources created by the workflow
    WorkFlowStatusFullResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow.
        error:
          type: string
          description: The error message if the workflow failed.
          nullable: true
        state:
          type: string
          description: The current state of the workflow.
          enum:
            - COMPLETED
            - FAILED
            - NOT_STARTED
            - PROVISIONING
        resources_created:
          type: array
          items:
            type: string
          description: A list of resources created by the workflow.
        provisioning_progress:
          type: string
          description: The current progress of the provisioning process.
          nullable: true
        provision_start_time:
          type: string
          format: date-time
          description: When the provisioning process started.
        provision_end_time:
          type: string
          format: date-time
          description: When the provisioning process completed.
        user:
          $ref: '#/components/schemas/user'
        user_outputs:
          type: array
          items:
            type: string
          description: The list of outputs generated by the user.
    UserProvidedSubstitutionExpressions:
      type: object
      description: A map of user-provided substitution expressions and their values.
      additionalProperties:
        type: string
        description: The value for the user-provided substitution expression.
    SearchWorkflowRequest:
      type: object
      properties:
        query:
          $ref: '_common.query_dsl.yaml#/components/schemas/QueryContainer'
          description: The query used to search for workflows.
    WorkflowSearchResponse:
      type: object
      properties:
        took:
          type: integer
          description: The amount of time in milliseconds that the request took to complete.
        timed_out:
          type: boolean
          description: Whether the request timed out.
        _shards:
          $ref: '#/components/schemas/shards'
        hits:
          $ref: '#/components/schemas/hits'
    WorkflowSearchStateResponse:
      type: object
      properties:
        took:
          type: integer
          description: The amount of time in milliseconds that the request took to complete.
        timed_out:
          type: boolean
          description: Whether the request timed out.
        _shards:
          $ref: '#/components/schemas/shards'
        hits:
          $ref: '#/components/schemas/StateHits'