openapi: 3.1.0
info:
  title: Schemas of flow_framework._common category
  description: Schemas of flow_framework._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    FlowFrameworkException:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "This API is disabled. To enable it, set [flow_framework.enabled] to true."
            status:
              type: integer
    BadRequestError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "Only the parameters [param1, param2] are permitted unless the provision parameter is set to true."
            status:
              type: integer
    ConflictError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "You cannot use both the 'provision_workflow' and 'update_workflow_fields' parameters in the same request."
            status:
              type: integer
    MissingParameterError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # eslint-disable-next-line @cspell/spellchecker
              # example: "You cannot use the 'reprovision_workflow' parameter to create a new template."
            status:
              type: integer
    ParameterConflictError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # eslint-disable-next-line @cspell/spellchecker
              # example: "You cannot use the 'reprovision_workflow' and 'use_case' parameters in the same request."
            status:
              type: integer
    WorkFlowIdNullError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "Workflow ID can not be null"
            status:
              type: integer
    WorkflowSaveError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "Failed to save workflow state"
              status:
                type: integer
    MaxWorkflowsLimitError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "Maximum workflows limit reached: 50"
            code:
              type: integer
    TemplateNotFoundError:
      content:
        application/json:
          type: object
          properties:
            message:
              type: string
              # example: "Failed to retrieve template (12345) from global context."
            code:
              type: integer