openapi: 3.0.3
info:
  title: Schemas of flow_framework.common category
  description: Schemas of flow_framework.common category
  version: 1.0.0
paths: { }
components:
  schemas:
    AllowDelete:
      description: Required when deleting resources involves a high potential for data loss.
      type: string
    WorkflowID:
      type: string
    WorkflowIDResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow
    WorkflowStepName:
      type: string
    Provision:
      description: Provision the workflow as part of the request.
      type: boolean
      default: false
    Reprovision:
      type: boolean
      default: false
    UseCase:
      type: string
    Validation:
      description: Validate the workflow. Valid values are all (validate the template) and none (do not validate the template). Default is all.
      type: string
      default: all
    UpdateFields:
      description: Update only the fields included in the request body.
      type: boolean
      default: false
    All:
      description: The all parameter specifies whether the response should return all fields.
      type: boolean
      default: false
    FlowFrameworkCreate:
      type: object
      properties:
        name:
          type: string
          description: The name of the workflow.
        description:
          type: string
          description: A description of the workflow.
        use_case:
          type: string
          description: A use case, which can be used with the Search Workflow API to find related workflows.
        version:
          $ref: '#/components/schemas/version'
        workflows:
          type: object
          description: A map of workflows. Presently, only the provision key is supported. The value for the workflow key is a key-value map that includes fields for user_params and lists of nodes and edges.
      required:
        - name
    FlowFrameworkUpdate:
      type: object
      properties:
        name:
          type: string
          description: The name of the workflow.
        description:
          type: string
          description: A description of the workflow.
        use_case:
          type: string
          description: A use case, which can be used with the Search Workflow API to find related workflows.
        workflows:
          type: object
        version:
          $ref: '#/components/schemas/version'
      minProperties: 1
    FlowFrameworkDeleteResponse:
      type: object
      properties:
        _index:
          type: string
          description: The name of the index where the document was stored.
        _id:
          type: string
          description: The unique identifier of the deleted document.
        _version:
          type: integer
          description: The version of the document after the deletion.
        result:
          type: string
          description: The result of the deletion operation.
          enum: [deleted, not_found]
        _shards:
          $ref: '#/components/schemas/shards'
        _seq_no:
          type: integer
          description: The sequence number assigned to the document after the deletion.
        _primary_term:
          type: integer
          description: The primary term assigned to the document after the deletion.
    FlowFrameworkGetResponse:
      type: object
      properties:
        name:
          type: string
        version:
          $ref: '#/components/schemas/version'
        description:
          type: string
        use_case:
          type: string
        workflows:
          type: object
        user:
          $ref: '#/components/schemas/user'
        created_time:
          type: integer
        last_updated_time:
          type: integer
        last_provisioned_time:
          type: number
    version:
      type: object
      description: A key-value map with two fields, template, which identifies the template version, and compatibility, which identifies a list of minimum required OpenSearch versions.
      properties:
        template:
          type: string
          description: The template version of the workflow.
        compatibility:
          type: array
          items:
            type: string
          description: A list of minimum required OpenSearch versions.
    shards:
      type: object
      properties:
        total:
          type: integer
          description: The total number of shards involved in the deletion.
        successful:
          type: integer
          description: The number of shards where the deletion was successful.
        failed:
          type: integer
          description: The number of shards where the deletion failed.
        skipped:
          type: integer
          description: The number of shards where the deletion was skipped.
    query:
      type: object
      description: The search query to match workflows. Use `match_all` to retrieve all workflows, or `match` to search by specific fields like `use_case`.
      properties:
        match:
          type: object
        match_all:
          type: object
    total:
      type: object
      properties:
        value:
          type: integer
          description: Total number of matching documents.
        relation:
          type: string
          description: The relation of the total hits.
    itemsObject:
      type: object
      properties:
        _index:
          type: string
          description: The index name where the document resides.
        _id:
          type: string
          description: The document ID.
        _version:
          type: integer
          description: The version of the document.
        _seq_no:
          type: integer
          description: The sequence number of the document.
        _primary_term:
          type: integer
          description: The primary term of the document.
        _score:
          type: number
          format: float
          description: The score of the search hit.
        _source:
          $ref: '#/components/schemas/FlowFrameworkGetResponse'
    StateItems:
      type: object
      properties:
        _index:
          type: string
          description: The index name where the document resides.
        _id:
          type: string
          description: The document ID.
        _version:
          type: integer
          description: The version of the document.
        _seq_no:
          type: integer
          description: The sequence number of the document.
        _primary_term:
          type: integer
          description: The primary term of the document.
        _score:
          type: number
          format: float
          description: The score of the search hit.
        _source:
          $ref: '#/components/schemas/SearchStateResponse'
    SearchStateResponse:
      type: object
      properties:
        workflow_id:
          type: string
        provisioning_progress:
          type: string
        state:
          type: string
        user:
          $ref: '#/components/schemas/user'
    user:
      type: object
      properties:
        name:
          type: string
        backend_roles:
          type: array
          items:
            type: string
        roles:
          type: array
          items:
            type: string
        custom_attribute_names:
          type: array
          items:
            type: string
        user_requested_tenant:
          type: string
          nullable: true
    hits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/total'
        max_score:
          oneOf:
            - type: 'null'
            - type: number
              format: float
              description: The maximum score of the search hits.
        hits:
          type: array
          items:
            $ref: '#/components/schemas/itemsObject'
    StateHits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/total'
        max_score:
          oneOf:
            - type: 'null'
            - type: number
              format: float
              description: The maximum score of the search hits.
        hits:
          type: array
          items:
            $ref: '#/components/schemas/StateItems'
    WorkflowSteps:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/WorkflowStep'
    WorkflowStep:
      type: object
      properties:
        inputs:
          type: array
          items:
            type: string
          description: The list of required inputs for the workflow step
        outputs:
          type: array
          items:
            type: string
          description: The list of outputs generated by the workflow step
        required_plugins:
          type: array
          items:
            type: string
          description: The list of plugins required for the workflow step
        timeout:
          $ref: '_common.yaml#/components/schemas/Duration'
    WorkFlowStatusDefaultResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow
        error:
          type: string
          description: Any error state associated with the workflow
          nullable: true
        state:
          type: string
          description: The current state of the workflow
        resources_created:
          type: array
          items:
            type: string
          description: A list of resources created by the workflow
    WorkFlowStatusFullResponse:
      type: object
      properties:
        workflow_id:
          type: string
          description: The ID of the workflow
        error:
          type: string
          description: Any error state associated with the workflow
          nullable: true
        state:
          type: string
          description: The current state of the workflow
          enum:
            - COMPLETED
            - FAILED
            - NOT_STARTED
            - PROVISIONING
        resources_created:
          type: array
          items:
            type: string
          description: A list of resources created by the workflow
        provisioning_progress:
          type: string
          description: The progress of the provisioning process
          nullable: true
        provision_start_time:
          type: string
          format: date-time
          description: The start time of the provisioning process
        provision_end_time:
          type: string
          format: date-time
          description: The end time of the provisioning process
        user:
          $ref: '#/components/schemas/user'
        user_outputs:
          type: array
          items:
            type: string
          description: Outputs generated by the user
    UserProvidedSubstitutionExpressions:
      type: object
      additionalProperties:
        type: string
        description: The value for the user-provided key. Keys represent substitution expressions.
    SearchWorkflowRequest:
      type: object
      properties:
        query:
          $ref: '#/components/schemas/query'
    WorkflowSearchResponse:
      type: object
      properties:
        took:
          type: integer
          description: Time in milliseconds that the request took to complete.
        timed_out:
          type: boolean
          description: Indicates if the request timed out.
        _shards:
          $ref: '#/components/schemas/shards'
        hits:
          $ref: '#/components/schemas/hits'
    WorkflowSearchStateResponse:
      type: object
      properties:
        took:
          type: integer
          description: Time in milliseconds that the request took to complete.
        timed_out:
          type: boolean
          description: Indicates if the request timed out.
        _shards:
          $ref: '#/components/schemas/shards'
        hits:
          $ref: '#/components/schemas/StateHits'