openapi: 3.1.0
info:
  title: Schemas of indices.put_index_template category
  description: Schemas of indices.put_index_template category
  version: 1.0.0
paths: {}
components:
  schemas:
    IndexTemplateMapping:
      type: object
      properties:
        aliases:
          description: |-
            Aliases to add.
            If the index template includes a `data_stream` object, these are data stream aliases.
            Otherwise, these are index aliases.
            Data stream aliases ignore the `index_routing`, `routing`, and `search_routing` options.
          type: object
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/Alias'
        mappings:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
        settings:
          $ref: 'indices._common.yaml#/components/schemas/IndexSettings'
        lifecycle:
          $ref: 'indices._common.yaml#/components/schemas/DataStreamLifecycle'
