openapi: 3.1.0
info:
  title: Schemas of indices.validate_query category
  description: Schemas of indices.validate_query category
  version: 1.0.0
paths: {}
components:
  schemas:
    IndicesValidationExplanation:
      type: object
      properties:
        error:
          type: string
        explanation:
          type: string
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        valid:
          type: boolean
      required:
        - index
        - valid
