openapi: 3.1.0
info:
  title: Schemas of `indices.modify_data_stream` Category
  description: Schemas of `indices.modify_data_stream` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Action:
      description: A single add or remove backing index action for a data stream.
      type: object
      properties:
        add_backing_index:
          $ref: '#/components/schemas/BackingIndexAction'
        remove_backing_index:
          $ref: '#/components/schemas/BackingIndexAction'
      minProperties: 1
      maxProperties: 1
    BackingIndexAction:
      description: The data stream and index targeted by a modify data stream action.
      type: object
      properties:
        data_stream:
          $ref: '_common.yaml#/components/schemas/DataStreamName'
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
      required:
        - data_stream
        - index
