openapi: 3.1.0
info:
  title: Schemas of `indices.validate_query` Category
  description: Schemas of `indices.validate_query` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    IndicesValidationExplanation:
      description: The validation results for an index query.
      type: object
      properties:
        error:
          type: string
          description: The error message if validation failed.
        explanation:
          type: string
          description: The explanation of why the query is valid or invalid.
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        valid:
          type: boolean
          description: Whether the query is valid for the index.
      required:
        - index
        - valid