openapi: 3.1.0
info:
  title: Schemas of `indices.get_field_mapping` Category
  description: Schemas of `indices.get_field_mapping` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    TypeFieldMappings:
      description: The field mapping configuration for a type.
      type: object
      properties:
        mappings:
          type: object
          description: The map of field names to their mapping definitions.
          additionalProperties:
            $ref: '_common.mapping.yaml#/components/schemas/FieldMapping'
      required:
        - mappings