openapi: 3.1.0
info:
  title: Schemas of `indices.simulate_template` Category
  description: Schemas of `indices.simulate_template` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Overlapping:
      description: The configuration for overlapping index templates.
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        index_patterns:
          type: array
          description: The list of index patterns that may overlap with other templates.
          items:
            type: string
      required:
        - index_patterns
        - name
    Template:
      description: The configuration for an index template simulation.
      type: object
      properties:
        aliases:
          type: object
          description: The map of alias names to their configurations.
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/Alias'
        mappings:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
        settings:
          $ref: 'indices._common.yaml#/components/schemas/IndexSettings'
      required:
        - aliases
        - settings