openapi: 3.1.0
info:
  title: Schemas of indices.stats category
  description: Schemas of indices.stats category
  version: 1.0.0
paths: {}
components:
  schemas:
    ShardFileSizeInfo:
      type: object
      properties:
        description:
          type: string
        size:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        average_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        count:
          type: number
      required:
        - description
        - size_in_bytes
    AllIndicesStats:
      type: object
      properties:
        primaries:
          $ref: '#/components/schemas/IndexStats'
        total:
          $ref: '#/components/schemas/IndexStats'
      required:
        - primaries
        - total
    IndicesStats:
      type: object
      properties:
        uuid:
          $ref: '_common.yaml#/components/schemas/Uuid'
        primaries:
          $ref: '#/components/schemas/IndexStats'
        total:
          $ref: '#/components/schemas/IndexStats'
        shards:
          type: object
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/IndexShardStats'
      required:
        - primaries
        - total
        - uuid
    IndexStatsBase:
      type: object
      properties:
        docs:
          $ref: '_common.yaml#/components/schemas/DocStats'
        store:
          $ref: '_common.yaml#/components/schemas/StoreStats'
        indexing:
          $ref: '_common.yaml#/components/schemas/IndexingStats'
        get:
          $ref: '_common.yaml#/components/schemas/GetStats'
        search:
          $ref: '_common.yaml#/components/schemas/SearchStats'
        merges:
          $ref: '_common.yaml#/components/schemas/MergesStats'
        refresh:
          $ref: '_common.yaml#/components/schemas/RefreshStats'
        flush:
          $ref: '_common.yaml#/components/schemas/FlushStats'
        warmer:
          $ref: '_common.yaml#/components/schemas/WarmerStats'
        query_cache:
          $ref: '_common.yaml#/components/schemas/QueryCacheStats'
        fielddata:
          $ref: '_common.yaml#/components/schemas/FielddataStats'
        completion:
          $ref: '_common.yaml#/components/schemas/CompletionStats'
        segments:
          $ref: '_common.yaml#/components/schemas/SegmentsStats'
        translog:
          $ref: '_common.yaml#/components/schemas/TranslogStats'
        request_cache:
          $ref: '_common.yaml#/components/schemas/RequestCacheStats'
        recovery:
          $ref: '_common.yaml#/components/schemas/RecoveryStats'
    IndexStats:
      allOf:
        - $ref: '#/components/schemas/IndexStatsBase'
        - type: object
    IndexShardStats:
      allOf:
        - $ref: '#/components/schemas/IndexStatsBase'
        - type: object
          properties:
            routing:
              $ref: '#/components/schemas/ShardRouting'
            commit:
              $ref: '#/components/schemas/ShardCommit'
            seq_no:
              $ref: '#/components/schemas/ShardSequenceNumber'
            retention_leases:
              $ref: '#/components/schemas/ShardRetentionLeases'
            shard_path:
              $ref: '#/components/schemas/ShardPath'
    Metric:
      type: string
      enum:
        - _all
        - completion
        - docs
        - fielddata
        - flush
        - get
        - indexing
        - merge
        - query_cache
        - recovery
        - refresh
        - request_cache
        - search
        - segments
        - store
        - suggest
        - translog
        - warmer
    ShardCommit:
      type: object
      properties:
        generation:
          type: number
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        num_docs:
          type: number
        user_data:
          type: object
          additionalProperties:
            type: string
      required:
        - generation
        - id
        - num_docs
        - user_data
    ShardPath:
      type: object
      properties:
        data_path:
          type: string
        is_custom_data_path:
          type: boolean
        state_path:
          type: string
      required:
        - data_path
        - is_custom_data_path
        - state_path
    ShardRetentionLeases:
      type: object
      properties:
        primary_term:
          type: number
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        leases:
          type: array
          items:
            $ref: '#/components/schemas/ShardLease'
      required:
        - leases
        - primary_term
        - version
    ShardLease:
      type: object
      properties:
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        retaining_seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        timestamp:
          type: number
        source:
          type: string
      required:
        - id
        - retaining_seq_no
        - source
        - timestamp
    ShardRouting:
      type: object
      properties:
        node:
          type: string
        primary:
          type: boolean
        relocating_node:
          type: ['null', string]
        state:
          $ref: '#/components/schemas/ShardRoutingState'
      required:
        - node
        - primary
        - state
    ShardRoutingState:
      type: string
      enum:
        - INITIALIZING
        - RELOCATING
        - STARTED
        - UNASSIGNED
    ShardSequenceNumber:
      type: object
      properties:
        global_checkpoint:
          type: number
        local_checkpoint:
          type: number
        max_seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
      required:
        - global_checkpoint
        - local_checkpoint
        - max_seq_no
