openapi: 3.1.0
info:
  title: Schemas of `indices.get_alias` Category
  description: Schemas of `indices.get_alias` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    IndexAliases:
      description: The alias configuration for an index.
      type: object
      properties:
        aliases:
          type: object
          description: The map of alias names to their definitions.
          additionalProperties:
            $ref: 'indices._common.yaml#/components/schemas/AliasDefinition'
      required:
        - aliases
