openapi: 3.1.0
info:
  title: Schemas of `indices.get_index_template` Category
  description: Schemas of `indices.get_index_template` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    IndexTemplateItem:
      description: The configuration for an index template item.
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        index_template:
          $ref: 'indices._common.yaml#/components/schemas/IndexTemplate'
      required:
        - index_template
        - name