openapi: 3.1.0
info:
  title: Schemas of `indices.close` Category
  description: Schemas of `indices.close` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    CloseIndexResult:
      description: The result of a close index operation.
      type: object
      properties:
        closed:
          type: boolean
          description: Whether the index was successfully closed.
        shards:
          type: object
          description: The status of individual shards during the close operation.
          additionalProperties:
            $ref: '#/components/schemas/CloseShardResult'
      required:
        - closed
    CloseShardResult:
      description: The result of closing shards in an index.
      type: object
      properties:
        failures:
          type: array
          description: The list of failures that occurred while closing shards.
          items:
            $ref: '_common.yaml#/components/schemas/ShardFailure'
      required:
        - failures