openapi: 3.1.0
info:
  title: Schemas of `indices.shard_stores` Category
  description: Schemas of `indices.shard_stores` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    ShardStoreStatus:
      oneOf:
        - type: string
          const: all
          description: Return all shards, regardless of health status.
        - type: string
          const: green
          description: The primary shard and all replica shards are assigned.
        - type: string
          const: red
          description: The primary shard is unassigned.
        - type: string
          const: yellow
          description: One or more replica shards are unassigned.
    IndicesShardStores:
      type: object
      properties:
        shards:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ShardStoreWrapper'
      required:
        - shards
    ShardStoreWrapper:
      type: object
      properties:
        stores:
          type: array
          items:
            $ref: '#/components/schemas/ShardStore'
      required:
        - stores
    ShardStore:
      type: object
      properties:
        allocation:
          $ref: '#/components/schemas/ShardStoreAllocation'
        allocation_id:
          $ref: '_common.yaml#/components/schemas/Id'
        store_exception:
          $ref: '#/components/schemas/ShardStoreException'
      additionalProperties:
        title: nodes
        $ref: '_common.yaml#/components/schemas/NodeAttributes'
      required:
        - allocation
    ShardStoreAllocation:
      type: string
      enum:
        - primary
        - replica
        - unused
    ShardStoreException:
      type: object
      properties:
        reason:
          type: string
        type:
          type: string
      required:
        - reason
        - type
