openapi: 3.1.0
info:
  title: Schemas of `indices.rollover` Category
  description: Schemas of `indices.rollover` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    RolloverConditions:
      description: The conditions that trigger an index rollover.
      type: object
      properties:
        min_age:
          description: The minimum age of the index before rollover.
          $ref: '_common.yaml#/components/schemas/Duration'
        max_age:
          description: The maximum age of the index before rollover.
          $ref: '_common.yaml#/components/schemas/Duration'
        max_age_millis:
          description: The maximum age in milliseconds of the index before rollover.
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
        min_docs:
          description: The minimum number of documents in the index before rollover.
          type: integer
          format: int64
        max_docs:
          description: The maximum number of documents in the index before rollover.
          type: integer
          format: int64
        max_size:
          description: The maximum size of the index before rollover.
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        max_size_bytes:
          description: The maximum size in bytes of the index before rollover.
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_size:
          description: The minimum size of the index before rollover.
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        min_size_bytes:
          description: The minimum size in bytes of the index before rollover.
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_primary_shard_size:
          description: The maximum size of any primary shard in the index before rollover.
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        max_primary_shard_size_bytes:
          description: The maximum size in bytes of any primary shard in the index before rollover.
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_primary_shard_size:
          description: The minimum size of any primary shard in the index before rollover.
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        min_primary_shard_size_bytes:
          description: The minimum size in bytes of any primary shard in the index before rollover.
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_primary_shard_docs:
          description: The maximum number of documents in any primary shard before rollover.
          type: integer
          format: int64
        min_primary_shard_docs:
          description: The minimum number of documents in any primary shard before rollover.
          type: integer
          format: int64