openapi: 3.1.0
info:
  title: Schemas of `indices.analyze` Category
  description: Schemas of `indices.analyze` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    TextToAnalyze:
      $ref: '_common.yaml#/components/schemas/StringOrStringArray'
    AnalyzeDetail:
      type: object
      properties:
        analyzer:
          $ref: '#/components/schemas/AnalyzerDetail'
        charfilters:
          type: array
          items:
            $ref: '#/components/schemas/CharFilterDetail'
        custom_analyzer:
          type: boolean
        tokenfilters:
          type: array
          items:
            $ref: '#/components/schemas/TokenDetail'
        tokenizer:
          $ref: '#/components/schemas/TokenDetail'
      required:
        - custom_analyzer
    AnalyzerDetail:
      type: object
      properties:
        name:
          type: string
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/ExplainAnalyzeToken'
      required:
        - name
        - tokens
    ExplainAnalyzeToken:
      type: object
      properties:
        bytes:
          type: string
        end_offset:
          type: integer
          format: int32
        keyword:
          type: boolean
        position:
          type: integer
          format: int32
        positionLength:
          type: integer
          format: int32
        start_offset:
          type: integer
          format: int32
        termFrequency:
          type: integer
          format: int32
        token:
          type: string
        type:
          type: string
      required:
        - bytes
        - end_offset
        - position
        - positionLength
        - start_offset
        - termFrequency
        - token
        - type
    CharFilterDetail:
      type: object
      properties:
        filtered_text:
          type: array
          items:
            type: string
        name:
          type: string
      required:
        - filtered_text
        - name
    TokenDetail:
      type: object
      properties:
        name:
          type: string
        tokens:
          type: array
          items:
            $ref: '#/components/schemas/ExplainAnalyzeToken'
      required:
        - name
        - tokens
    AnalyzeToken:
      type: object
      properties:
        end_offset:
          type: integer
          format: int32
        position:
          type: integer
          format: int32
        positionLength:
          type: integer
          format: int32
        start_offset:
          type: integer
          format: int32
        token:
          type: string
        type:
          type: string
      required:
        - end_offset
        - position
        - start_offset
        - token
        - type
