openapi: 3.1.0
info:
  title: Schemas of indices.rollover category
  description: Schemas of indices.rollover category
  version: 1.0.0
paths: {}
components:
  schemas:
    RolloverConditions:
      type: object
      properties:
        min_age:
          $ref: '_common.yaml#/components/schemas/Duration'
        max_age:
          $ref: '_common.yaml#/components/schemas/Duration'
        max_age_millis:
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
        min_docs:
          type: number
        max_docs:
          type: number
        max_size:
          $ref: '_common.yaml#/components/schemas/StorageSize'
        max_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_size:
          $ref: '_common.yaml#/components/schemas/StorageSize'
        min_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_primary_shard_size:
          $ref: '_common.yaml#/components/schemas/StorageSize'
        max_primary_shard_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_primary_shard_size:
          $ref: '_common.yaml#/components/schemas/StorageSize'
        min_primary_shard_size_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_primary_shard_docs:
          type: number
        min_primary_shard_docs:
          type: number
