openapi: 3.1.0
info:
  title: Schemas of indices.resolve_index category
  description: Schemas of indices.resolve_index category
  version: 1.0.0
paths: {}
components:
  schemas:
    ResolveIndexItem:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        aliases:
          type: array
          items:
            type: string
        attributes:
          type: array
          items:
            type: string
        data_stream:
          $ref: '_common.yaml#/components/schemas/DataStreamName'
      required:
        - name
        - attributes
    ResolveIndexAliasItem:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
      required:
        - name
        - indices
    ResolveIndexDataStreamsItem:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/DataStreamName'
        timestamp_field:
          $ref: '_common.yaml#/components/schemas/Field'
        backing_indices:
          $ref: '_common.yaml#/components/schemas/Indices'
      required:
        - name
        - timestamp_field
        - backing_indices
