openapi: 3.1.0
info:
  title: Schemas of `indices.resolve_index` Category
  description: Schemas of `indices.resolve_index` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    ResolveIndexItem:
      description: The resolved information for an index.
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        aliases:
          type: array
          description: The list of aliases associated with the index.
          items:
            type: string
        attributes:
          type: array
          description: The list of index attributes.
          items:
            type: string
        data_stream:
          $ref: '_common.yaml#/components/schemas/DataStreamName'
      required:
        - attributes
        - name
    ResolveIndexAliasItem:
      description: The resolved information for an index alias.
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
      required:
        - indices
        - name
    ResolveIndexDataStreamsItem:
      description: The resolved information for a data stream.
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/DataStreamName'
        timestamp_field:
          $ref: '_common.yaml#/components/schemas/Field'
        backing_indices:
          $ref: '_common.yaml#/components/schemas/Indices'
      required:
        - backing_indices
        - name
        - timestamp_field