openapi: 3.1.0
info:
  title: Schemas of `indices.get_mapping` Category
  description: Schemas of `indices.get_mapping` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    IndexMappingRecord:
      description: The mapping configuration for an index.
      type: object
      properties:
        item:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
        mappings:
          $ref: '_common.mapping.yaml#/components/schemas/TypeMapping'
      required:
        - mappings