openapi: 3.1.0
info:
  title: Schemas of `indices.stats` Category
  description: Schemas of `indices.stats` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    ShardFileSizeInfo:
      type: object
      description: The size information for shard files.
      properties:
        description:
          type: string
          description: The description of the file type.
        size:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
        size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        min_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        max_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        average_size_in_bytes:
          $ref: '_common.yaml#/components/schemas/ByteCount'
        count:
          type: integer
          format: int64
          description: The number of files.
      required:
        - description
        - size_in_bytes
    AllIndicesStats:
      type: object
      description: The statistics for all indexes.
      properties:
        primaries:
          $ref: '#/components/schemas/IndexStats'
        total:
          $ref: '#/components/schemas/IndexStats'
      required:
        - primaries
        - total
    IndicesStats:
      type: object
      description: The statistics for specific indexes.
      properties:
        uuid:
          $ref: '_common.yaml#/components/schemas/Uuid'
        primaries:
          $ref: '#/components/schemas/IndexStats'
        total:
          $ref: '#/components/schemas/IndexStats'
        shards:
          type: object
          description: The statistics for individual shards.
          additionalProperties:
            type: array
            items:
              $ref: '#/components/schemas/IndexShardStats'
      required:
        - primaries
        - total
        - uuid
    IndexStatsBase:
      type: object
      description: The base statistics for an index.
      properties:
        docs:
          $ref: '_common.yaml#/components/schemas/DocStats'
        store:
          $ref: '_common.yaml#/components/schemas/StoreStats'
        indexing:
          $ref: '_common.yaml#/components/schemas/IndexingStats'
        get:
          $ref: '_common.yaml#/components/schemas/GetStats'
        search:
          $ref: '_common.yaml#/components/schemas/SearchStats'
        merges:
          $ref: '_common.yaml#/components/schemas/MergesStats'
        refresh:
          $ref: '_common.yaml#/components/schemas/RefreshStats'
        flush:
          $ref: '_common.yaml#/components/schemas/FlushStats'
        warmer:
          $ref: '_common.yaml#/components/schemas/WarmerStats'
        query_cache:
          $ref: '_common.yaml#/components/schemas/QueryCacheStats'
        fielddata:
          $ref: '_common.yaml#/components/schemas/FielddataStats'
        completion:
          $ref: '_common.yaml#/components/schemas/CompletionStats'
        segments:
          $ref: '_common.yaml#/components/schemas/SegmentsStats'
        translog:
          $ref: '_common.yaml#/components/schemas/TranslogStats'
        request_cache:
          $ref: '_common.yaml#/components/schemas/RequestCacheStats'
        recovery:
          $ref: '_common.yaml#/components/schemas/RecoveryStats'
    IndexStats:
      allOf:
        - $ref: '#/components/schemas/IndexStatsBase'
        - type: object
    IndexShardStatsBase:
      allOf:
        - $ref: '#/components/schemas/IndexStatsBase'
        - type: object
          properties:
            routing:
              $ref: '#/components/schemas/ShardRouting'
            commit:
              $ref: '#/components/schemas/ShardCommit'
            seq_no:
              $ref: '#/components/schemas/ShardSequenceNumber'
            retention_leases:
              $ref: '#/components/schemas/ShardRetentionLeases'
            shard_path:
              $ref: '#/components/schemas/ShardPath'
    IndexShardStats:
      allOf:
        - $ref: '#/components/schemas/IndexShardStatsBase'
        - type: object
          properties: {}
    Metric:
      type: string
      description: The type of statistics to retrieve.
      enum:
        - _all
        - completion
        - docs
        - fielddata
        - flush
        - get
        - indexing
        - merge
        - query_cache
        - recovery
        - refresh
        - request_cache
        - search
        - segments
        - store
        - suggest
        - translog
        - warmer
    ShardCommit:
      type: object
      description: The commit information for a shard.
      properties:
        generation:
          type: integer
          format: int32
          description: The generation number of the commit.
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        num_docs:
          type: integer
          format: int64
          description: The number of documents in the commit.
        user_data:
          type: object
          description: The user-defined data associated with the commit.
          additionalProperties:
            type: string
      required:
        - generation
        - id
        - num_docs
        - user_data
    ShardPath:
      type: object
      description: The path information for a shard.
      properties:
        data_path:
          type: string
          description: The path to the shard's data.
        is_custom_data_path:
          type: boolean
          description: Whether the shard uses a custom data path.
        state_path:
          type: string
          description: The path to the shard's state.
      required:
        - data_path
        - is_custom_data_path
        - state_path
    ShardRetentionLeases:
      type: object
      description: The retention lease information for a shard.
      properties:
        primary_term:
          type: integer
          format: int64
          description: The primary term of the retention leases.
        version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        leases:
          type: array
          description: The list of retention leases.
          items:
            $ref: '#/components/schemas/ShardLease'
      required:
        - leases
        - primary_term
        - version
    ShardLease:
      type: object
      description: The retention lease details.
      properties:
        id:
          $ref: '_common.yaml#/components/schemas/Id'
        retaining_seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        timestamp:
          type: integer
          format: int64
        source:
          type: string
      required:
        - id
        - retaining_seq_no
        - source
        - timestamp
    ShardRouting:
      type: object
      description: The routing information for a shard.
      properties:
        node:
          type: string
          description: The node containing the shard.
        primary:
          type: boolean
          description: Whether this is a primary shard.
        relocating_node:
          type: ['null', string]
          description: The node where the shard is relocating to.
        state:
          $ref: '#/components/schemas/ShardRoutingState'
      required:
        - node
        - primary
        - state
    ShardRoutingState:
      type: string
      description: The state of shard routing.
      enum:
        - INITIALIZING
        - RELOCATING
        - STARTED
        - UNASSIGNED
    ShardSequenceNumber:
      type: object
      description: The sequence number information for a shard.
      properties:
        global_checkpoint:
          type: integer
          format: int64
          description: The global checkpoint for the shard.
        local_checkpoint:
          type: integer
          format: int64
          description: The local checkpoint for the shard.
        max_seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
      required:
        - global_checkpoint
        - local_checkpoint
        - max_seq_no