openapi: 3.1.0
info:
  title: Schemas of `indices.analyze` Category
  description: Schemas of `indices.analyze` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    TextToAnalyze:
      description: The text or array of text to analyze.
      $ref: '_common.yaml#/components/schemas/StringOrStringArray'
    AnalyzeDetail:
      type: object
      description: The detailed analysis results.
      properties:
        analyzer:
          $ref: '#/components/schemas/AnalyzerDetail'
        charfilters:
          type: array
          description: The list of character filter results.
          items:
            $ref: '#/components/schemas/CharFilterDetail'
        custom_analyzer:
          type: boolean
          description: Whether a custom analyzer was used.
        tokenfilters:
          type: array
          description: The list of token filter results.
          items:
            $ref: '#/components/schemas/TokenDetail'
        tokenizer:
          $ref: '#/components/schemas/TokenDetail'
      required:
        - custom_analyzer
    AnalyzerDetail:
      type: object
      description: The analyzer results.
      properties:
        name:
          type: string
          description: The name of the analyzer.
        tokens:
          type: array
          description: The list of tokens produced by the analyzer.
          items:
            $ref: '#/components/schemas/ExplainAnalyzeToken'
      required:
        - name
        - tokens
    ExplainAnalyzeToken:
      type: object
      description: The detailed token information.
      properties:
        bytes:
          type: string
          description: The bytes representation of the token.
        end_offset:
          type: integer
          format: int32
          description: The ending character offset of the token.
        keyword:
          type: boolean
          description: Whether the token is a keyword.
        position:
          type: integer
          format: int32
          description: The position of the token.
        positionLength:
          type: integer
          format: int32
          description: The length of the token position.
        start_offset:
          type: integer
          format: int32
          description: The starting character offset of the token.
        termFrequency:
          type: integer
          format: int32
          description: The frequency of the term.
        token:
          type: string
          description: The token string.
        type:
          type: string
          description: The type of the token.
      required:
        - bytes
        - end_offset
        - position
        - positionLength
        - start_offset
        - termFrequency
        - token
        - type
    CharFilterDetail:
      type: object
      description: The character filter results.
      properties:
        filtered_text:
          type: array
          description: The text after character filtering.
          items:
            type: string
        name:
          type: string
          description: The name of the character filter.
      required:
        - filtered_text
        - name
    TokenDetail:
      type: object
      description: The token filter or tokenizer results.
      properties:
        name:
          type: string
          description: The name of the token filter or tokenizer.
        tokens:
          type: array
          description: The list of tokens produced.
          items:
            $ref: '#/components/schemas/ExplainAnalyzeToken'
      required:
        - name
        - tokens
    AnalyzeToken:
      description: The basic token information.
      type: object
      properties:
        end_offset:
          type: integer
          format: int32
          description: The ending character offset of the token.
        position:
          type: integer
          format: int32
          description: The position of the token.
        positionLength:
          type: integer
          format: int32
          description: The length of the token position.
        start_offset:
          type: integer
          format: int32
          description: The starting character offset of the token.
        token:
          type: string
          description: The token string.
        type:
          type: string
          description: The type of the token.
      required:
        - end_offset
        - position
        - start_offset
        - token
        - type
