openapi: 3.1.0
info:
  title: Schemas of query insights
  description: Schemas of query insights
  version: 1.0.0
paths: {}
components:
  schemas:
    MetricType:
      type: string
      enum:
        - cpu
        - latency
        - memory
    TopQueriesResponse:
      type: object
      properties:
        top_queries:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/TopQuery'
      required:
        - top_queries
    TopQuery:
      type: object
      properties:
        id:
          type: string
        group_by:
          $ref: '#/components/schemas/GroupingType'
        timestamp:
          type: integer
          description: The timestamp of the query execution.
        total_shards:
          type: integer
          description: The total number of shards involved in the query.
        task_resource_usages:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/TaskResourceUsages'
         
        query_hashcode:
          type: string
          description: The hash code of the query.
        labels:
          type: object
          description: Additional labels for the query.
        search_type:
          type: string
          description: The search query type (for example, `query_then_fetch`).
        source:
          type: string
          description: The search request body source associated with the query, serialized as a string.
        node_id:
          type: string
          description: The node ID associated with the query.
        indices:
          type: array
          items:
            type: string
          description: The indexes involved in the query.
        phase_latency_map:
          type: object
        measurements:
          type: object
          $ref: '#/components/schemas/Measurements'
        failed:
          type: boolean
          description: Whether the query failed.
        source_truncated:
          type: boolean
          description: Whether the query source was truncated.
        wlm_group_id:
          type: string
          description: The workload management group ID associated with the query.
        backend_roles:
          type: array
          items:
            type: string
          description: The backend roles of the user who ran the query.
        user_roles:
          type: array
          items:
            type: string
          description: The roles of the user who ran the query.
        username:
          type: string
          description: The name of the user who ran the query.
    GroupingType:
      type: string
      enum:
        - NONE
        - SIMILARITY
        - none
        - similarity
    TaskResourceUsages:
      type: object
      properties:
        action:
          type: string
          description: The action type of the task.
        taskId:
          type: integer
          description: The task ID.
        parentTaskId:
          type: integer
          description: The parent task ID.
        nodeId:
          type: string
          description: The node ID where the task was executed.
        taskResourceUsage:
          type: object
          $ref: '#/components/schemas/TaskResourceUsage'
    TaskResourceUsage:
      type: object
      properties:
        cpu_time_in_nanos:
          type: integer
          description: The CPU time used in nanoseconds.
        memory_in_bytes:
          type: integer
          description: The memory usage in bytes.
    Measurement:
      type: object
      properties:
        number:
          type: integer
        count:
          type: integer
        aggregationType:
          type: string
    Measurements:
      type: object
      properties:
        latency:
          type: object
          $ref: '#/components/schemas/Measurement'
        cpu:
          type: object
          $ref: '#/components/schemas/Measurement'
        memory:
          type: object
          $ref: '#/components/schemas/Measurement'