openapi: 3.1.0
info:
  title: Schemas of ism._common Category
  description: This document defines schemas for the `ism._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Metadata:
      type: object
      properties:
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _primary_term:
          type: number
          description: The primary term of the document.
        _seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        _version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
    Policy:
      type: object
      description: The policy defines how an index is managed throughout its lifetime.
      properties:
        policy_id:
          type: string
          description: The unique identifier for the policy.
        description:
          type: string
          description: The description of the policy.
        last_updated_time:
          type: integer
          description: When the policy was last updated.
        schema_version:
          type: number
          description: The version of the policy schema.
        error_notification:
          oneOf:
            - $ref: '#/components/schemas/ErrorNotification'
            - type: 'null'
          description: The configuration for error notifications.
        default_state:
          type: string
          description: The default state an index is in.
        states:
          type: array
          description: The list of states for the index to transition between.
          items:
            $ref: '#/components/schemas/States'
        ism_template:
          oneOf:
            - $ref: '#/components/schemas/IsmTemplate'
            - type: 'null'
            - type: array
              items:
                $ref: '#/components/schemas/IsmTemplate'
          description: The ISM template configuration.
    PolicyWithMetadata:
      type: object
      allOf:
        - $ref: '#/components/schemas/Metadata'
        - $ref: '#/components/schemas/PolicyEnvelope'
    States:
      type: object
      description: The list of actions to perform and transitions to enter a new state.
      properties:
        name:
          type: string
          description: The name of the state.
        actions:
          type: array
          description: The list of actions to perform.
          items:
            $ref: '#/components/schemas/Action'
        transitions:
          type: array
          description: The list of transitions to enter a new state.
          items:
            $ref: '#/components/schemas/Transition'
    Action:
      type: object
      description: An action to perform.
      properties:
        timeout:
          $ref: '#/components/schemas/ActionTimeout'
          description: The amount of time to wait before the action fails.
        retry:
          $ref: '#/components/schemas/ActionRetry'
          description: The number of times to retry the action.
        alias:
          $ref: '#/components/schemas/ActionAlias'
          description: Adds or removes an index alias.
        delete:
          $ref: '#/components/schemas/ActionDelete'
          description: Deletes an index.
        force_merge:
          $ref: '#/components/schemas/ActionForceMerge'
          description: Force merges an index.
        read_only:
          $ref: '#/components/schemas/ActionReadOnly'
          description: Changes the index permissions to read-only.
        read_write:
          $ref: '#/components/schemas/ActionReadWrite'
          description: Changes the index permissions to read-write.
        replica_count:
          $ref: '#/components/schemas/ActionReplicaCount'
          description: The number of replicas for the index.
        index_priority:
          $ref: '#/components/schemas/ActionIndexPriority'
          description: The priority level of the index.
        close:
          $ref: '#/components/schemas/ActionClose'
          description: Closes an index.
        open:
          $ref: '#/components/schemas/ActionOpen'
          description: Opens an index.
        snapshot:
          $ref: '#/components/schemas/ActionSnapshot'
          description: Takes a snapshot of the index.
        rollover:
          $ref: '#/components/schemas/ActionRollover'
          description: Sets a rollover policy for the index.
        notification:
          $ref: '#/components/schemas/ActionNotification'
          description: Sets a policy which determines when to send a notification regarding the index.
        allocation:
          $ref: '#/components/schemas/ActionAllocation'
          description: Sets the allocations settings for index.
        rollup:
          $ref: '#/components/schemas/ActionRollup'
          description: Determines when to perform an index rollup.
        transform:
          $ref: '#/components/schemas/ActionTransform'
          description: Determines when to perform an index transform.
        shrink:
          $ref: '#/components/schemas/ActionShrink'
          description: Determines when to shrink the index.
        custom:
          $ref: '#/components/schemas/ActionCustom'
          description: Enables custom operations to be performed on the index.
    ActionTimeout:
      type: object
      properties:
        timeout:
          type: object
          description: The timeout configuration for the action.
    ActionRetry:
      type: object
      properties:
        count:
          type: integer
          description: The number of retry attempts.
        backoff:
          type: string
          description: The backoff strategy for retries.
        delay:
          type: string
          description: The delay between retry attempts.
    ActionAlias:
      type: object
      properties:
        actions:
          type: object
          additionalProperties: true
          description: The alias actions to perform.
    ActionDelete:
      type: object
      description: The delete action configuration.
    ActionForceMerge:
      type: object
      properties:
        max_num_segments:
          type: integer
          description: The maximum number of segments to merge to.
    ActionReadOnly:
      type: object
      description: The read-only action configuration.
    ActionReadWrite:
      type: object
      description: The read-write action configuration.
    ActionReplicaCount:
      type: object
      properties:
        number_of_replicas:
          type: number
          description: The number of replicas to set.
    ActionIndexPriority:
      type: object
      properties:
        priority:
          type: number
          description: The priority to set for the index.
    ActionClose:
      type: object
      description: The close action configuration.
    ActionOpen:
      type: object
      description: The open action configuration.
    ActionSnapshot:
      type: object
      properties:
        repository:
          type: string
          description: The repository to store the snapshot.
        snapshot:
          type: string
          description: The name of the snapshot.
        include_global_state:
          type: boolean
          description: Whether to include the global state in the snapshot.
    ActionRollover:
      type: object
      properties:
        min_size:
          type: number
          description: The minimum size to trigger rollover.
        min_index_age:
          type: number
          description: The minimum index age to trigger rollover.
        min_doc_count:
          type: number
          description: The minimum document count to trigger rollover.
        min_primary_shard_size:
          type: number
          description: The minimum primary shard size to trigger rollover.
        copy_alias:
          type: boolean
          description: Whether to copy the alias to the new index.
    ActionNotification:
      type: object
      additionalProperties: true
      description: The notification action configuration.
    ActionAllocation:
      type: object
      properties:
        require:
          type: object
          additionalProperties: true
          description: The required allocation attributes.
        include:
          type: object
          additionalProperties: true
          description: The included allocation attributes.
        exclude:
          type: object
          additionalProperties: true
          description: The excluded allocation attributes.
        wait_for:
          type: boolean
          description: Whether to wait for the allocation to complete.
    ActionRollup:
      type: object
      additionalProperties: true
      description: The rollup action configuration.
    ActionTransform:
      type: object
      additionalProperties: true
      description: The transform action configuration.
    ActionShrink:
      type: object
      additionalProperties: true
      description: The shrink action configuration.
    ActionCustom:
      type: object
      additionalProperties: true
      description: The custom action configuration.
    Transition:
      type: object
      description: A transition into a new state.
      properties:
        state_name:
          type: string
          description: The name of the state to transition to.
        conditions:
          type: object
          additionalProperties: true
          description: The conditions for the transition.
    GetPoliciesResponse:
      type: object
      properties:
        total_policies:
          type: number
          description: The total number of policies.
        policies:
          type: array
          items:
            $ref: '#/components/schemas/PolicyWithMetadata'
          description: The list of policies.
    GetPolicyResponse:
      $ref: '#/components/schemas/PolicyWithMetadata'
    PutPolicyResponse:
      allOf:
        - $ref: '#/components/schemas/Metadata'
        - type: object
          properties:
            policy:
              $ref: '#/components/schemas/PolicyEnvelope'
    DeletePolicyResponse:
      $ref: '_common.yaml#/components/schemas/WriteResponseBase'
    ChangeResponse:
      type: object
      properties:
        updated_indices:
          type: number
          description: The number of updated indices.
        failures:
          type: boolean
          description: Whether there were any failures.
        failed_indices:
          type: array
          items:
            $ref: '#/components/schemas/FailedIndex'
          description: The list of indices that failed to update.
    ChangePolicyResponse:
      $ref: '#/components/schemas/ChangeResponse'
    FailedIndex:
      type: object
      properties:
        index_name:
          type: string
          description: The name of the failed index.
        index_uuid:
          type: string
          description: The UUID of the failed index.
        reason:
          type: string
          description: The reason for the failure.
    RemovePolicyResponse:
      $ref: '#/components/schemas/ChangePolicyResponse'
    AddPolicyResponse:
      $ref: '#/components/schemas/ChangePolicyResponse'
    PolicyEnvelope:
      type: object
      properties:
        policy:
          $ref: '#/components/schemas/Policy'
    PutPolicyRequest:
      $ref: '#/components/schemas/PolicyEnvelope'
    AddPolicyRequest:
      type: object
      properties:
        policy_id:
          type: string
          description: The ID of the policy to add.
      required:
        - policy_id
    ChangePolicyRequest:
      type: object
      properties:
        policy_id:
          type: string
          description: The ID of the new policy.
        state:
          type: string
          description: The state to transition to.
        include:
          type: array
          items:
            $ref: '#/components/schemas/IncludeState'
          description: The states to include in the policy change.
      required:
        - policy_id
    IncludeState:
      type: object
      properties:
        state:
          type: string
          description: The name of the state to include.
    ExplainIndexResponse:
      type: object
      properties:
        total_managed_indices:
          type: number
          description: The total number of managed indices.
      additionalProperties:
        $ref: '#/components/schemas/ExplainPolicy'
    ExplainPolicy:
      type: object
      properties:
        index.plugins.index_state_management.policy_id:
          type: ['null', string]
          description: The ID of the policy applied to the index.
        index.opendistro.index_state_management.policy_id:
          type: ['null', string]
          description: The ID of the OpenDistro policy applied to the index.
        enabled:
          type: [boolean, 'null']
          description: Whether the policy is enabled for the index.
    ErrorNotification:
      type: object
      properties:
        destination:
          $ref: '#/components/schemas/ErrorNotificationDestination'
        channel:
          $ref: '#/components/schemas/Channel'
        message_template:
          type: object
          additionalProperties: true
          description: The template for error notification messages.
    Channel:
      type: object
      properties:
        id:
          type: string
          description: The ID of the notification channel.
    ErrorNotificationDestination:
      type: object
      properties:
        name:
          type: string
          description: The name of the notification destination.
        last_update_time:
          type: integer
          description: When the notification destination was last updated.
      additionalProperties:
        anyOf:
          - $ref: '#/components/schemas/ErrorNotificationChime'
          - $ref: '#/components/schemas/ErrorNotificationSlack'
    ErrorNotificationChime:
      type: object
      properties:
        url:
          type: string
          description: The URL for the Chime webhook.
    ErrorNotificationSlack:
      type: object
      properties:
        url:
          type: string
          description: The URL for the Slack webhook.
        custom_webhook:
          $ref: '#/components/schemas/SlackCustomWebhook'
    SlackCustomWebhook:
      type: object
      properties:
        url:
          type: string
          description: The URL for the custom Slack webhook.
        scheme:
          type: string
          description: The scheme for the custom Slack webhook.
        host:
          type: string
          description: The host for the custom Slack webhook.
        port:
          type: integer
          description: The port for the custom Slack webhook.
        path:
          type: string
          description: The path for the custom Slack webhook.
        query_params:
          type: object
          additionalProperties: true
          description: The query parameters for the custom Slack webhook.
        header_params:
          type: object
          additionalProperties: true
          description: The header parameters for the custom Slack webhook.
        username:
          type: string
          description: The username for the custom Slack webhook.
        password:
          type: string
          description: The password for the custom Slack webhook.
    IsmTemplate:
      type: object
      properties:
        index_patterns:
          type: array
          items:
            type: string
          description: The index patterns for the ISM template.
        priority:
          type: number
          description: The priority of the ISM template.
        last_updated_time:
          type: integer
          description: When the ISM template was last updated.
    RetryIndexRequest:
      type: object
      properties:
        state:
          type: string
          description: The state to retry.
      required:
        - state
    RetryIndexResponse:
      $ref: '#/components/schemas/ChangeResponse'
    RefreshSearchAnalyzersResponse:
      type: object
      properties:
        _shards:
          $ref: '_common.yaml#/components/schemas/ShardStatistics'
        successful_refresh_details:
          type: array
          items:
            $ref: '#/components/schemas/RefreshSearchAnalyzersResponseDetails'
          description: The details of successful analyzer refreshes.
    RefreshSearchAnalyzersResponseDetails:
      type: object
      properties:
        index:
          type: string
          description: The name of the index.
        refreshed_analyzers:
          type: array
          items:
            type: string
          description: The list of refreshed analyzers.