openapi: 3.1.0
info:
  title: Schemas of knn._common category
  description: Schemas of knn._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    DefaultOperator:
      type: string
      description: The default operator for query string query (AND or OR).
      enum:
        - AND
        - OR
    SearchType:
      type: string
      description: Search operation type.
      enum:
        - query_then_fetch
        - dfs_query_then_fetch
    SuggestMode:
      type: string
      description: Specify suggest mode.
      enum:
        - missing
        - popular
        - always
