openapi: 3.1.0
info:
  title: Schemas of `knn._common` Category
  description: Schemas of `knn._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    Stats:
      type: object
      properties:
        _nodes:
          $ref: '_common.yaml#/components/schemas/NodeStatistics'
        cluster_name:
          $ref: '_common.yaml#/components/schemas/Name'
        stores:
          $ref: '#/components/schemas/StoreStats'
        status:
          type: string
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NodeStats'
    StoreStats:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/StoreStat'
    StoreStat:
      type: object
      properties:
        model_count:
          type: integer
        featureset_count:
          type: integer
        feature_count:
          type: integer
        status:
          type: string
    NodeStats:
      type: object
      properties:
        cache:
          $ref: '#/components/schemas/CacheStats'
        request_total_count:
          type: integer
        request_error_count:
          type: integer
    CacheStats:
      type: object
      properties:
        feature:
          $ref: '#/components/schemas/CacheStat'
        featureset:
          $ref: '#/components/schemas/CacheStat'
        model:
          $ref: '#/components/schemas/CacheStat'
    CacheStat:
      type: object
      properties:
        eviction_count:
          type: integer
        miss_count:
          type: integer
        entry_count:
          type: integer
        memory_usage_in_bytes:
          type: integer
        hit_count:
          type: integer
