openapi: 3.1.0
info:
  title: Schemas of `ltr._common` Category
  description: Schemas of `ltr._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    StoreDetails:
      type: object
      properties:
        store:
          type: string
          description: The name of the store.
        index:
          type: string
          description: The index name for this store.
        version:
          type: integer
          description: Store version.
        counts:
          type: object
          description: Count statistics for this store.
      
    ListStoresResponse:
      type: object
      properties:
        stores:
          type: object
          description: Map of available feature stores.
          additionalProperties:
            $ref: '#/components/schemas/StoreDetails'
      required: [stores]
    StoreExistsResponse:
      type: object
      properties:
        exists:
          type: boolean
          description: Indicates whether the store exists.
    AcknowledgedResponse:
      type: object
      properties:
        acknowledged:
          type: boolean
          description: Indicates whether the request was acknowledged.
        shards_acknowledged:
          type: boolean
          description: Indicates whether the required active shards were acknowledged.
        index:
          type: string
          description: The name of the index.
    Stats:
      type: object
      properties:
        _nodes:
          $ref: '_common.yaml#/components/schemas/NodeStatistics'
        cluster_name:
          $ref: '_common.yaml#/components/schemas/Name'
        stores:
          $ref: '#/components/schemas/StoreStats'
        status:
          type: string
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NodeStats'
    StoreStats:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/StoreStat'
    StoreStat:
      type: object
      properties:
        model_count:
          type: integer
        featureset_count:
          type: integer
        feature_count:
          type: integer
        status:
          type: string
    NodeStats:
      type: object
      properties:
        cache:
          $ref: '#/components/schemas/CacheStats'
        request_total_count:
          type: integer
        request_error_count:
          type: integer
    CacheStats:
      type: object
      properties:
        feature:
          $ref: '#/components/schemas/CacheStat'
        featureset:
          $ref: '#/components/schemas/CacheStat'
        model:
          $ref: '#/components/schemas/CacheStat'
    CacheStat:
      type: object
      properties:
        eviction_count:
          type: integer
        miss_count:
          type: integer
        entry_count:
          type: integer
        memory_usage_in_bytes:
          type: integer
        hit_count:
          type: integer
