openapi: 3.1.0
info:
  title: Schemas of ml category
  description: Schemas of ml category
  version: 1.0.0
paths: {}
components:
  schemas:
    SearchModelHits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/HitsTotal'
        hits:
          type: array
          items:
            $ref: '#/components/schemas/SearchModelHitsHit'
      required:
        - hits
        - total
    HitsTotal:
      type: object
      properties:
        value:
          type: integer
          description: The total number of hits.
        relation:
          type: string
          description: The relation.
      required:
        - relation
        - value
    SearchModelHitsHit:
      type: object
      properties:
        _index:
          type: string
          description: The index.
        _id:
          type: string
          description: The hit ID.
        model_id:
          type: string
          description: The model ID.
      required:
        - _id
        - model_id      
