openapi: 3.1.0
info:
  title: Schemas of ml category
  description: Schemas of ml category
  version: 1.0.0
paths: {}
components:
  schemas:
    SearchModelsQuery:
      type: object
      properties:
        query:
          type: object
          # TODO: Define the query schema
          description: The query.
        size:
          type: integer
          description: The number of models to return.
      required:
        - query
        - size
    SearchModelsResponse:
      type: object
      properties:
        hits:
          $ref: '#/components/schemas/SearchModelsHits'
      required:
        - hits
    SearchModelsHits:
      type: object
      properties:
        total:
          $ref: '#/components/schemas/HitsTotal'
        hits:
          type: array
          items:
            $ref: '#/components/schemas/SearchModelsHitsHit'
      required:
        - hits
        - total
    HitsTotal:
      type: object
      properties:
        value:
          type: integer
          description: The total number of hits.
        relation:
          type: string
          description: The relation.
      required:
        - relation
        - value
    SearchModelsHitsHit:
      type: object
      properties:
        _index:
          type: string
          description: The index.
        _id:
          type: string
          description: The hit ID.
        model_id:
          type: string
          description: The model ID.
      required:
        - _id
        - model_id
    ModelGroupRegistration:
      type: object
      properties:
        model_group_id:
          type: string
          description: The model group ID.
        status:
          type: string
          description: The status.
      required:
        - model_group_id
        - status
    ModelGroup:
      type: object
      properties:
        name:
          type: string
          description: The model group name.
        latest_version:
          type: integer
          description: The latest version.
        description:
          type: string
          description: The model group description.
        access:
          type: string
          description: The model group access.
        created_time:
          type: integer
          format: int64
        last_updated_time:
          type: integer
          format: int64
      required:
        - access
        - description
        - latest_version
        - name
    Task:
      type: object
      properties:
        model_id:
          type: string
        task_id:
          type: string
        state:
          type: string
          enum:
            - CANCELLED
            - COMPLETED
            - COMPLETED_WITH_ERROR
            - CREATED
            - FAILED
            - RUNNING
        task_type:
          type: string
          description: Task type.
          enum:
            - DEPLOY_MODEL
            - REGISTER_MODEL
        function_name:
          type: string
        worker_node:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/NodeIds'
        create_time:
          type: integer
          format: int64
        last_update_time:
          type: integer
          format: int64
        is_async:
          type: boolean
        error:
          type: string
      required:
        - state
    UndeployModelResponse:
      type: object
      additionalProperties:
        title: nodes
        $ref: '#/components/schemas/UndeployModelNode'
    UndeployModelNode:
      type: object
      properties:
        stats:
          $ref: '#/components/schemas/UndeployModelNodeStats'
    UndeployModelNodeStats:
      type: object
      additionalProperties: true
    CreateConnectorRequest:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: integer
        protocol:
          type: string
        credential:
          $ref: '#/components/schemas/Credential'
        parameters:
          $ref: '#/components/schemas/Parameters'
        client_config:
          $ref: '#/components/schemas/ClientConfig'
        actions:
          type: array
          items:
            $ref: '#/components/schemas/Action'
      required:
        - actions
        - credential
        - description
        - name
        - parameters
        - protocol
        - version
    Credential:
      type: object
      properties:
        access_key:
          type: string
        secret_key:
          type: string
        session_token:
          type: string
      additionalProperties: true
    Parameters:
      type: object
      additionalProperties: true
    ClientConfig:
      type: object
      properties:
        max_connection:
          type: integer
        connection_timeout:
          type: integer
        read_timeout:
          type: integer
        retry_backoff_policy:
          type: string
        max_retry_times:
          type: integer
        retry_backoff_millis:
          type: integer
        retry_timeout_seconds:
          type: integer
    Action:
      type: object
      properties:
        action_type:
          type: string
        method:
          type: string
        headers:
          $ref: '#/components/schemas/Headers'
        url:
          type: string
        request_body:
          type: string
        pre_process_function:
          type: string
        post_process_function:
          type: string
    RegisterAgentsRequest:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        description:
          type: string
        tools:
          type: array
          items:
            $ref: '#/components/schemas/ToolItems'
        parameters:
          $ref: '#/components/schemas/Parameters'
        app_type:
          type: string
        memory:
          $ref: '#/components/schemas/Memory'
        llm:
          $ref: '#/components/schemas/LLM'
      required:
        - name
        - type
    LLM:
      type: object
      properties:
        model_id:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
    Memory:
      type: object
      properties:
        type:
          type: string
    ToolItems:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        parameters:
          $ref: '#/components/schemas/Parameters'
      additionalProperties: true
    Headers:
      type: object
      properties:
        content_type:
          type: string
      additionalProperties: true