openapi: 3.1.0
info:
  title: Schemas of `neural._common` Category
  description: Schemas of `neural._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    NeuralStats:
      oneOf:
        - $ref: '#/components/schemas/NestedNeuralStats'
        - $ref: '#/components/schemas/FlatNeuralStats'
    # Separate schemas for flattened vs unflattened
    NestedNeuralStats:
      type: object
      properties:
        _nodes:
          $ref: '#/components/schemas/NodesInfo'
        cluster_name:
          type: string
        info:
          type: object
          properties:
            cluster_version:
              $ref: '#/components/schemas/InfoStringStat'
            processors:
              type: object
              properties:
                ingest:
                  type: object
                  properties:
                    text_embedding_processors_in_pipelines:
                      $ref: '#/components/schemas/InfoCounterStat'
        all_nodes:
          $ref: '#/components/schemas/NestedNeuralNodeStats'
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/NestedNeuralNodeStats'
    FlatNeuralStats:
      type: object
      properties:
        _nodes:
          $ref: '#/components/schemas/NodesInfo'
        cluster_name:
          type: string
        info:
          type: object
          properties:
            "cluster_version":
              $ref: '#/components/schemas/InfoStringStat'
            "processors.ingest.text_embedding_processors_in_pipelines":
              $ref: '#/components/schemas/InfoCounterStat'
        all_nodes:
          $ref: '#/components/schemas/FlatNeuralNodeStats'
        nodes:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/FlatNeuralNodeStats'
    FlatNeuralNodeStats:
      type: object
      properties:
        "processors.ingest.text_embedding_executions":
          $ref: '#/components/schemas/TimestampedEventCounterStat'
    NestedNeuralNodeStats:
      type: object
      properties:
        processors:
          type: object
          properties:
            ingest:
              type: object
              properties:
                text_embedding_executions:
                  $ref: '#/components/schemas/TimestampedEventCounterStat'
    NodesInfo:
      type: object
      properties:
        total:
          type: integer
        successful:
          type: integer
        failed:
          type: integer
    StatMetadata:
      type: object
      required:
        - value
        - stat_type
      properties:
        value:
          oneOf:
            - type: integer
            - type: string
        stat_type:
          type: string
          enum:
            - info_string
            - info_counter
            - timestamped_event_counter
    # Stat Types
    InfoStringStat:
      oneOf:
        - type: string
        - allOf:
          - $ref: '#/components/schemas/StatMetadata'
          - type: object
            properties:
              stat_type:
                type: string
                const: info_string
    InfoCounterStat:
      oneOf:
        - type: integer
        - allOf:
          - $ref: '#/components/schemas/StatMetadata'
          - type: object
            properties:
              stat_type:
                type: string
                const: info_counter
    TimestampedEventCounterStat:
      oneOf:
        - type: integer
        - allOf:
          - $ref: '#/components/schemas/StatMetadata'
          - type: object
            properties:
              stat_type:
                type: string
                const: timestamped_event_counter
              trailing_interval_value:
                type: integer
              minutes_since_last_event:
                type: integer