openapi: 3.1.0
info:
  title: Schemas of nodes.stats category
  description: Schemas of nodes.stats category
  version: 1.0.0
paths: {}
components:
  schemas:
    Metric:
      type: string
      enum:
        - breaker
        - fs
        - http
        - indices
        - jvm
        - os
        - process
        - thread_pool
        - transport
        - discovery
        - indexing_pressure
        - search_pipeline
        - _all
    IndexMetric:
      type: string
      enum:
        - store
        - indexing
        - get
        - search
        - merge
        - flush
        - refresh
        - query_cache
        - fielddata
        - docs
        - warmer
        - completion
        - segments
        - translog
        - suggest
        - request_cache
        - recovery
        - _all
    ResponseBase:
      allOf:
        - $ref: 'nodes._common.yaml#/components/schemas/NodesResponseBase'
        - type: object
          properties:
            cluster_name:
              $ref: '_common.yaml#/components/schemas/Name'
            nodes:
              type: object
              additionalProperties:
                $ref: 'nodes._common.yaml#/components/schemas/Stats'
          required:
            - nodes
