openapi: 3.1.0
info:
  title: Schemas of nodes.reload_secure_settings category
  description: Schemas of nodes.reload_secure_settings category
  version: 1.0.0
paths: {}
components:
  schemas:
    ResponseBase:
      allOf:
        - $ref: 'nodes._common.yaml#/components/schemas/NodesResponseBase'
        - type: object
          properties:
            cluster_name:
              $ref: '_common.yaml#/components/schemas/Name'
            nodes:
              type: object
              additionalProperties:
                $ref: 'nodes._common.yaml#/components/schemas/NodeReloadResult'
          required:
            - cluster_name
            - nodes
