openapi: 3.1.0
info:
  title: Schemas of `nodes.reload_secure_settings` Category
  description: Schemas of `nodes.reload_secure_settings` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    NodeReloadResponse:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
      required:
        - name
    NodeReloadError:
      allOf:
        - $ref: '#/components/schemas/NodeReloadResponse'
        - type: object
          properties:
            reload_exception:
              $ref: '_common.yaml#/components/schemas/ErrorCause'
    NodeReloadResult:
      anyOf:
        - $ref: '#/components/schemas/NodeReloadResponse'
        - $ref: '#/components/schemas/NodeReloadError'
