openapi: 3.1.0
info:
  title: Schemas of nodes.hot_threads category
  description: Schemas of nodes.hot_threads category
  version: 1.0.0
paths: {}
components:
  schemas:
    HotThread:
      type: object
      properties:
        hosts:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/Host'
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        node_name:
          $ref: '_common.yaml#/components/schemas/Name'
        threads:
          type: array
          items:
            type: string
      required:
        - hosts
        - node_id
        - node_name
        - threads
