openapi: 3.1.0
info:
  title: Schemas of `nodes._common` Category
  description: Schemas of `nodes._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    NodesResponseBase:
      type: object
      properties:
        _nodes:
          description: Contains statistics about the number of nodes selected by the request's node filters.
          $ref: '_common.yaml#/components/schemas/NodeStatistics'
    SampleType:
      type: string
      description: The type to sample.
      enum:
        - block
        - cpu
        - wait
