openapi: 3.1.0
info:
  title: Schemas of notifications._common category
  description: Schemas of notifications._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    DeleteConfigsResponse:
      type: object
      properties:
        delete_response_list:
          $ref: '#/components/schemas/DeleteResponseList'
    DeleteResponseList:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RestStatus'
    GetConfigsResponse:
      type: object
      properties:
        start_index:
          type: integer
          format: int64
        total_hits:
          type: integer
          format: int64
        total_hit_relation:
          $ref: '#/components/schemas/TotalHitRelation'
        config_list:
          type: array
          maxItems: 1
          items:
            $ref: '#/components/schemas/NotificationsConfigsOutputItem'
    RestStatus:
      type: string
      enum:
        - accepted
        - continue
        - created
        - found
        - moved_permanently
        - multi_status
        - multiple_choices
        - no_content
        - non_authoritative_information
        - not_modified
        - ok
        - partial_content
        - reset_content
        - see_other
        - switching_protocols
        - temporary_redirect
        - use_proxy
    NotificationConfigType:
      type: string
      description: Type of notification configuration.
      enum:
        - chime
        - email
        - email_group
        - microsoft_teams
        - ses_account
        - slack
        - smtp_account
        - sns
        - webhook
    TotalHitRelation:
      type: string
      enum:
        - eq
        - gte
    NotificationsConfigsOutputItem:
      type: object
      properties:
        config_id:
          type: string
        last_updated_time_ms:
          type: integer
          format: int64
        created_time_ms:
          type: integer
          format: int64
        config:
          $ref: '#/components/schemas/NotificationsConfigItem'
    NotificationsConfigItem:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        config_type:
          $ref: '#/components/schemas/NotificationConfigType'
        is_enabled:
          type: boolean
        sns:
          $ref: '#/components/schemas/SnsItem'
        slack:
          $ref: '#/components/schemas/SlackItem'
        chime:
          $ref: '#/components/schemas/Chime'
        webhook:
          $ref: '#/components/schemas/Webhook'
        smtp_account:
          $ref: '#/components/schemas/SmtpAccount'
        ses_account:
          $ref: '#/components/schemas/SesAccount'
        email_group:
          $ref: '#/components/schemas/EmailGroup'
        email:
          $ref: '#/components/schemas/Email'
        microsoft_teams:
          $ref: '#/components/schemas/MicrosoftTeamsItem'
      required:
        - config_type
        - name
    SnsItem:
      type: object
      properties:
        topic_arn:
          type: string
        role_arn:
          type: string
      required:
        - topic_arn
    SlackItem:
      type: object
      properties:
        url:
          type: string
      required:
        - url
    Chime:
      type: object
      properties:
        url:
          type: string
      required:
        - url
    Webhook:
      type: object
      properties:
        url:
          type: string
        method:
          $ref: '#/components/schemas/HttpMethodType'
        header_params:
          $ref: '#/components/schemas/HeaderParamsMap'
      required:
        - url
    HttpMethodType:
      type: string
      enum:
        - PATCH
        - POST
        - PUT
    HeaderParamsMap:
      type: object
      additionalProperties:
        type: integer
        format: int32
    SmtpAccount:
      type: object
      properties:
        host:
          type: string
        port:
          type: integer
          format: int32
        method:
          $ref: '#/components/schemas/EmailEncryptionMethod'
        from_address:
          type: string
      required:
        - from_address
        - host
        - method
        - port
    EmailEncryptionMethod:
      type: string
      enum:
        - none
        - ssl
        - start_tls
    SesAccount:
      type: object
      properties:
        region:
          type: string
        role_arn:
          type: string
        from_address:
          type: string
      required:
        - from_address
        - region
    EmailGroup:
      type: object
      properties:
        recipient_list:
          type: array
          items:
            $ref: '#/components/schemas/RecipientListItem'
        email_group_id_list:
          type: array
          items:
            type: string
      required:
        - recipient_list
    RecipientListItem:
      type: object
      properties:
        recipient:
          type: string
    Email:
      type: object
      properties:
        email_account_id:
          type: string
        recipient_list:
          type: array
          items:
            $ref: '#/components/schemas/RecipientListItem'
      required:
        - email_account_id
    MicrosoftTeamsItem:
      type: object
      properties:
        url:
          type: string
      required:
        - url
    NotificationsConfig:
      type: object
      properties:
        config_id:
          type: string
        config:
          $ref: '#/components/schemas/NotificationsConfigItem'
      required:
        - config
    EventSource:
      type: object
      properties:
        title:
          type: string
        reference_id:
          type: string
        severity:
          $ref: '#/components/schemas/SeverityType'
        tags:
          type: array
          items:
            type: string
    SeverityType:
      type: string
      enum:
        - critical
        - high
        - info
    EventStatus:
      type: object
      properties:
        config_id:
          type: string
        config_name:
          type: string
        config_type:
          $ref: '#/components/schemas/NotificationConfigType'
        email_recipient_status:
          type: array
          items:
            $ref: '#/components/schemas/EmailRecipientStatus'
        delivery_status:
          $ref: '#/components/schemas/DeliveryStatus'
    EmailRecipientStatus:
      type: object
      properties:
        recipient:
          type: string
        delivery_status:
          $ref: '#/components/schemas/DeliveryStatus'
    DeliveryStatus:
      type: object
      properties:
        status_code:
          type: string
        status_text:
          type: string
    NotificationsPluginFeaturesMap:
      type: object
      additionalProperties:
        type: string
    NotificationChannel:
      type: object
      properties:
        config_id:
          type: string
        name:
          type: string
        description:
          type: string
        config_type:
          $ref: '#/components/schemas/NotificationConfigType'
        is_enabled:
          type: boolean
