openapi: 3.1.0
info:
  title: Schemas for OpenSearch Query Data Sources API
  description: Schemas for OpenSearch Query Data Sources API
  version: 1.0.0
paths: {}
components:
  schemas:
    DataSourceList:
      type: array
      items:
        $ref: '#/components/schemas/DataSource'

    DataSource:
      type: object
      properties:
        name:
          type: string
          description: The name of the data source.
        description:
          type: string
          description: The description of the data source.
        connector:
          type: string
          description: The connector type for the data source.
        allowedRoles:
          type: array
          items:
            type: string
            description: The roles allowed to access this data source.
        properties:
          type: object
          additionalProperties: true
          description: The configuration properties for the data source.
        resultIndex:
          type: string
          description: The index where query results are stored.
        status:
          type: string
          description: The current status of the data source.
        configuration:
          $ref: '#/components/schemas/DataSourceConfiguration'
      required:
        - connector
        - name
        - properties
        - resultIndex
        - status

    DataSourceConfiguration:
      type: object
      properties:
        endpoint:
          type: string
          description: The connection endpoint for the data source.
        credentials:
          $ref: '#/components/schemas/Credentials'
      required:
        - credentials
        - endpoint

    Credentials:
      type: object
      properties:
        username:
          type: string
          description: The username for authentication.
        password:
          type: string
          description: The username for authentication.
      required:
        - password
        - username

    DataSourceRetrieve:
      type: object
      description: Represents the fundamental reason for an error.
      properties:
        name:
          type: string
          description: The name of the data source.
        description:
          type: string
          description: The description of the data source.
        connector:
          type: string
          description: The connector type for the data source.
        allowedRoles:
          type: array
          items:
            type: string
          description: The roles allowed to access this data source.
        properties:
          type: object
          additionalProperties: true
          description: The configuration properties for the data source.
        resultIndex:
          type: string
          description: The index where query results are stored.
        status:
          type: string
          description: The current status of the data source.
        configuration:
          $ref: '#/components/schemas/DataSourceConfiguration'
      required:
        - connector
        - name
        - properties
        - resultIndex
        - status
