openapi: 3.1.0
info:
  title: Schemas for OpenSearch Query Data Sources API
  description: Schemas for OpenSearch Query Data Sources API
  version: 1.0.0
paths: {}
components:
  schemas:
    DataSourceList:
      type: array
      items:
        $ref: '#/components/schemas/DataSource'

    DataSource:
      type: object
      properties:
        name:
          type: string
          description: The name of the data source.
        description:
          type: string
          description: The description of the data source.
        connector:
          type: string
          description: The connector type for the data source.
        allowedRoles:
          type: array
          items:
            type: string
            description: The roles allowed to access this data source.
        properties:
          type: object
          additionalProperties: true
          description: The configuration properties for the data source.
        resultIndex:
          type: string
          description: The index where query results are stored.
        status:
          type: string
          description: The current status of the data source.
        configuration:
          $ref: '#/components/schemas/DataSourceConfiguration'
      required:
        - connector
        - name
        - properties
        - resultIndex
        - status

    DataSourceConfiguration:
      type: object
      properties:
        endpoint:
          type: string
          description: The connection endpoint for the data source.
        credentials:
          $ref: '#/components/schemas/Credentials'
      required:
        - credentials
        - endpoint

    Credentials:
      type: object
      properties:
        username:
          type: string
          description: The username for authentication.
        password:
          type: string
          description: The username for authentication.
      required:
        - password
        - username

    DataSourceNotFound:
      type: object
      description: Indicates that the requested data source could not be found.
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse'
      required:
        - error

    ErrorResponse:
      type: object
      description: Provides details about an API error.
      properties:
        error:
          $ref: '#/components/schemas/Error'
        status:
          type: number
          description: The HTTP status code for the error.

    Error:
      type: object
      description: Contains detailed information about an error.
      properties:
        root_cause:
          type: array
          items:
            $ref: '#/components/schemas/RootCause'
            description: The underlying causes of the error.
        type:
          type: string
          description: The error type classification.
          # example: status_exception
        reason:
          type: string
          description: The human-readable error message.
          # example: DataSource not found
      required:
        - reason
        - root_cause
        - type

    RootCause:
      type: object
      properties:
        type:
          type: string
          description: The error type classification.
          # example: status_exception
        reason:
          type: string
          description: The human-readable error message.
          # example: DataSource not found
      required:
        - reason
        - type

    DataSourceRetrieve:
      type: object
      description: Represents the fundamental reason for an error.
      properties:
        name:
          type: string
          description: The name of the data source.
        description:
          type: string
          description: The description of the data source.
        connector:
          type: string
          description: The connector type for the data source.
        allowedRoles:
          type: array
          items:
            type: string
          description: The roles allowed to access this data source.
        properties:
          type: object
          additionalProperties: true
          description: The configuration properties for the data source.
        resultIndex:
          type: string
          description: The index where query results are stored.
        status:
          type: string
          description: The current status of the data source.
        configuration:
          $ref: '#/components/schemas/DataSourceConfiguration'
      required:
        - connector
        - name
        - properties
        - resultIndex
        - status
