openapi: 3.1.0
info:
  title: Schemas of query_group._common category
  description: Schemas of query_group._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    QueryGroupResponse:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        updated_at:
          type: integer
          format: int64
        resource_limits:
          anyOf:
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - memory
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - cpu
      required:
        - _id
        - name
        - resiliency_mode
        - updated_at
        - resource_limits
    QueryGroupCreate:
      type: object
      properties:
        name:
          type: string
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        resource_limits:
          anyOf:
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - memory
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - cpu
      required:
        - name
        - resiliency_mode
        - resource_limits
    QueryGroupUpdate:
      type: object
      properties:
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        resource_limits:
          properties:
            memory:
              type: number
              format: double
            cpu:
              type: number
              format: double
