openapi: 3.1.0
info:
  title: Schemas of query_group._common category
  description: Schemas of query_group._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    QueryGroupResponse:
      type: object
      properties:
        name:
          type: string
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        jvm:
          type: number
          format: double
        cpu:
          type: number
          format: double
        updatedAt:
          type: integer
          format: int64
      anyOf:
        - required:
            - jvm
        - required:
            - cpu
      required:
        - name
        - resiliency_mode
        - updatedAt
    QueryGroupCreate:
      type: object
      properties:
        name:
          type: string
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        jvm:
          type: number
          format: double
        cpu:
          type: number
          format: double
      anyOf:
        - required:
            - jvm
        - required:
            - cpu
      required:
        - name
        - resiliency_mode
    QueryGroupUpdate:
      type: object
      properties:
        resiliency_mode:
          type: string
          enum: [ "soft", "enforced", "monitor" ]
        jvm:
          type: number
          format: double
        cpu:
          type: number
          format: double
