openapi: 3.1.0
info:
  title: Schemas of `rollup._common` Category
  description: Schemas of `rollup._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    RollupEntity:
      description: A rollup job entity with metadata.
      type: object
      properties:
        _id:
          $ref: '_common.yaml#/components/schemas/Id'
        _seq_no:
          $ref: '_common.yaml#/components/schemas/SequenceNumber'
        _primary_term:
          type: integer
          format: int64
          description: The primary term of the document.
        _version:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        rollup:
          $ref: '#/components/schemas/Rollup'

    Rollup:
      description: Defines the configuration for a rollup job.
      type: object
      properties:
        rollup_id:
          type: string
          description: The ID for the rollup job.
        enabled:
          type: boolean
          description: Whether the rollup job is enabled.
        schedule:
          $ref: '#/components/schemas/Schedule'
        last_updated_time:
          type: number
          description: When the rollup job was last updated.
        enabled_time:
          type: number
          description: When the rollup job was enabled.
        description:
          type: string
          description: The description of the rollup job.
        schema_version:
          type: number
          description: The schema version for the rollup job.
        source_index:
          type: string
          description: The source index pattern for the rollup job.
        target_index:
          type: string
          description: The target index where rollup results are stored.
        metadata_id:
          type: ['null', string]
          description: The metadata ID associated with the rollup job.
        page_size:
          type: number
          description: The number of documents to process per iteration.
        delay:
          type: number
          description: The time delay in milliseconds between consecutive rollup executions.
        continuous:
          type: boolean
          description: Whether the rollup job runs continuously.
        dimensions:
          type: array
          items:
            $ref: '#/components/schemas/DimensionsConfigItem'
          description: The dimensions to aggregate data in the rollup.
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/MetricsConfigItem'
          description: The metrics to calculate in the rollup.
        error_notification:
          type: string
          description: Set up a Mustache message template for error notifications. For example, if an index rollup job fails, the system can send  a message to a Slack channel.

    ExplainEntities:
      description: Maps rollup IDs to their explanation details.
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Explain'

    Explain:
      description: Provides explanation details for a rollup job.
      type: object
      properties:
        metadata_id:
          type: ['null', string]
          description: The metadata ID for the rollup job.
        rollup_metadata:
          type: ['null', object]
          description: The metadata associated with the rollup job execution.

    DimensionsConfigItem:
      description: Defines a dimension for aggregating data in a rollup job.
      type: object
      properties:
        histogram:
          $ref: '#/components/schemas/HistogramDimension'
        date_histogram:
          $ref: '#/components/schemas/DateHistogramDimension'
        terms:
          $ref: '#/components/schemas/TermsDimension'
      minProperties: 1
      maxProperties: 1

    DateHistogramDimension:
      description: Configures a date histogram dimension for rollup aggregation.
      type: object
      properties:
        fixed_interval:
          type: string
          description: The fixed interval for the date histogram.
        calendar_interval:
          type: string
          description: The calendar interval for the date histogram.
        timezone:
          type: string
          description: The timezone for the date histogram calculations.
        source_field:
          type: string
          description: The field from the source documents to use for the date histogram.
        target_field:
          type: string
          description: The field name to use in the target index for the date histogram results.
        format:
          type: ['null', string]
          description: The date format pattern for the histogram values.

    HistogramDimension:
      description: Configures a numeric histogram dimension for rollup aggregation.
      type: object
      properties:
        source_field:
          type: string
          description: The field from the source documents to use for the histogram.
        target_field:
          type: string
          description: The field name to use in the target index for the histogram results.
        interval:
          type: string
          description: The interval for the histogram buckets.

    TermsDimension:
      description: Configures a terms dimension for rollup aggregation.
      type: object
      properties:
        source_field:
          type: string
          description: The field from the source documents to use for terms aggregation.
        target_field:
          type: string
          description: The field name to use in the target index for the terms aggregation results.

    MetricsConfigItem:
      description: Defines metric aggregations for a field in a rollup job.
      type: object
      properties:
        source_field:
          type: string
          description: The field from the source documents to calculate metrics on.
        target_field:
          type: string
          description: The field name prefix to use in the target index for the metric results.
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/MetricsConfigMetrics'
          description: The list of metrics to calculate for the field.

    MetricsConfigMetrics:
      description: Specifies a metric aggregation type to calculate.
      type: object
      properties:
        avg:
          type: object
          description: Calculates the average value of a field.
        sum:
          type: object
          description: Calculates the sum of values for a field.
        max:
          type: object
          description: Finds the maximum value of a field.
        min:
          type: object
          description: Finds the minimum value of a field.
        value_count:
          type: object
          description: Counts the number of values for a field.
      minProperties: 1
      maxProperties: 1

    Cron:
      description: Defines a cron schedule for the rollup job execution.
      type: object
      properties:
        expression:
          type: string
          description: The cron expression that defines the schedule.
        timezone:
          type: string
          description: The timezone for interpreting the cron expression.

    Schedule:
      description: Defines the execution schedule for a rollup job.
      type: object
      properties:
        interval:
          $ref: '#/components/schemas/Interval'

    Interval:
      description: Specifies the timing details for rollup job execution.
      type: object
      properties:
        start_time:
          type: number
          description: When the rollup job should start, in epoch milliseconds.
        period:
          type: number
          description: The numerical value for the execution interval.
        unit:
          type: string
          description: The time unit for the execution interval, such as `MINUTES` or `HOURS`.
        cron:
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/Cron'
            - $ref: '#/components/schemas/Cron'
          description: The cron schedule configuration for the rollup job.
        schedule_delay:
          type: number
          description: The delay in milliseconds before starting the rollup process.