openapi: 3.1.0
info:
  title: Schemas of Search Relevance
  description: Schemas of Search Relevance.
  version: 1.0.0
paths: {}
components:
  schemas:
    QuerySet:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        sampling:
          type: string
        timestamp:
          type: string
        querySetQueries:
          type: object # TODO: How to test that the output
          # of the querySetQueries is correct because it is object which is dependent
          # on the input to the query set creation prior. 
    Judgment:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
        name:
          type: string
        status:
          type: string
        type:
          type: string
        metadata:
          type: object
        judgmentScores:
          type: object # TODO: How to test that the output
          # of the judgmentScores is correct because it is object which is dependent
          # on the input to the query set creation prior. 
    SearchConfiguration:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        timestamp:
          type: string
        index:
          type: string
        query:
          type: string
        searchPipeline:
          type: string
    Experiment:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
        type:
          type: string
        status:
          type: string
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        judgmentList:
          type: array
          items:
            type: string
        size:
          type: integer
        results:
          type: object
          # TODO: How to test that the output
          # of the results is correct because it is object which is dependent
          # on the input to the query set creation prior. 
    PutExperimentResponse:
      type: object
      properties:
        experiment_id:
          type: string
        experiment_result:
          type: string
    PutSearchConfigurationResponse:
      type: object
      properties:
        search_configuration_id:
          type: string
        search_configuration_result:
          type: string
    PutJudgmentsResponse:
      type: object
      properties:
        judgment_id: 
          type: string
    PostQuerySetsResponse:
      type: object
      properties:
        query_set_id: 
          type: string
        query_set_result:
          type: string
    PutQuerySetsResponse:
      type: object
      properties:
        query_set_id: 
          type: string
        query_set_result:
          type: string
    PutPairwiseExperimentRequest:
      type: object
      description: The schema for a pairwise experiment 
      properties:
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        size:
          type: integer
        type:
          type: string
    PutHybridOptimizerExperimentRequest:
      type: object
      description: The schema for a hybrid optimizer experiment 
      properties:
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        judgmentList:
          type: array
          items:
            type: string
        size:
          type: integer
        type:
          type: string
    PutPointwiseExperimentRequest:
      type: object
      description: The schema for a pointwise experiment 
      properties:
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        judgmentList:
          type: array
          items:
            type: string
        size:
          type: integer
        type:
          type: string
    PostQuerySetsRequest:
      type: object
      description: The schema for creating a query set 
      properties:
        name:
          type: string
        description:
          type: string
        sampling:
          type: string
        querySetSize:
          type: integer
    PutQuerySetsRequest:
      type: object
      description: The schema for updating a query set 
      properties:
        name:
          type: string
        description:
          type: string
        sampling:
          type: string
        querySetQueries:
          type: array
          items:
            type: object
    PutLLMJudgmentsRequest:
      type: object
      description: The schema for a LLM judgment 
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        modelId:
          type: string
        querySetId:
          type: string
        searchConfigurationList:
          type: array
          items:
            type: string
        size:
          type: integer
        ignoreFailure:
          type: boolean
        contextFields:
          type: array
          items:
            type: string
    PutUBIJudgmentsRequest:
      type: object
      description: The schema for a UBI judgment 
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        clickModel:
          type: string
        maxRank:
          type: integer
    PutImportJudgmentsRequest:
      type: object
      description: The schema for an import judgment 
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
        judgmentRatings:
          type: array
          items:
            type: object
    PutSearchConfigurationRequest:
      type: object
      properties:
        name:
          type: string
        index:
          type: string
        query:
          type: string
        searchPipeline:
          type: string
    PostScheduledExperimentsRequest:
      type: object
      description: The schema for scheduling experiments 
      properties:
        experimentId:
          type: string
        cronExpression:
          type: string
    PostScheduledExperimentsResponse:
      type: object
      properties:
        job_id:
          type: string
        job_result:
          type: string
