openapi: 3.1.0
info:
  title: Schemas of security._common category.
  description: Schemas of security._common category.
  version: 1.0.0
paths: {}
components:
  schemas:
    AccountDetails:
      type: object
      properties:
        user_name:
          type: string
        is_reserved:
          type: boolean
        is_hidden:
          type: boolean
        is_internal_user:
          type: boolean
        user_requested_tenant:
          type: string
        backend_roles:
          type: array
          items:
            type: string
        custom_attribute_names:
          type: array
          items:
            type: string
        tenants:
          $ref: '#/components/schemas/UserTenants'
        roles:
          type: array
          items:
            type: string

    ActionGroup:
      type: object
      properties:
        reserved:
          type: boolean
        hidden:
          type: boolean
        allowed_actions:
          type: array
          items:
            type: string
        type:
          type: string
        description:
          type: string
        static:
          type: boolean

    ActionGroupsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/ActionGroup'

    AllowListConfig:
      type: object
      properties:
        config:
          $ref: '#/components/schemas/AllowConfig'

    AllowConfig:
      type: object
      properties:
        enabled:
          type: boolean
        requests:
          type: object
          description: An object with APIs as key and array of http methods as values.

    AuditConfig:
      type: object
      properties:
        compliance:
          $ref: '#/components/schemas/ComplianceConfig'
        enabled:
          type: boolean
        audit:
          $ref: '#/components/schemas/AuditLogsConfig'

    AuditConfigWithReadOnly:
      type: object
      properties:
        _readonly:
          type: array
          items:
            type: string
        config:
          $ref: '#/components/schemas/AuditConfig'

    AuditLogsConfig:
      type: object
      properties:
        ignore_users:
          type: array
          items:
            type: string
        ignore_requests:
          type: array
          items:
            type: string
        disabled_rest_categories:
          type: array
          items:
            type: string
        disabled_transport_categories:
          type: array
          items:
            type: string
        log_request_body:
          type: boolean
        resolve_indices:
          type: boolean
        resolve_bulk_requests:
          type: boolean
        exclude_sensitive_headers:
          type: boolean
        enable_transport:
          type: boolean
        enable_rest:
          type: boolean

    AuthInfo:
      type: object
      properties:
        user:
          type: string
          description: Stringified User object.
        user_name:
          type: string
          description: User's name.
        user_requested_tenant:
          type: string
          description: Name of the tenant the user wants to switch to.
        remote_address:
          type: string
          description: The IP address of remote user.
        backend_roles:
          type: array
          description: Backend roles associated with the user.
        custom_attribute_names:
          type: array
          description: Name of the attributes associated with the user.
        roles:
          type: array
          description: Roles associated with the user.
        tenants:
          type: object
          description: Tenants the user has access to with read-write or read-only access indicator.
        principal:
          type: string
          description: User principal.
        peer_certificates:
          type: number
          description: Number of peer certificates.
        sso_logout_url:
          type: string
          description: Logout url.
        size_of_user:
          type: string
          description: Size of user in memory.
        size_of_custom_attributes:
          type: string
          description: Size of user's custom attributes in bytes.
        size_of_backendroles:
          type: string
          description: Size of backend roles in bytes.

    BadRequest:
      type: object
      properties:
        status:
          type: string
          enum:
            - 400
        message:
          type: string
          description: Message returned as part of BAD_REQUEST response.

    CertificatesDetail:
      type: object
      properties:
        issuer_dn:
          type: string
        subject_dn:
          type: string
        san:
          type: string
        not_before:
          type: string
        not_after:
          type: string

    GetCertificates:
      type: object
      properties:
        http_certificates_list:
          type: array
          items:
            $ref: '#/components/schemas/CertificatesDetail'
        transport_certificates_list:
          type: array
          items:
            $ref: '#/components/schemas/CertificatesDetail'

    ChangePasswordRequestContent:
      type: object
      properties:
        current_password:
          type: string
          description: The current password.
        password:
          type: string
          description: The new password to set.
      required:
        - current_password
        - password

    ComplianceConfig:
      type: object
      properties:
        enabled:
          type: boolean
        write_log_diffs:
          type: boolean
        read_watched_fields: {}
        read_ignore_users:
          type: array
          items:
            type: string
        write_watched_indices:
          type: array
          items:
            type: string
        write_ignore_users:
          type: array
          items:
            type: string
        read_metadata_only:
          type: boolean
        write_metadata_only:
          type: boolean
        external_config:
          type: boolean
        internal_config:
          type: boolean

    ConfigUpgradePayload:
      type: object
      properties:
        config:
          type: array
          description: List of configs to be upgraded.

    CreateTenantParams:
      type: object
      properties:
        description:
          type: string

    DashboardsInfo:
      type: object
      properties:
        user_name:
          type: string
          description: User's name
        not_fail_on_forbidden_enabled:
          type: boolean
          description: Indicates whether DNFOF is enabled.
        opensearch_dashboards_mt_enabled:
          type: boolean
          description: Indicates whether multi-tenancy is enabled.
        opensearch_dashboards_index:
          type: string
          description: Name of the dashboards index.
        opensearch_dashboards_server_user:
          type: string
          description: Name of the user used to connect dashboards to the server.
        multitenancy_enabled:
          type: boolean
          description: Indicates whether multi-tenancy is enabled.
        private_tenant_enabled:
          type: boolean
          description: Indicates whether private tenant is enabled for all users.
        default_tenant:
          type: string
          description: The default tenant setting for the dashboard.
        sign_in_options:
          type: array
          description: List of available sign-in options available.
        password_validation_error_message:
          type: string
          description: Error message when password validation fails.
        password_validation_regex:
          type: string
          description: Reg-ex to be used to perform password validation.

    DistinguishedNames:
      type: object
      properties:
        nodes_dn:
          type: array
          items:
            type: string

    DistinguishedNamesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/DistinguishedNames'

    DynamicConfig:
      type: object
      properties:
        dynamic:
          $ref: '#/components/schemas/DynamicOptions'

    DynamicOptions:
      type: object
      properties:
        filteredAliasMode:
          type: string
        disableRestAuth:
          type: boolean
        disableIntertransportAuth:
          type: boolean
        respectRequestIndicesOptions:
          type: boolean
        kibana: {}
        http: {}
        authc: {}
        authz: {}
        authFailureListeners: {}
        doNotFailOnForbidden:
          type: boolean
        multiRolespanEnabled:
          type: boolean
        hostsResolverMode:
          type: string
        doNotFailOnForbiddenEmpty:
          type: boolean

    GenerateOBOToken:
      type: object
      properties:
        user:
          type: string
          description: The name of the entity requesting token.
        authenticationToken:
          type: string
          description: The generated OBO token.
        durationSeconds:
          type: string
          description: The duration of the token, defaulted to 300s.

    HealthInfo:
      type: object
      properties:
        message:
          type: string
        mode:
          type: string
        status:
          type: string

    IndexPermission:
      type: object
      properties:
        index_patterns:
          type: array
          items:
            type: string
        dls:
          type: string
        fls:
          type: array
          items:
            type: string
        masked_fields:
          type: array
          items:
            type: string
        allowed_actions:
          type: array
          items:
            type: string

    InternalServerError:
      type: object
      properties:
        error:
          type: string
          description: Error message during request execution.

    MethodNotImplemented:
      type: object
      properties:
        status:
          type: string
          enum:
            - 501
        message:
          type: string
          description: Message returned as part of NOT_IMPLEMENTED response.

    MultiTenancyConfig:
      type: object
      properties:
        default_tenant:
          type: string
        private_tenant_enabled:
          type: boolean
        multitenancy_enabled:
          type: boolean
        sign_in_options:
          type: array
          items:
            type: string
          description: Value in seconds.

    OBOToken:
      type: object
      properties:
        description:
          type: string
          description: Contains the description supplied by the user to describe the token.
        service:
          type: string
          description: A name of the service if generating a token for that service.
        duration:
          type: string
          description: Value in seconds.
      required:
        - description

    Ok:
      type: object
      properties:
        status:
          type: string
          enum:
            - 200
        message:
          type: string
          description: Message returned as part of OK response.

    PatchOperation:
      type: object
      properties:
        op:
          type: string
          description: 'The operation to perform. Possible values: remove, add, replace, move, copy, test.'
        path:
          type: string
          description: The path to the resource.
        value:
          description: The new values used for the update.
      required:
        - op
        - path

    PermissionsInfo:
      type: object
      properties:
        user:
          type: string
        user_name:
          type: string
        has_api_access:
          type: boolean
        disabled_endpoints:
          type: object
          description: An object with disabled APIs as key and array of http methods as values.

    Role:
      type: object
      properties:
        reserved:
          type: boolean
        hidden:
          type: boolean
        description:
          type: string
        cluster_permissions:
          type: array
          items:
            type: string
        index_permissions:
          type: array
          items:
            $ref: '#/components/schemas/IndexPermission'
        tenant_permissions:
          type: array
          items:
            $ref: '#/components/schemas/TenantPermission'
        static:
          type: boolean

    RoleMapping:
      type: object
      properties:
        hosts:
          type: array
          items:
            type: string
        users:
          type: array
          items:
            type: string
        reserved:
          type: boolean
        hidden:
          type: boolean
        backend_roles:
          type: array
          items:
            type: string
        and_backend_roles:
          type: array
          items:
            type: string
        description:
          type: string

    RoleMappings:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/RoleMapping'

    RolesMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Role'

    SSLInfo:
      type: object
      properties:
        principal:
          type: string
          description: User principal.
        peer_certificates:
          type: number
          description: Number of certificates.
        peer_certificates_list:
          type: array
          description: List of domain names from peer certificates.
        local_certificates_list:
          type: array
          description: List of domain names from local certificates.
        ssl_protocol:
          type: string
          description: Protocol for this ssl setup.
        ssl_cipher:
          type: string
          description: Cipher for this ssl setup.
        ssl_openssl_available:
          type: boolean
          description: A boolean to indicate if OpenSSL is available.
        ssl_openssl_version:
          type: string
          description: Version of openssl.
        ssl_openssl_version_string:
          type: string
          description: Full version string for openssl version.
        ssl_openssl_non_available_cause:
          type: string
          description: Reason for openssl unavailability.
        ssl_openssl_supports_key_manager_factory:
          type: boolean
          description: Indicates where KMF is supported.
        ssl_openssl_supports_hostname_validation:
          type: boolean
          description: Indicates whether hostname validation is supported.
        ssl_provider_http:
          type: string
          description: Returns http provider's name.
        ssl_provider_transport_server:
          type: string
          description: Returns transport server's name.
        ssl_provider_transport_client:
          type: string
          description: Returns transport client's name.

    Tenant:
      type: object
      properties:
        reserved:
          type: boolean
        hidden:
          type: boolean
        description:
          type: string
        static:
          type: boolean

    TenantPermission:
      type: object
      properties:
        tenant_patterns:
          type: array
          items:
            type: string
        allowed_actions:
          type: array
          items:
            type: string

    TenantsMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Tenant'

    Unauthorized:
      type: object
      properties:
        status:
          type: string
          enum:
            - 403
        message:
          type: string
          description: Message returned as part of FORBIDDEN response.

    UpgradeCheck:
      type: object
      properties:
        status:
          type: string
        upgradeAvailable:
          type: boolean
        upgradeActions:
          type: object

    UpgradePerform:
      type: object
      properties:
        status:
          type: string
        upgrades:
          type: object

    User:
      type: object
      properties:
        hash:
          type: string
        reserved:
          type: boolean
        hidden:
          type: boolean
        backend_roles:
          type: array
          items:
            type: string
        attributes:
          $ref: '#/components/schemas/UserAttributes'
        description:
          type: string
        opendistro_security_roles:
          type: array
          items:
            type: string
        static:
          type: boolean

    UserAttributes:
      type: object
      additionalProperties:
        type: string

    UserTenants:
      type: object
      properties:
        global_tenant:
          type: boolean
        admin_tenant:
          type: boolean
        admin:
          type: boolean

    UsersMap:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/User'

    WhoAmI:
      type: object
      properties:
        dn:
          type: string
        is_admin:
          type: string
        is_node_certificate_request:
          type: string

    TenantInfo:
      type: object
      additionalProperties:
        type: string
