openapi: 3.1.0
info:
  title: Schemas of snapshot._common category
  description: Schemas of snapshot._common category
  version: 1.0.0
paths: {}
components:
  schemas:
    SnapshotInfo:
      type: object
      properties:
        data_streams:
          type: array
          items:
            type: string
        duration:
          $ref: '_common.yaml#/components/schemas/Duration'
        duration_in_millis:
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
        end_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
        end_time_in_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        failures:
          type: array
          items:
            $ref: '#/components/schemas/SnapshotShardFailure'
        include_global_state:
          type: boolean
        indices:
          type: array
          items:
            $ref: '_common.yaml#/components/schemas/IndexName'
        index_details:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IndexDetails'
        metadata:
          $ref: '_common.yaml#/components/schemas/Metadata'
        reason:
          type: string
        repository:
          $ref: '_common.yaml#/components/schemas/Name'
        snapshot:
          $ref: '_common.yaml#/components/schemas/Name'
        shards:
          $ref: '_common.yaml#/components/schemas/ShardStatistics'
        start_time:
          $ref: '_common.yaml#/components/schemas/DateTime'
        start_time_in_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        state:
          type: string
        uuid:
          $ref: '_common.yaml#/components/schemas/Uuid'
        version:
          $ref: '_common.yaml#/components/schemas/VersionString'
        version_id:
          $ref: '_common.yaml#/components/schemas/VersionNumber'
        feature_states:
          type: array
          items:
            $ref: '#/components/schemas/InfoFeatureState'
      required:
        - data_streams
        - snapshot
        - uuid
    SnapshotShardFailure:
      type: object
      properties:
        index:
          $ref: '_common.yaml#/components/schemas/IndexName'
        node_id:
          $ref: '_common.yaml#/components/schemas/Id'
        reason:
          type: string
        shard_id:
          $ref: '_common.yaml#/components/schemas/Id'
        status:
          type: string
      required:
        - index
        - reason
        - shard_id
        - status
    IndexDetails:
      type: object
      properties:
        shard_count:
          type: number
        size:
          $ref: '_common.yaml#/components/schemas/ByteSize'
        size_in_bytes:
          type: number
        max_segments_per_shard:
          type: number
      required:
        - shard_count
        - size_in_bytes
        - max_segments_per_shard
    InfoFeatureState:
      type: object
      properties:
        feature_name:
          type: string
        indices:
          $ref: '_common.yaml#/components/schemas/Indices'
      required:
        - feature_name
        - indices
    Repository:
      type: object
      properties:
        type:
          type: string
        uuid:
          $ref: '_common.yaml#/components/schemas/Uuid'
        settings:
          $ref: '#/components/schemas/RepositorySettings'
      required:
        - type
        - settings
    RepositorySettings:
      type: object
      properties:
        chunk_size:
          type: string
        compress:
          oneOf:
            - type: string
            - type: boolean
        concurrent_streams:
          oneOf:
            - type: string
            - type: number
        location:
          type: string
        read_only:
          oneOf:
            - type: string
            - type: boolean
      required:
        - location
    Status:
      type: object
      properties:
        include_global_state:
          type: boolean
        indices:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SnapshotIndexStats'
        repository:
          type: string
        shards_stats:
          $ref: '#/components/schemas/ShardsStats'
        snapshot:
          type: string
        state:
          type: string
        stats:
          $ref: '#/components/schemas/SnapshotStats'
        uuid:
          $ref: '_common.yaml#/components/schemas/Uuid'
      required:
        - include_global_state
        - indices
        - repository
        - shards_stats
        - snapshot
        - state
        - stats
        - uuid
    SnapshotIndexStats:
      type: object
      properties:
        shards:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SnapshotShardsStatus'
        shards_stats:
          $ref: '#/components/schemas/ShardsStats'
        stats:
          $ref: '#/components/schemas/SnapshotStats'
      required:
        - shards
        - shards_stats
        - stats
    SnapshotShardsStatus:
      type: object
      properties:
        stage:
          $ref: '#/components/schemas/ShardsStatsStage'
        stats:
          $ref: '#/components/schemas/ShardsStatsSummary'
      required:
        - stage
        - stats
    ShardsStatsStage:
      type: string
      enum:
        - DONE
        - FAILURE
        - FINALIZE
        - INIT
        - STARTED
    ShardsStatsSummary:
      type: object
      properties:
        incremental:
          $ref: '#/components/schemas/ShardsStatsSummaryItem'
        total:
          $ref: '#/components/schemas/ShardsStatsSummaryItem'
        start_time_in_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        time:
          $ref: '_common.yaml#/components/schemas/Duration'
        time_in_millis:
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
      required:
        - incremental
        - total
        - start_time_in_millis
        - time_in_millis
    ShardsStatsSummaryItem:
      type: object
      properties:
        file_count:
          type: number
        size_in_bytes:
          type: number
      required:
        - file_count
        - size_in_bytes
    ShardsStats:
      type: object
      properties:
        done:
          type: number
        failed:
          type: number
        finalizing:
          type: number
        initializing:
          type: number
        started:
          type: number
        total:
          type: number
      required:
        - done
        - failed
        - finalizing
        - initializing
        - started
        - total
    SnapshotStats:
      type: object
      properties:
        incremental:
          $ref: '#/components/schemas/FileCountSnapshotStats'
        start_time_in_millis:
          $ref: '_common.yaml#/components/schemas/EpochTimeUnitMillis'
        time:
          $ref: '_common.yaml#/components/schemas/Duration'
        time_in_millis:
          $ref: '_common.yaml#/components/schemas/DurationValueUnitMillis'
        total:
          $ref: '#/components/schemas/FileCountSnapshotStats'
      required:
        - incremental
        - start_time_in_millis
        - time_in_millis
        - total
    FileCountSnapshotStats:
      type: object
      properties:
        file_count:
          type: number
        size_in_bytes:
          type: number
      required:
        - file_count
        - size_in_bytes
