openapi: 3.1.0
info:
  title: Schemas of `snapshot.cleanup_repository` Category
  description: Schemas of `snapshot.cleanup_repository` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    CleanupRepositoryResults:
      type: object
      properties:
        deleted_blobs:
          description: Number of binary large objects (blobs) removed during cleanup.
          type: integer
          format: int64
        deleted_bytes:
          description: Number of bytes freed by cleanup operations.
          type: integer
          format: int64
      required:
        - deleted_blobs
        - deleted_bytes
