openapi: 3.1.0
info:
  title: Schemas of snapshot.verify_repository category
  description: Schemas of snapshot.verify_repository category
  version: 1.0.0
paths: {}
components:
  schemas:
    CompactNodeInfo:
      type: object
      properties:
        name:
          $ref: '_common.yaml#/components/schemas/Name'
      required:
        - name
