openapi: 3.1.0
info:
  title: Schemas of `snapshot.s3` Category
  description: Schemas of `snapshot.s3` category (repository-s3 plugin).
  version: 1.0.0
paths: {}
components:
  schemas:
    RepositorySettingsS3:
      type: object
      description: The settings for the S3 snapshot repository.
      properties:
        base_path:
          type: string
          description: The path within the bucket in which you want to store snapshots.
        bucket:
          type: string
          description: Name of the S3 bucket.
        region:
          type: string
          description: The AWS Region in which the S3 bucket is located.
        endpoint:
          type: string
          description: The S3 bucket endpoint.
        buffer_size:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
          description: The buffer size for the repository.
        canned_acl:
          type: string
          description: S3 canned ACL that is added to objects.
        chunk_size:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
          description: The chunk size for the repository.
        client:
          type: string
          description: Client for which settings have been provided (e.g. default).
        compress:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Whether compression is enabled for the repository.
        disable_chunked_encoding:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Disables chunked encoding for compatibility with some storage services.
        max_restore_bytes_per_sec:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
          description: The maximum rate at which snapshots restore.
        max_snapshot_bytes_per_sec:
          $ref: '_common.yaml#/components/schemas/HumanReadableByteCount'
          description: The maximum rate at which snapshots take.
        readonly:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Whether the repository is read-only.
        remote_store_index_shallow_copy:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Determines whether the snapshot of the remote store indexes are captured as a shallow copy.
        shallow_snapshot_v2:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Determines whether the snapshots of the remote store indexes are captured as a shallow copy v2.
        storage_class:
          type: string
          description: S3 storage class
        server_side_encryption_type:
          type: string
          description: S3 server-side encryption type.
        server_side_encryption_kms_key_id:
          type: string
          description: AWS KMS key to be used when using S3 SSE-KMS.
        server_side_encryption_bucket_key_enabled:
          $ref: '_common.yaml#/components/schemas/StringifiedBoolean'
          description: Specifies whether S3 Bucket Keys should be used when using S3 SSE-KMS.
        server_side_encryption_encryption_context:
          type: object
          description: Specifies any additional encryption context that should be used when using S3 SSE-KMS.
        expected_bucket_owner:
          type: string
          description: Specifies the AWS account ID of the expected S3 bucket owner.
      required:
          - bucket