openapi: 3.1.0
info:
  title: Schemas of `snapshot.restore` Category
  description: Schemas of `snapshot.restore` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    SnapshotRestore:
      type: object
      properties:
        indices:
          type: array
          description: The list of indexes that were restored.
          items:
            $ref: '_common.yaml#/components/schemas/IndexName'
        snapshot:
          type: string
          description: The name of the snapshot that was restored.
        shards:
          $ref: '_common.yaml#/components/schemas/ShardStatistics'
          description: Any statistics about the restored shards.
      required:
        - indices
        - shards
        - snapshot