openapi: 3.1.0
info:
  title: Schemas of tier_warm category
  description: Schemas of tier_warm category
  version: 1.0.0
paths: {}
components:
  schemas:
    FailedIndex:
      type: object
      properties:
        index:
          description: Index name.
          $ref: '_common.yaml#/components/schemas/IndexName'
        error:
          description: Error message.
          type: string