openapi: 3.1.0
info:
  title: Schemas of `wlm._common` Category
  description: Schemas of `wlm._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    QueryGroupResponse:
      type: object
      properties:
        _id:
          description: The ID of the query group, which can be used to associate query requests with the group and enforce the group's resource limits.
          type: string
        name:
          description: The name of the query group.
          type: string
        resiliency_mode:
          description: The resiliency mode of the query group.
          type: string
          enum: [enforced, monitor,soft]
        updated_at:
          description: The time at which the query group was last updated.
          type: integer
          format: int64
        resource_limits:
          description: The resource limits for query requests in the query group.
          anyOf:
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - memory
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - cpu
      required:
        - _id
        - name
        - resiliency_mode
        - resource_limits
        - updated_at
    QueryGroupCreate:
      type: object
      properties:
        name:
          type: string
        resiliency_mode:
          type: string
          enum: [enforced, monitor,soft]
        resource_limits:
          anyOf:
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - memory
            - type: object
              properties:
                memory:
                  type: number
                  format: double
                cpu:
                  type: number
                  format: double
              required:
                - cpu
      required:
        - name
        - resiliency_mode
        - resource_limits
    QueryGroupUpdate:
      type: object
      properties:
        resiliency_mode:
          type: string
          enum: [enforced, monitor,soft]
        resource_limits:
          $ref: '#/components/schemas/ResourceLimitsSchema'
    ResourceLimitsSchema:
      type: object
      properties:
        memory:
          type: number
          format: double
        cpu:
          type: number
          format: double
