/*
* Copyright OpenSearch Contributors
* SPDX-License-Identifier: Apache-2.0
*
* The OpenSearch Contributors require contributions made to
* this file be licensed under the Apache-2.0 license or a
* compatible open source license.
*/

/* eslint-disable @typescript-eslint/consistent-indexed-object-style */

/*
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file by running:
 * "npm run generate-types" in a terminal.
 */

export interface SupersededOperations {
  /**
   * This interface was referenced by `SupersededOperations`'s JSON-Schema definition
   * via the `patternProperty` "^/".
   */
  [k: string]: {
    superseded_by: string;
    operations: ('GET' | 'POST' | 'PUT' | 'DELETE' | 'HEAD' | 'OPTIONS' | 'PATCH')[];
  };
}


/* eslint-enable @typescript-eslint/consistent-indexed-object-style */
