name: Build and Publish Spec

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '24'

      - name: Build
        run: npm ci && npm run merge

      - name: Extract Branch Name
        id: branch
        shell: bash
        run: echo "name=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build
          path: |
            build/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6
        with:
          role-to-assume: ${{ secrets.LUCENE_SNAPSHOTS_SECRET_ROLE }}
          aws-region: us-east-1

      - name: Get S3 Bucket
        id: get_s3_bucket
        run: |
          lucene_snapshots_bucket=`aws secretsmanager get-secret-value --secret-id jenkins-artifact-bucket-name --query SecretString --output text`
          echo "::add-mask::$lucene_snapshots_bucket"
          echo "LUCENE_SNAPSHOTS_BUCKET=$lucene_snapshots_bucket" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@d979d5b3a71173a29b74b5b88418bfda9437d885 # v6
        with:
          role-to-assume: ${{ secrets.LUCENE_SNAPSHOTS_S3_ROLE }}
          aws-region: us-east-1

      - name: Copy files to S3 with the aws CLI (New)
        run: |
          cd build/
          aws s3 cp ./opensearch-openapi.yaml s3://${{ steps.get_s3_bucket.outputs.LUCENE_SNAPSHOTS_BUCKET }}/snapshots/opensearch-api-specification/opensearch-openapi.yaml  --recursive --no-progress
          aws s3 cp ./LICENSE.txt s3://${{ steps.get_s3_bucket.outputs.LUCENE_SNAPSHOTS_BUCKET }}/snapshots/opensearch-api-specification/LICENSE.txt  --recursive --no-progress
          curl -SfL https://github.com/opensearch-project/opensearch-api-specification/archive/refs/heads/main.zip -o main-latest.zip
          aws s3 cp ./main-latest.zip s3://${{ steps.get_s3_bucket.outputs.LUCENE_SNAPSHOTS_BUCKET }}/snapshots/opensearch-api-specification/main-latest.zip  --recursive --no-progress
