name: Gather API Coverage

on: [push, pull_request]

env:
  JAVA_VERSION: 11
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: BobgG7YrtsdKf9M

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build Spec
        working-directory: ./tools
        run: |-
          mkdir -p ../build
          npm install
          export ROOT_PATH=../spec
          export OUTPUT_PATH=../build/opensearch-openapi.yaml
          npm run merge -- $ROOT_PATH $OUTPUT_PATH
      - name: Build and Run Docker Container
        run: |
          docker build coverage --tag opensearch-with-api-plugin
          docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" -e OPENSEARCH_INITIAL_ADMIN_PASSWORD="$OPENSEARCH_INITIAL_ADMIN_PASSWORD" opensearch-with-api-plugin
          sleep 15
      - name: Display OpenSearch Info
        run: |
          curl -ks -u "admin:$OPENSEARCH_INITIAL_ADMIN_PASSWORD" https://localhost:9200/ | jq
      - name: Dump and Compare API
        run: |
          curl -ks -u "admin:$OPENSEARCH_INITIAL_ADMIN_PASSWORD" https://localhost:9200/_plugins/api | jq > ./build/local-openapi.json
          docker run --rm --mount type=bind,source=./build,target=/build openapitools/openapi-diff:latest /build/opensearch-openapi.yaml /build/local-openapi.json --json /build/diff.json
      - name: Show Diff
        run: |
          echo "-------- Missing APIs"
          jq -r '.newEndpoints | group_by(.pathUrl)[] | "\(.[0].pathUrl): \([.[].method])"' build/diff.json
          echo "-------- Legacy APIs"
          jq -r '.missingEndpoints | group_by(.pathUrl)[] | "\(.[0].pathUrl): \([.[].method])"' build/diff.json
      - name: Gather Coverage
        id: coverage
        shell: bash
        run: |
          current=`docker run --rm -i mikefarah/yq:latest -r '.paths | keys | length' < build/opensearch-openapi.yaml`
          total=`jq -r '.paths | keys | length' build/local-openapi.json`
          percent=$((current * 100 / total))
          echo "API specs implemented for $current/$total ($percent%) APIs."
          cat >>"coverage.json" <<EOL
          {
            "pull_request":${{ github.event.number }},
            "current":$current,
            "total":$total,
            "percent":$percent
          }
          EOL
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.json