name: Lint

on:
  push:
    branches: ['**']
    paths:
      - 'cmd/osapispec/**'
  pull_request:
    branches: ['**']
    paths:
      - 'cmd/osapispec/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cmd/osapispec/go.mod
          cache-dependency-path: cmd/osapispec/go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.12
          working-directory: cmd/osapispec
