name: Proto Compatibility Comment

on:
  workflow_run:
    workflows:
      - Proto Compatibility Check
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: refs/heads/main
          sparse-checkout: |
            .github

      - name: Download Proto Comment Payload
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: proto-comment-payload
          run-id: ${{ github.event.workflow_run.id }}

      - name: Parse Payload
        shell: bash -eo pipefail {0}
        run: |
          PR_NUMBER=$(jq -r '.pr_number' ./proto-comment-payload.json)
          REPORT=$(jq -r '.report' ./proto-comment-payload.json)

          vars=(
            PR_NUMBER
          )

          {
            for var in "${vars[@]}"
            do
              echo "${var}=${!var}"
            done
          } | tee "$GITHUB_ENV"

          # Save report to environment variable
          echo "REPORT_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$REPORT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Find Existing Comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
        id: fc
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: Proto Compatibility Report

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ env.PR_NUMBER }}
          body: |
            ## Proto Compatibility Report

            ${{ env.REPORT_CONTENT }}

            ---
            *Generated by Proto Compatibility Check*
          edit-mode: replace
