name: Draft a Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  draft-a-release:
    name: Draft a Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get Current Version
        id: current
        run: |
          echo version=$(yq .version spec/_info.yaml) >> "$GITHUB_OUTPUT"

      - name: Check Version
        run: |
          echo current=v${{ steps.current.outputs.version }}
          echo tag=${{ github.ref_name }}
          if "v${{ steps.current.outputs.version }}" != "${{ github.ref_name }}"; then
            echo "::error::Failing, reason: version ${{ steps.current.outputs.version }} does not match tag ${{ github.ref_name }}."
            exit 1
          else
            echo "::notice::Found version ${{ steps.current.outputs.version }}, all good."
          fi

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20'

      - name: Build
        run: npm ci && npm run merge

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build
          path: |
            build/*

      - name: Extract Changelog
        id: changelog
        uses: sean0x42/markdown-extract@7b185cbe85263116bbf741e739e7198ba86465dc # v2.1.0
        with:
          file: CHANGELOG.md
          pattern: Unreleased
          no-print-matched-heading: true

      - name: Draft a release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        id: release
        with:
          draft: true
          generate_release_notes: false
          tag_name: ${{ github.ref_name }}
          body: |
            ${{ steps.changelog.outputs.markdown }}

            ### Links
            - [Build Artifact](${{ steps.upload.outputs.artifact-url }})
          files: |
            LICENSE.txt
            build/*

      - name: Increment Version
        uses: nguyenvukhang/semver-increment@38a3e3f41cfd66c9b0cef7dac0370bb642371574 # v1.0.3
        id: version
        with:
          increment: patch
          version-file: spec/_info.yaml
          version-regex: '^version: (.*)'

      - name: Update CHANGELOG to the Next Developer Iteration
        uses: thomaseizinger/keep-a-changelog-new-release@f62c3c390716df5af712ba5d94f4f4a8efc1306d # 3.1.0
        with:
          tag: ${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Preparing for next developer iteration ${{ steps.version.outputs.version }}.'
          signoff: true
          branch: prepare-v-next
          base: main
          delete-branch: true
          title: 'Preparing for next developer iteration, ${{ steps.version.outputs.version }}.'
          body: |
            I've drafted a release, [${{ github.ref_name }}](${{ steps.release.outputs.url }}), please verify and release it.
            Preparing for the next developer iteration, ${{ steps.version.outputs.version }}.
