name: Test Tools (Integration)

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/test-tools*.yml'
      - 'cmd/osapispec/**'
  pull_request:
    branches: ['**']
    paths:
      - '.github/workflows/test-tools*.yml'
      - 'cmd/osapispec/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENSEARCH_VERSION: 3.6.0
      OPENSEARCH_PASSWORD: myStrongPassword123!
      OPENSEARCH_URL: https://localhost:9200
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run OpenSearch Cluster
        working-directory: tests/default
        run: |
          docker compose up -d
          sleep 15

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cmd/osapispec/go.mod
          cache-dependency-path: cmd/osapispec/go.sum

      - name: Run Integration Tests
        run: |
          go run . test \
            -insecure \
            -url=${{ env.OPENSEARCH_URL }} \
            -password=${{ env.OPENSEARCH_PASSWORD }} \
            -tests=../../tests/default
        working-directory: cmd/osapispec
