name: Test Tools

on:
  push:
    branches: ['**']
    paths:
      - '.github/workflows/test-tools*.yml'
      - 'cmd/osapispec/**'
  pull_request:
    branches: ['**']
    paths:
      - '.github/workflows/test-tools*.yml'
      - 'cmd/osapispec/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: cmd/osapispec/go.mod
          cache-dependency-path: cmd/osapispec/go.sum

      - name: Test
        working-directory: cmd/osapispec
        run: go test -race -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cmd/osapispec/coverage.out
