name: Update OpenAPI specs
on: 
  push:
    branches:
      - main

jobs:
  update:
    if: github.repository == 'opensearch-project/opensearch-api-specification'
    runs-on: ubuntu-latest
    steps:
      - name: GitHub App token
        id: github_app_token
        uses: tibdex/github-app-token@v1.5.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          installation_id: 22958780

      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build
        run: ./gradlew build
      
      - name: Move OpenAPI specs to root
        run: mv build/smithyprojections/opensearch-api-specification/source/openapi/OpenSearch.openapi.json .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.github_app_token.outputs.token }}
          commit-message: Update OpenAPI specs
          signoff: true
          title: Update OpenAPI specs
          body: |
            I've noticed an update to the models. This pull request updates the OpenAPI specs accordingly.
          branch: create-pull-request/specs-update
