name: Validate Spec (Python)

on: [pull_request,push]

jobs:
  validate-spec-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: '20'

      - name: Build
        run: npm ci && npm run merge

      - name: Set Up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        working-directory: tools/src/validate-spec-py
        run: |
          pip install --user pipenv
          pipenv install

      - name: Validate Spec
        working-directory: tools/src/validate-spec-py
        run: |
          pipenv run python validate.py ../../../build/opensearch-openapi.yaml
