name: Validate Spec (Python)

on: [pull_request,push]

jobs:
  validate-spec-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '20'

      - name: Build
        run: npm ci && npm run merge

      - name: Set Up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.12'

      - name: Install Dependencies
        working-directory: tools/src/validate-spec-py
        run: |
          pip install --user pipenv
          pipenv install

      - name: Validate Spec
        working-directory: tools/src/validate-spec-py
        run: |
          pipenv run python validate.py ../../../build/opensearch-openapi.yaml
