openapi: 3.1.0
info:
  title: OpenSearch Tasks API
  description: OpenSearch Tasks API
  version: 1.0.0
paths:
  /_tasks:
    get:
      description: Returns a list of tasks.
      externalDocs:
        description: API Reference
        url: https://opensearch.org/docs/latest/api-reference/tasks/
      operationId: TasksList
      parameters:
        - name: nodes
          in: query
          description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return
            information from the node you're connecting to, leave empty to get information from all nodes.
          style: form
          schema:
            type: array
            items:
              type: string
            description: Comma-separated list of node IDs or names to limit the returned information; use `_local` to return
              information from the node you're connecting to, leave empty to get information from all nodes.
          explode: true
        - in: query
          name: actions
          description: Comma-separated list or wildcard expression of actions used to limit the request.
          deprecated: false
          schema:
            oneOf:
              - type: string
              - type: array
                items:
                  type: string
          style: form
        - in: query
          name: detailed
          description: If `true`, the response includes detailed information about shard recoveries.
          deprecated: false
          schema:
            type: boolean
          style: form
        - in: query
          name: parent_task_id
          description: Parent task ID used to limit returned information. To return all tasks, omit this parameter or use a value
            of `-1`.
          deprecated: false
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/Id'
          style: form
        - in: query
          name: wait_for_completion
          description: If `true`, the request blocks until the operation is complete.
          deprecated: false
          schema:
            type: boolean
          style: form
        - in: query
          name: group_by
          description: Key used to group tasks in the response.
          deprecated: false
          schema:
            $ref: '../schemas/tasks._common.yaml#/components/schemas/GroupBy'
          style: form
        - in: query
          name: timeout
          description: Period to wait for a response. If no response is received before the timeout expires, the request fails and
            returns an error.
          deprecated: false
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/Duration'
          style: form
      responses:
        '200':
          $ref: '#/components/responses/tasks.list#200'
      x-operation-group: tasks.list
      x-version-added: '1.0'
  /_tasks/_cancel:
    post:
      description: Cancels a task, if it can be cancelled through an API.
      externalDocs:
        description: API Reference
        url: https://opensearch.org/docs/latest/api-reference/tasks/#task-canceling
      operationId: TasksCancel
      parameters:
        - $ref: '#/components/parameters/tasks.cancel#nodes'
        - $ref: '#/components/parameters/tasks.cancel#actions'
        - $ref: '#/components/parameters/tasks.cancel#parent_task_id'
        - $ref: '#/components/parameters/tasks.cancel#wait_for_completion'
      responses:
        '200':
          $ref: '#/components/responses/tasks.cancel#200'
      x-operation-group: tasks.cancel
      x-version-added: '1.0'
  /_tasks/{task_id}:
    get:
      description: Returns information about a task.
      externalDocs:
        description: API Reference
        url: https://opensearch.org/docs/latest/api-reference/tasks/
      operationId: TasksGet
      parameters:
        - in: path
          name: task_id
          description: ID of the task.
          required: true
          deprecated: false
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/Id'
          style: simple
        - in: query
          name: wait_for_completion
          description: If `true`, the request blocks until the task has completed.
          deprecated: false
          schema:
            type: boolean
          style: form
        - in: query
          name: timeout
          description: |-
            Period to wait for a response.
            If no response is received before the timeout expires, the request fails and returns an error.
          deprecated: false
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/Duration'
          style: form
      responses:
        '200':
          $ref: '#/components/responses/tasks.get#200'
      x-operation-group: tasks.get
      x-version-added: '1.0'
  /_tasks/{task_id}/_cancel:
    post:
      description: Cancels a task, if it can be cancelled through an API.
      operationId: TasksCancel_WithTaskId
      parameters:
        - $ref: '#/components/parameters/tasks.cancel#task_id'
        - $ref: '#/components/parameters/tasks.cancel#nodes'
        - $ref: '#/components/parameters/tasks.cancel#actions'
        - $ref: '#/components/parameters/tasks.cancel#parent_task_id'
        - $ref: '#/components/parameters/tasks.cancel#wait_for_completion'
      responses:
        '200':
          $ref: '#/components/responses/tasks.cancel#200'
      x-operation-group: tasks.cancel
      x-version-added: '1.0'
components:
  requestBodies: {}
  responses:
    tasks.cancel#200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/tasks._common.yaml#/components/schemas/TaskListResponseBase'
    tasks.list#200:
      description: ''
      content:
        application/json:
          schema:
            $ref: '../schemas/tasks._common.yaml#/components/schemas/TaskListResponseBase'
    tasks.get#200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              completed:
                type: boolean
              task:
                $ref: '../schemas/tasks._common.yaml#/components/schemas/TaskInfo'
              response:
                type: object
              error:
                $ref: '../schemas/_common.yaml#/components/schemas/ErrorCause'
            required:
              - completed
              - task
  parameters:
    tasks.cancel#task_id:
      in: path
      name: task_id
      description: ID of the task.
      required: true
      deprecated: false
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/TaskId'
      style: simple
    tasks.cancel#actions:
      in: query
      name: actions
      description: Comma-separated list or wildcard expression of actions used to limit the request.
      deprecated: false
      schema:
        oneOf:
          - type: string
          - type: array
            items:
              type: string
      style: form
    tasks.cancel#nodes:
      in: query
      name: nodes
      description: Comma-separated list of node IDs or names used to limit the request.
      deprecated: false
      schema:
        type: array
        items:
          type: string
      style: form
    tasks.cancel#parent_task_id:
      in: query
      name: parent_task_id
      description: Parent task ID used to limit the tasks.
      deprecated: false
      schema:
        type: string
      style: form
    tasks.cancel#wait_for_completion:
      in: query
      name: wait_for_completion
      description: Should the request block until the cancellation of the task and its descendant tasks is completed. Defaults
        to false
      deprecated: false
      schema:
        type: boolean
      style: form
